### PR TITLE
Fixes #460: OnlineIndexer fails to getPrimaryKeyBoundaries when there is no boundary

### LINKED ISSUE #460: OnlineIndexer fails to getPrimaryKeyBoundaries when there is no boundary

### PR DESCRIPTION
**Pull request by nblintao**

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java [hunk 1]
```diff
@@ -2147,6 +2147,50 @@ public void boundaryPrimaryKeys() throws Exception {
         indexer.close();
     }
 
+    @Test
+    public void noBoundaryPrimaryKeys() throws Exception {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java]: I'm somewhat concerned about the flakiness of the test. In particular, there's no guarantee that there won't be any boundaries. There aren't any guarantees in the other test (I suppose), but it seems more likely to me that this will spuriously report a boundary rather than the other test spuriously not reporting a boundary, but maybe I'm wrong.
