### PR TITLE
Resolves #1674: Lucene scans without queries

### LINKED ISSUE #1674: Lucene scans without queries
`planOther` is not called when there is no filter at all. But the only filter(s) might be on the grouping key(s).

The code does the correct thing today. A single filter will not match `getQueryForFilter`. And an `And` will fail to match any of its children. However, that child filter check lacks a comment about why it is there, in as much as this is policy and not correctness.

So mostly this is about documentation and tests.

Still, it is possible to determine that the passed-on filter only had group filters after initially matching them and stop.

### PR DESCRIPTION
**Pull request by MMcM**
Note that this does not change any generated plans. It just tries to make the logic for excluding vacuous queries more clear and better commented. And adds a couple tests.

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 1]
```diff
@@ -905,4 +906,39 @@ void covering() throws Exception {
...
+            QueryComponent groupFilter = Query.and(
+                    Query.field("group").equalsValue(1L),
+                    Query.field("entry").oneOfThem().matches(Query.field("key").equalsValue("a")));
+            RecordQuery query = RecordQuery.newBuilder()
+                    .setRecordType(MAP_DOC)
+                    .setFilter(groupFilter)
+                    .build();
+            RecordQueryPlan plan = planner.plan(query);
+            Matcher<RecordQueryPlan> matcher = filter(groupFilter, typeFilter(equalTo(Collections.singleton(TextIndexTestUtils.MAP_DOC)), scan(unbounded())));
+            assertThat(plan, matcher);
```
Comment (alecgrieser) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:940]: Is there a test showing that the plan actually executes correctly (that is, that it returns all results and doesn't trip over the lack of bounds)?

**Review by alecgrieser — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 1 above)
Comment (MMcM) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:940]: I think the reasoning was that this need only check that a non-Lucene plan is generated and that such tests would exist in the core.

Comment (alecgrieser) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:940]: Oh, I see--the plan in question is a full store scan, not an unbounded scan of the index. Got it

**Review by alecgrieser — APPROVED** [review]
