### PR TITLE
Resolves #712: Support validating missing index entries

### LINKED ISSUE #712: Support validating missing index entries
Currently, there is no good way to see if there are index entries missing unexpectedly.

My earlier issue https://github.com/FoundationDB/fdb-record-layer/issues/383 can help validate corrupted data if there is no data entry corresponding to an index entry. This radar is the other side of the coin.

### PR DESCRIPTION
**Pull request by nblintao**

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java [hunk 1]
```diff
@@ -392,22 +396,50 @@ public void updateUniquenessViolations(@Nonnull Tuple valueKey, @Nonnull Tuple p
...
-                        FDBRecordStore.DEFAULT_PIPELINE_SIZE)
-                .map(indexEntry ->
-                        new InvalidIndexEntry(indexEntry, InvalidIndexEntry.Reasons.ORPHAN));
+                        DEFAULT_PIPELINE_SIZE)
+                .map(InvalidIndexEntry::newOrphan);
+    }
+
+    /**
+     * Validate entries in the index. It scans the records and checks if the index entries associated with each record
+     * exist. Note that it may not work for synthetic indexes.
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java]: You should clarify what you mean by "synthetic indexes".  I think you probably mean indexes that act as materialized views and do not actually point to base records, such as aggregate indexes.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java [hunk 2]
```diff
@@ -392,22 +396,50 @@ public void updateUniquenessViolations(@Nonnull Tuple valueKey, @Nonnull Tuple p
...
+                                    ))
+                                    .map(indexEntry -> Pair.of(indexEntry, record))
+                                    .collect(Collectors.toList()),
+                            cont);
+                },
+                continuation, DEFAULT_PIPELINE_SIZE)
+        .filterAsync(indexEntryRecordPair -> {
+            final byte[] keyBytes = state.indexSubspace.pack(indexEntryRecordPair.getLeft().getKey());
+            return state.transaction.get(keyBytes).thenApply(Objects::isNull);
+        }, DEFAULT_PIPELINE_SIZE)
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/StandardIndexMaintainer.java]: Given that this is reading records and looking for entries, maybe this shouldn't just use the default pipeline size and should instead have it configurable.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexMaintainer.java [hunk 3]
```diff
@@ -75,7 +76,17 @@ public ValueIndexMaintainer(IndexMaintainerState state) {
     @Override
     public RecordCursor<InvalidIndexEntry> validateEntries(@Nullable byte[] continuation,
                                                            @Nullable ScanProperties scanProperties) {
-        return validateOrphanEntries(continuation, scanProperties);
+        if (scanProperties == null) {
+            scanProperties = new ScanProperties(ExecuteProperties.newBuilder()
+                    .setReturnedRowLimit(Integer.MAX_VALUE)
+                    // For orphan index entry validation, it does not hurt to have a weaker isolation.
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexMaintainer.java]: Since this does both orphaned entries and missing entries, maybe the comment should just say `// For index entry validation, ...`

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/PipelineOperation.java [hunk 4]
```diff
@@ -39,7 +39,7 @@
     @Nonnull
     public static final PipelineOperation KEY_TO_RECORD = new PipelineOperation("KEY_TO_RECORD");
     @Nonnull
-    public static final PipelineOperation RECORD_ASYNC_FILTER = new PipelineOperation("RECORD_ASYNC_FILTER");
+    public static final PipelineOperation ASYNC_FILTER = new PipelineOperation("ASYNC_FILTER");
```
[the remark this answers is not in the document]
Comment (scgray) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/PipelineOperation.java]: Hmmm...yes, @alecgrieser has a good point.   For example, there are examples of places in which one would have indexes as a covering mechanism due to the overhead of reading the records themselves--conceivably you have could have records approaching 10MB in size, in which case such indexes would become even more of a requirements.   I think maybe a separate pipelining option would make sense.

[the remark this answers is not in the document]
Comment (nblintao) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/PipelineOperation.java]: Updated.
