### PR TITLE
Resolve #2636: AgilityContext: add applyInRecoveryPath test

### LINKED ISSUE #2636: AgilityContext: add applyInRecoveryPath test
A test is needed to ensure that applyInRecoveryPath works where apply fails.

### PR DESCRIPTION
**Pull request by jjezra**
Add a test

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 1]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+            byte[] key = subspace.pack(Tuple.from(2023, 3));
+            byte[] val = Tuple.from(800, "Green eggs and ham", 0).pack();
+            agilityContext.set(key, val);
+            agilityContext.abortAndClose();
+            IntStream range = IntStream.rangeClosed(1, 10);
+            range.parallel().forEach(i -> {
+                if (i == 7) {
+                    agilityContext.applyInRecoveryPath(aContext -> {
+                        Assertions.assertNotNull(aContext);
+                        refInt.addAndGet(i);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:436]: It seems like this should write something to the database, and afterwards we should assert that it was written with the correct value.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 2]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+        AtomicInteger refInt = new AtomicInteger(0);
+        try (FDBRecordContext context = openContext()) {
+            final AgilityContext agilityContext = getAgilityContext(context, true);
+            final Subspace subspace = path.toSubspace(context);
+            byte[] key = subspace.pack(Tuple.from(2023, 3));
+            byte[] val = Tuple.from(800, "Green eggs and ham", 0).pack();
+            agilityContext.set(key, val);
+            agilityContext.abortAndClose();
+            IntStream range = IntStream.rangeClosed(1, 10);
+            range.parallel().forEach(i -> {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:432]: Is the goal of the parallelism here to make sure that `applyInRecoveryPath` doesn't result in allowing other data to be committed?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 3]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
 
+    @Test
+    void testAgilityContextRecoveryPath() {
+        AtomicInteger refInt = new AtomicInteger(0);
+        try (FDBRecordContext context = openContext()) {
+            final AgilityContext agilityContext = getAgilityContext(context, true);
+            final Subspace subspace = path.toSubspace(context);
+            byte[] key = subspace.pack(Tuple.from(2023, 3));
+            byte[] val = Tuple.from(800, "Green eggs and ham", 0).pack();
+            agilityContext.set(key, val);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:429]: We should assert at the end of the test that this was not actually written.

It looks as though there isn't much other testing of the abort/close functionality, so perhaps it would be better to add other tests, rather than adding more assertions to this test.
Additional tests could make it clearer what the expectations are.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 4]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+            IntStream range = IntStream.rangeClosed(1, 10);
+            range.parallel().forEach(i -> {
+                if (i == 7) {
+                    agilityContext.applyInRecoveryPath(aContext -> {
+                        Assertions.assertNotNull(aContext);
+                        refInt.addAndGet(i);
+                        return CompletableFuture.completedFuture(null);
+                    }).join();
+                } else {
+                    try {
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:440]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 5]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+                        agilityContext.apply(aContext -> {
+                            refInt.set(i);
+                            return CompletableFuture.completedFuture(null);
+                        }).join();
+                    } catch (RecordCoreException ex) {
+                        assertTrue(ex.getMessage().contains("Agile context is already closed"));
+                    }
+                }
+            });
+            assertEquals(7, refInt.get());
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:450]: To verify that any thread that calls regular `apply` fails before executing the inner command.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 6]
```diff
@@ -414,6 +418,39 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+            range.parallel().forEach(i -> {
+                if (i == 7) {
+                    agilityContext.applyInRecoveryPath(aContext -> {
+                        Assertions.assertNotNull(aContext);
+                        refInt.addAndGet(i);
+                        return CompletableFuture.completedFuture(null);
+                    }).join();
+                } else {
+                    try {
+                        agilityContext.apply(aContext -> {
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:441]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:436]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java (hunk 2 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:432]: Yes.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 7]
```diff
@@ -419,6 +421,80 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+                    Assertions.assertThrows(RecordCoreStorageException.class,
+                            () -> agilityContext.apply(aContext -> {
+                                context.ensureActive().set(keyFails, packedValue);
+                                return CompletableFuture.completedFuture(null);
+                            }).join());
+                    Assertions.assertThrows(RecordCoreStorageException.class,
+                            () -> agilityContext.set(keyFails, packedValue));
+                }
+            });
+            context.commit();
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:490]: It seems strange to commit the caller context, is that what you want?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java [hunk 8]
```diff
@@ -419,6 +421,80 @@ void testAgilityContextAtomicAttribute(boolean useAgile) {
...
+        byte[] packedValue = value.pack();
+        try (FDBRecordContext context = openContext()) {
+            final AgilityContext agilityContext = getAgilityContext(context, true);
+            final Subspace subspace = path.toSubspace(context);
+            keyAborted = subspace.pack(Tuple.from(2023, 3));
+            agilityContext.set(keyAborted, packedValue);
+            agilityContext.abortAndClose();
+            IntStream range = IntStream.rangeClosed(1, 10);
+            keySucceeds = this.path.toSubspace(context).pack(Tuple.from(prefix, "yes").pack());
+            keyFails = this.path.toSubspace(context).pack(Tuple.from(prefix, "no").pack());
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:472]: `path.toSubspace` can interact with the context. Specifically it may need to update the directory layer to do string interning.

It would be better to do this conversion in a transaction before to ensure that anything in the directory layer is committed beforehand.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java (hunk 7 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:490]: Yes. I wanted to emulate a user that eventually commits the context he opened. As a read-only, it should be a no-op. Is it?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java (hunk 8 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/AgilityContextTest.java:472]: ✅

**Review by ScottDugas — APPROVED** [review]

**Comment by jjezra** [comment]
Rebased + resolved conflicts.

**Review by ScottDugas — APPROVED** [review]

**Review by ScottDugas — APPROVED** [review]
