### PR TITLE
Resolves #549: CursorLimitManager provides no way to tell from the exception which of the limits was hit.

### LINKED ISSUE #549: CursorLimitManager provides no way to tell from the exception which of the limits was hit.
In CursorLimitManager when we hit any of the limits we get “"limit on number of key-values scanned per transaction reached”, however there is no way to tell from the exception which of the limits was hit.

### PR DESCRIPTION
**Pull request by dsimmen**

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java [hunk 1]
```diff
@@ -136,7 +136,7 @@ public boolean tryRecordScan() {
         if (!halted) {
             usedInitialPass = true;
         } else if (failOnScanLimitReached) {
-            throw new ScanLimitReachedException("limit on number of key-values scanned per transaction reached");
+            throw new ScanLimitReachedException("Reached cursor limit : " + (getStoppedReason().isPresent() ? getStoppedReason().get().toString() : "Unknown reason."));
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java]: With very rare exceptions, all `RecordCoreExceptions` are expected to have static title strings.  Any information that is specific to the action being performed should be included as logging details.  So you want to do something like:

    throw new ScanLimitReachedException("limit on number of key-values scanned per transaction reached")
        .addLogInfo("no_next_reason", getStoppedReason().orElse("Unknown"));
    
We do this because it allows for easier log analysis.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/CursorLimitManagerTest.java [hunk 2]
```diff
@@ -56,26 +61,42 @@ public void timeOut() {
...
             assertFalse(manager.isStopped());
             assertFalse(manager.getStoppedReason().isPresent());
         }
 
-        assertFalse(manager.tryRecordScan());
-        assertTrue(manager.isStopped());
-        assertEquals(RecordCursor.NoNextReason.SCAN_LIMIT_REACHED, manager.getStoppedReason().get());
+        if (failOnLimitReached) {
+            RecordCoreException ex = assertThrows(ScanLimitReachedException.class, manager::tryRecordScan);
+            assertThat(ex.getMessage(), containsString("SCAN_LIMIT_REACHED"));
```
Comment (scgray) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/cursors/CursorLimitManagerTest.java]: If you update the exception thrown to use logging properties to convey the reason the scan was stopped, you can use `TestHelpers.assertThrows()` to both assert the exception that is thrown as well as the log keys and values you expect.

**Comment by dsimmen** [comment]
Test this please

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java [hunk 3]
```diff
@@ -136,7 +139,8 @@ public boolean tryRecordScan() {
         if (!halted) {
             usedInitialPass = true;
         } else if (failOnScanLimitReached) {
-            throw new ScanLimitReachedException("limit on number of key-values scanned per transaction reached");
+            throw new ScanLimitReachedException("limit on number of key-values scanned per transaction reached")
+                    .addLogInfo("no_next_reason", getStoppedReason().map(reason -> reason.toString()).orElse("Unknown."));
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/CursorLimitManager.java]: As a note, there should be no reason for the `.map()`.  The logging info allows for you to log any kind of object and it will automatically have `.toString()` called on it when logged, so:

    getStoppedRead().orElse("Unknown")

would be fine.
