### PR TITLE
RESOLVES #2701: Test FDBDirectory consistency while cross-transaction merges are ongoing

### LINKED ISSUE #2701: Test FDBDirectory consistency while cross-transaction merges are ongoing
1. Lock a directory, and commit, then try to update a record, or save a record, or do a search, and assert that nothing is corrupted (or that the user request fails)
2. A test of what lucene does when a merge loses its lock
3. A chaos test of two threads, one constantly trying to merge, and one trying to update a record, or save a new record or do a search. At the end the index should be validated for consistency. It is expected (for now) that user operations will fail.
4. A test where there are multiple threads both trying to do merges. At the end the index should be validated for consistency.

### PR DESCRIPTION
**Pull request by wshaib-apple**
…ransaction merges are ongoing

- added 4 tests to `LuceneIndexTest`

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 1]
```diff
@@ -403,6 +434,314 @@ void flakyMerge(boolean isGrouped,
...
+        try (FDBRecordContext context = openContext(contextProps)) {
+            Pair<FDBRecordStore, QueryPlanner> storeQueryPlannerPair = schemaSetup.apply(context);
+            LuceneIndexMaintainer luceneIndexMaintainer = (LuceneIndexMaintainer)storeQueryPlannerPair.getLeft().getIndexMaintainer(index);
+            FDBDirectory fdbDirectory = luceneIndexMaintainer.getDirectory(Tuple.from(1), 0);
+            Lock testLock = fdbDirectory.obtainLock("write.lock");
+            testLock.ensureValid();
+            commit(context);
+        }
+
+        // create another record
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:482]: If the code above to lock the directory is working correctly, this should fail.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 2]
```diff
@@ -403,6 +434,314 @@ void flakyMerge(boolean isGrouped,
         }
     }
 
+    // Lock a directory, and commit, then try to update a record, or save a record, or do a search, and assert that nothing
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:437]: You are only doing a record save, and not doing the other operations.
It would be good to have a search test, as that, I think, should succeed, but saving/updating should fail.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 3]
```diff
@@ -403,6 +434,314 @@ void flakyMerge(boolean isGrouped,
...
+            }
+        });
+
+        Thread merger = new Thread(() -> {
+            // wait till first record is committed before attempting to merge
+            while (!firstRecordCommitted.get()) {
+                try {
+                    Thread.sleep(100);
+                } catch (InterruptedException interruptedException) {
+                }
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:566]: I think this should mark the thread as interrupted, and return.
```suggestion
                } catch (InterruptedException interruptedException) {
                    Thread.currentThread().interrupt();
                    return;
                }
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 4]
```diff
@@ -403,6 +434,314 @@ void flakyMerge(boolean isGrouped,
...
+
+        // validate index
+        new LuceneIndexTestValidator(() -> openContext(contextProps), context -> {
+            Pair<FDBRecordStore, QueryPlanner> storeQueryPlannerPair = schemaSetup.apply(context);
+            return storeQueryPlannerPair.getLeft();
+        }).validate(index, insertedDocs, Integer.MAX_VALUE, "text:about", false);
+    }
+
+
+    // A chaos test of two threads, one constantly trying to merge, and one trying to update a record, or save a new record or do a search.
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:507]: Here also, we're not doing a search, but testing that we can would be good. I think searches should succeed when there is a merge ongoing, but updates/saves should not.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 5]
```diff
@@ -403,6 +434,314 @@ void flakyMerge(boolean isGrouped,
...
+                        .build();
+                Tuple primaryKey = recordStore.saveRecord(cd).getPrimaryKey();
+                insertedDocs.computeIfAbsent(Tuple.from(1), k -> new HashMap<>()).put(primaryKey, Tuple.from(timestamp));
+                commit(context);
+            }
+        }
+
+        List<Thread> mergingThreads = new ArrayList<>();
+        for (int i = 0; i < threadCount; i++) {
+            mergingThreads.add(new Thread(() -> explicitMergeIndex(index, contextProps, schemaSetup)));
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:631]: Since starting a thread takes time, it would probably be good to use a `CountDown` to increase the chance that the merges start at about the same time.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 2 above)
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:437]: I would be in support of just updating the comment in this PR, and then following up with additional tests

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 4 above)
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:507]: I would be in support of just updating the comment in this PR, and then following up with additional tests

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 6]
```diff
@@ -403,6 +426,308 @@ void flakyMerge(boolean isGrouped,
...
+        // try a couple of times
+        for (int l = 0; l < 2; l++) {
+            try (FDBRecordContext context = openContext(contextProps)) {
+                FDBRecordStore recordStore = Objects.requireNonNull(schemaSetup.apply(context).getLeft());
+
+                // directory key for group 1/partition 0
+                Tuple directoryKey = Tuple.from(1, LucenePartitioner.PARTITION_DATA_SUBSPACE, 0);
+                IndexMaintainerState state = new IndexMaintainerState(recordStore, index, IndexMaintenanceFilter.NORMAL);
+
+                // custom test directory that returns a lucene lock that's never valid (Lock.ensureValid() throws IOException)
```
[the remark this answers is not in the document]
Comment (wshaib-apple) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:664]: Would it be enough to have the overridden `ensureValid()` return `false` say 50% of the time?

[the remark this answers is not in the document]
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:664]: Having it probabilistically fail would probably be sufficient. I'm not sure if 50% is the right frequency.

**Review by ScottDugas — APPROVED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 7]
```diff
@@ -698,7 +712,12 @@ public void close() throws IOException {
 
                 @Override
                 public void ensureValid() throws IOException {
-                    throw new IOException("invalid lock");
+                    // 0 <= 0-99 < 100
+                    if (ThreadLocalRandom.current().nextInt(100) < percentFailure) {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:716]: We could make the test more deterministic if the test took a seed as a parameter, and created a `Random` for this.

**Review by ScottDugas — APPROVED** [review]
