### PR TITLE
Fixes #2024: Listing missing ranges in a RangeSet has overly large conflict ranges

### LINKED ISSUE #2024: Listing missing ranges in a RangeSet has overly large conflict ranges
When inserting into a range set, we take care to only insert read and write conflict ranges over the range we're inserting. See:

https://github.com/FoundationDB/fdb-record-layer/blob/77cc0c5328bea2722482a3e6562869b7b1b56d4e/fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java#L231-L243

Note that the two `AsyncIterator`s are created at snapshot, and there's a read conflict range added over just the range we're inserting. Because of the data format of the `RangeSet`, it does have to read outside the range, but it will discard any information it gets from keys that aren't in the range actually being inserted.

However, the logic for reading missing ranges from the range set doesn't work like that:

https://github.com/FoundationDB/fdb-record-layer/blob/77cc0c5328bea2722482a3e6562869b7b1b56d4e/fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java#L514-L517

Here, read conflict ranges can be added for values outside the range, which means that (for example) a transaction that inserts a range can cause a transaction that reads a disjoint range to fail with a conflict.

### PR DESCRIPTION
**Pull request by alecgrieser**
This adjusts the way that the `RangeSet` adds conflict ranges when listing missing ranges so that it only adds a read conflict range if the range is relevant to the final answer. This means that, for example, disjoint ranges can be modified in concurrent transacitons and all commit. There was already logic that adjusted these ranges in `insertRange`, so only the list method needed to be adjusted.

This fixes #2024.

### CODE REVIEW

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java [hunk 1]
```diff
@@ -233,66 +240,182 @@ public void insert() {
...
+            Range r1 = new Range(new byte[]{0x00}, new byte[]{0x01});
+            Range r2 = new Range(new byte[]{0x02}, new byte[]{0x03});
+            Range r3 = new Range(new byte[]{0x04}, new byte[]{0x05});
+
+            // Insert r1
+            Transaction tr1 = multi.get(0);
+            assertTrue(rs.insertRange(tr1, r1, true).join());
+
+            // In separate transactions, read the ranges r2 and r3. One of them
+            // is before r1 and the other other after
```
Comment (jjezra) [inline fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:269]: Aren't both after r1?

**Review by jjezra — DISMISSED** [review]

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java (hunk 1 above)
Comment (ScottDugas) [reply fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:269]: Yeah, it seems like this is missing coverage of querying before the inserted range.

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java [hunk 2]
```diff
@@ -233,66 +240,182 @@ public void insert() {
...
+            Transaction tr2 = multi.get(1);
+            assertEquals(List.of(r), rs.missingRanges(tr2, r).asList().join());
+
+            // The second transaction should fail to commit
+            multi.commit(Set.of(1));
+        }
+    }
+
+    @Test
+    void insertNonOverlappingRanges() {
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:347]: It seems like it would be good to also have a test that does `[i, i+1)`, which would also be non-overlapping, but abutting. Or would that result in them merging, and thus conflicting?

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java [hunk 3]
```diff
@@ -233,66 +240,182 @@ public void insert() {
...
+
+    @Test
+    void insertOverlappingRanges() {
+        try (MultipleTransactions multi = MultipleTransactions.create(db, 10)) {
+            for (int i = 0; i < multi.size(); i++) {
+                Transaction tr = multi.get(i);
+                assertTrue(rs.insertRange(tr, new Range(new byte[]{(byte)i}, new byte[]{(byte)(i + 1), 0x00}), false).join());
+            }
+
+            // Even transactions should be able to commit
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:367]: even transactions can commit because it commits in order, so in chronological order we have:
1. tr0 commits
2. tr1 conflicts with tr0
3. tr2 does not overlap with tr0's range, so commits
4. tr3 conflicts with tr2
5. tr4 does not overlap with the two that committed, so succeeds
...

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java [hunk 4]
```diff
@@ -430,4 +541,78 @@ public void missingRanges() {
         }
     }
 
+    private static class MultipleTransactions implements AutoCloseable, Iterable<Transaction> {
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:544]: It doesn't have to be done in this PR, but I feel like this class would be pretty generally useful in other tests, so perhaps worth pulling out.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:347]: Added a test with `[i, i+1)`. This does succeed, because each one inserts a different key representing a different range. This means that it isn't coalesced, but given the goal here, it's probably better to have the lack of coalescence rather than to have transactions that fail.

In this test (and the others), I've added some additional tests to make sure that the set makes sense, i.e., there are gaps in the expected places

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java (hunk 3 above)
Comment (alecgrieser) [reply fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:367]: Yeah, that's right. Expanded this comment

File: fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java (hunk 4 above)
Comment (alecgrieser) [reply fdb-extensions/src/test/java/com/apple/foundationdb/async/RangeSetTest.java:544]: Yeah, that makes sense. I've extracted the class from outside of the `RangeSetTest` into its own top-level class. I haven't migrated any other tests to use it, but now it's available.

**Comment by alecgrieser** [comment]
Rebase was to protect against merge skew, but otherwise didn't make any changes. Responded to comments in 30d2e75 and 153553c
