### PR TITLE
Resolves #441: Audit code for incorrect uses of CompletableFuture::isDone

### LINKED ISSUE #441: Audit code for incorrect uses of CompletableFuture::isDone
Issue #437 was essentially caused by improper usage of `CompletableFuture::isDone` causing errors to be swallowed. It's possible that we have other instances of the same or similar bug from other uses. We should go through the code and see if any of them need to be replaced with `MoreAsyncUtil.isCompletedNormally` to avoid swallowing errors.

### PR DESCRIPTION
**Pull request by alecgrieser**
Nothing major was found. There were a few instances where we were not using the cached `READY_TRUE` and `READY_FALSE` futures, so I fixed those. A few places, the error was generated, thrown, and then caught, so I instead made it check for normal completion so that propagating the error was a little cheaper. I did not touch the `MapPipelinedCursor` or `FlatMapPipelined` cursor (except for a few comments), though I tried to add tests to exercise some of the code paths that might encounter exceptions. Those were all either directly or later calling `.join()` on the future they were checking, so they should all report errors, though there may be ways to fix those up so that they do not need to throw. I started down that path, then I decided that it was probably better to avoid accidentally introducing a new bug under the axiom of not trying to fix what is not Baroque.

I purposefully omitted any release notes as I didn't find any real bugs.

### CODE REVIEW

**Comment by alecgrieser** [comment]
@nschiefer If you feel like someone else should also review this, I guess add them on.

File: fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java [hunk 1]
```diff
@@ -270,7 +270,7 @@ private static void checkRange(@Nonnull byte[] begin, @Nonnull byte[] end) {
                     // If we are allowing non-empty ranges, then we just need to fill in the gaps.
                     return AsyncUtil.whileTrue(() -> {
                         byte[] lastSeenBytes = lastSeen.get();
-                        if (afterIterator.onHasNext().isDone() && afterIterator.hasNext()) {
+                        if (MoreAsyncUtil.isCompletedNormally(afterIterator.onHasNext()) && afterIterator.hasNext()) {
```
Comment (nschiefer) [inline fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java]: Hmm, I suppose we used to join on the future immediately (via `afterIterator.hasNext()`), so this future would complete exceptionally. Now we'll do the same by returning `afterIterator.onHasNext()`?

Comment (alecgrieser) [reply fdb-extensions/src/main/java/com/apple/foundationdb/async/RangeSet.java]: Yeah, if `afterIterator.onHasNext()` completes exceptionally, then this used to raise an error (with the `hasNext()` call). Now, it propagates the exceptional future to `whileTrue`, which in turn boils the exception back up.

So, in theory, this isn't strictly necessary, but I think *in general* propagating the exceptional future rather than re-raising is better etiquette. I could be wrong though.

**Comment by alecgrieser** [comment]
Rebase resolves merge conflicts.
