### PR TITLE
Limit parallel open of segment readers to settable number of threads.

### LINKED ISSUE #2309: Lucene segment parallel opener runs out of threads
`StandardDirectoryReaderOptimization` is happy to use up all FJP threads and extra spares when there are enough segments.

```
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:1575)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3115)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabase.asyncToSync(FDBDatabase.java:1093)
	at com.apple.foundationdb.record.provider.foundationdb.FDBRecordContext.asyncToSync(FDBRecordContext.java:1139)
	at com.apple.foundationdb.record.lucene.directory.FDBDirectory.readSchema(FDBDirectory.java:525)
	at com.apple.foundationdb.record.lucene.codec.LuceneOptimizedWrappedDirectory.lambda$openInput$2(LuceneOptimizedWrappedDirectory.java:157)
	at com.apple.foundationdb.record.lucene.codec.LuceneOptimizedWrappedIndexInput.lambda$new$0(LuceneOptimizedWrappedIndexInput.java:38)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at com.apple.foundationdb.record.lucene.codec.LuceneOptimizedWrappedIndexInput.readByte(LuceneOptimizedWrappedIndexInput.java:69)
	at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
	at com.apple.foundationdb.record.lucene.codec.PrefetchableBufferedChecksumIndexInput.readByte(PrefetchableBufferedChecksumIndexInput.java:101)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:102)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:194)
	at com.apple.foundationdb.record.lucene.codec.LuceneOptimized60FieldInfosFormat.read(LuceneOptimized60FieldInfosFormat.java:143)
	at com.apple.foundationdb.record.lucene.codec.LuceneOptimizedFieldInfosFormat.read(LuceneOptimizedFieldInfosFormat.java:46)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:109)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)
	at org.apache.lucene.index.StandardDirectoryReaderOptimization$1.lambda$doBody$0(StandardDirectoryReaderOptimization.java:66)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
```

### PR DESCRIPTION
**Pull request by MMcM**
Additionally make it robust to running out of executor threads (which will be much less likely with the limit).

Fixes #2309.

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java [hunk 1]
```diff
@@ -88,4 +91,60 @@ protected DirectoryReader doBody(String segmentFileName) throws IOException {
...
+            this.segmentReaders = segmentReaders;
+            this.readerIndex = readerIndex;
+            this.segmentCommitInfo = segmentCommitInfo;
+            this.createdVersionMajor = createdVersionMajor;
+            this.ioContext = ioContext;
+        }
+
+        public void start(final Executor executor) {
+            try {
+                future = CompletableFuture.supplyAsync(() -> {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java:117]: I think this could just use `CompletableFuture.runAsync()`, since it doesn't have a result.

File: fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java [hunk 2]
```diff
@@ -88,4 +91,60 @@ protected DirectoryReader doBody(String segmentFileName) throws IOException {
...
+            }
+            if (ioException != null) {
+                throw ioException;
+            }
+            if (segmentReaders[readerIndex] == null) {
+                open();
+            }
+        }
+
+        private void open() throws IOException {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java:146]: Would it be easy / beneficial to add a test that runs with the `LUCENE_OPEN_PARALLELISM` and/or `executor`'s parallelism set to very low values (like 1 or 2)?
The issues are most likely to happen when you have hundreds or thousands of segments, but perhaps we can simulate by lowering the parallelism a bunch.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java (hunk 1 above)
Comment (MMcM) [reply fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java]: Sure. Done.

File: fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java (hunk 2 above)
Comment (MMcM) [reply fdb-record-layer-lucene/src/main/java/org/apache/lucene/index/StandardDirectoryReaderOptimization.java:145]: Yeah. I added a test that does it with parallelism `2` after (effectively) disabling auto-merge. Not much of a stress test, but just in case all other tests happened to be below `16`.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java [hunk 3]
```diff
@@ -2419,6 +2419,29 @@ void luceneCursorTestAllMatchesSkipped() throws Exception {
...
+            final RecordLayerPropertyStorage.Builder insertProps = RecordLayerPropertyStorage.newBuilder()
+                    .addProp(LuceneRecordContextProperties.LUCENE_MERGE_MAX_SIZE, 0.001); // Don't merge
+            try (FDBRecordContext context = openContext(insertProps)) {
+                rebuildIndexMetaData(context, SIMPLE_DOC, SIMPLE_TEXT_SUFFIXES);
+                recordStore.saveRecord(createSimpleDocument(1000 + i, ENGINEER_JOKE, 2));
+                context.commit();
+            }
+        }
+        final RecordLayerPropertyStorage.Builder scanProps = RecordLayerPropertyStorage.newBuilder()
+                .addProp(LuceneRecordContextProperties.LUCENE_OPEN_PARALLELISM, 2); // Don't merge
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java:2434]:
```suggestion
                .addProp(LuceneRecordContextProperties.LUCENE_OPEN_PARALLELISM, 2); // Decrease parallelism when opening segments
```

**Review by ScottDugas — CHANGES_REQUESTED** [review]
