### PR TITLE
IndexingMerger: lessen work and retry by default

### LINKED ISSUE #3731: IndexingMerger: lessen work and retry by default
Catching an exception, the `IndexingMerger` attempts to detect if it should lessen work and retry. Currently it is an include list of known "retyable" errors.  If the error is not detected correctly, or not predicted, it will not retry. 
Being a background process, however, it is better and safer to retry by default.

### PR DESCRIPTION
**Pull request by jjezra**
Catching an exception, the IndexingMerger attempts to detect if it should lessen work and retry. Currently it is an include list of known "retyable" errors. If the error is not detected correctly, or not predicted, it will not retry.
 Being a background process, however, it is better and safer to retry after timeouts and after any FDB exception.

  Resolves #3731

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java [hunk 1]
```diff
@@ -144,6 +145,22 @@ boolean mayRetryAfterHandlingException(@Nullable FDBException fdbException,
             return true;
         }
 
+        private static boolean shouldLessenWork(@Nullable FDBException ex) {
+            // These error codes represent a list of errors that can occur if there is too much work to be done
+            // in a single transaction.
+            if (ex == null) {
+                return false;
+            }
+            final Set<Integer> lessenWorkCodes = new HashSet<>(Arrays.asList(
```
Comment (ohadzeliger) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java]: This set can be declared as a static instance - no need to instantiate every time

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 2]
```diff
@@ -150,7 +150,7 @@ private CompletableFuture<Boolean> handleFailure(final IndexDeferredMaintenanceC
         mergeControl.mergeHadFailed(); // report to adjust stats
         final FDBException ex = IndexingBase.findException(e, FDBException.class);
         final IndexDeferredMaintenanceControl.LastStep lastStep = mergeControl.getLastStep();
-        if (!IndexingBase.shouldLessenWork(ex)) {
+        if (shouldAbort(ex)) {
```
Comment (ohadzeliger) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java]: Is there a test that we can add to ensure e.g. that the retries stop after a few attempts?

**Review by ohadzeliger — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 2 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java]: `luceneOnlineIndexingTestTerrible2Merger`

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 3]
```diff
@@ -175,6 +174,24 @@ private CompletableFuture<Boolean> handleFailure(final IndexDeferredMaintenanceC
...
     }
 
+    private boolean shouldAbort(@Nullable Throwable e) {
+        if (e == null) {
+            return true;
+        }
+        // Expecting AsyncToSyncTimeoutException or an instance of TimeoutException. However, cannot
+        // refer to AsyncToSyncTimeoutException without creating a lucene dependency
+        // TODO: remove this kludge
+        if (e.getClass().getCanonicalName().contains("Timeout") ) {
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java]: From the PR description: 
> Being a background process, however, it is better and safer to retry by default.

Why not just have this return false if there is any exception, except `InterruptedException`.
Here you abort for any exception that doesn't have `Timeout` in its name, or an `FDBException` as its cause. 

Either way, it seems like having a test with a mock IndexMaintainer that has various failure scenarios would be valuable.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java]: Just wonder - wouldn't the JVM do the right thing here? It seems like an obvious optimization and I know that other languages are performing this optimization (and much more).

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java [hunk 4]
```diff
@@ -192,10 +192,11 @@ void repartitionGroupedTestWithExceptionMapping(boolean useLegacyAsyncToSync, bo
         }
 
         // run partitioning without failure - make sure the index is still in good shape
+        timer.reset();
         explicitMergeIndex(index, contextProps, schemaSetup, false, 0);
         try (FDBRecordContext context = openContext(contextProps)) {
             schemaSetup.accept(context);
-            assertEquals(2, getCounter(context, LuceneEvents.Counts.LUCENE_REPARTITION_CALLS).getCount());
+            assertEquals(1, getCounter(context, LuceneEvents.Counts.LUCENE_REPARTITION_CALLS).getCount());
```
Comment (jjezra) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java:199]: @ohadzeliger, please verify this code (time reset, then getting only one repartition call. With this PR, the are more retries than the old test anticipated)

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 5]
```diff
@@ -461,14 +461,18 @@ void flakyMerge(boolean isGrouped,
                     return oldAsyncToSyncTimeout == null ? Duration.ofDays(1L) : oldAsyncToSyncTimeout.apply(wait);
                 }
             };
-            for (int i = 0; i < 100; i++) {
+            for (int i = 0; i < 20; i++) {
```
Comment (jjezra) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:485]: @ScottDugas , please verify - 
1. Using now a lower level index maintainer's merge to avoid retries on timeout. 
2. With "100" repetitions the `flakyMergeQuick` test was reaching the 5 minutes test limit. Had to take it down to 20. Is that acceptable?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java]: From what I saw, the Java compiler and JIT compiler will do little in terms of optimization of `final` and it is more intended to convey a design intent and to protect from unintentional change. Setting this to `static final` would probably be a good way to indicate that this is not changing and prevent extra work that is unneeded.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 6]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+            // Assert that the timeout exception is in the cause chain
+            var timeoutCause =
+                    customTimeout ?
+                    findCause(thrownException, CustomOperationTimeoutException.class) :
+                    findCause(thrownException, TimeoutException.class);
+            Assertions.assertNotNull(timeoutCause);
+            Assertions.assertEquals(exceptionMessage, timeoutCause.getMessage());
+        }
+        // Assert multiple retries
+        assertTrue(1 < attemptCount.get());
```
Comment (ohadzeliger) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:278]: Do we know exactly how many retries should be? Isn't it the same as the number above (5)?

Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:278]: Do you mean the "max attempts" above? 
If so, the answer is no. The index merge does not retry with the same configuration but will give-up if it cannot lessen the work anymore (or some other conditions). The `setMaxAttempts(5)` above relates to the runner.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingThrottle.java]: √

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 7]
```diff
@@ -175,6 +176,13 @@ private CompletableFuture<Boolean> handleFailure(final IndexDeferredMaintenanceC
         return AsyncUtil.READY_TRUE; // and retry
     }
 
+    private boolean shouldAbort(@Nullable Throwable e) {
+        return e == null ||
+                (IndexingBase.findException(e, RecordCoreTimeoutException.class) == null &&
+                         IndexingBase.findException(e, TimeoutException.class) == null &&
+                         IndexingBase.findException(e, FDBException.class) == null);
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java]: Looking at the [error codes](https://apple.github.io/foundationdb/api-error-codes.html)
It seems like probably the following should not be retried:
- `batch_transaction_throttled` -- this indicates the cluster is overloaded and trying not to do batch-level work. Retrying increases the load
- `tag_throttled` -- Similar, but for a tag (I'm not sure if record layer supports tags, but if we don't know, we may in the future)

There's definitely a long list of errors in there that would be pointless to retry, which is why the original code had a list of error codes where it should lessen work, rather than a list where it shouldn't.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 8]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+            adjustMergeControl(state);
+
+            attemptCount.incrementAndGet();
+
+            // Throw a TimeoutException (not FDB timeout)
+            final CompletableFuture<Void> future = new CompletableFuture<>();
+            future.completeExceptionally(
+                    customTimeout ?
+                    new CustomOperationTimeoutException(exceptionMessage) :
+                    new java.util.concurrent.TimeoutException(exceptionMessage));
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: This should not be fully qualified, it should use the import
```suggestion
                    new TimeoutException(exceptionMessage));
```

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 9]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+            return future;
+        });
+
+        final FDBRecordStore.Builder storeBuilder = createStore(indexType);
+        try (OnlineIndexer indexer = OnlineIndexer.newBuilder()
+                .setRecordStoreBuilder(storeBuilder)
+                .setTargetIndexesByName(List.of(INDEX_NAME))
+                .setMaxAttempts(5)
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: Why are you setting `maxAttempts` to 5 here?

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 10]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+                    findCause(thrownException, CustomOperationTimeoutException.class) :
+                    findCause(thrownException, TimeoutException.class);
+            Assertions.assertNotNull(timeoutCause);
+            Assertions.assertEquals(exceptionMessage, timeoutCause.getMessage());
+        }
+        // Assert multiple retries
+        assertTrue(1 < attemptCount.get());
+    }
+
+    private static void adjustMergeControl(final IndexMaintainerState state) {
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:281]: Nit: This `findCause` and the `CustomOperationTimeoutException` seem arbitrarily placed as there are methods above and below that reference them. Generally, in the record layer, nested classes go at the end. helper methods are a bit more flexible, either at the end, or at the end of the tests I think would make sense.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 11]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+    }
+
+    @SuppressWarnings("serial")
+    private static class CustomOperationTimeoutException extends RecordCoreTimeoutException {
+        public CustomOperationTimeoutException(String message) {
+            super(message);
+        }
+    }
+
+    private static <T extends Throwable> T findCause(Throwable throwable, Class<T> causeType) {
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: Perhaps this could be useful in `TestHelpers`.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 12]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+        Throwable current = throwable;
+        while (current != null) {
+            if (causeType.isInstance(current)) {
+                return causeType.cast(current);
+            }
+            current = current.getCause();
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: An exception can have a cause that references another exception in the cause chain, which would result in an infinite loop here. See: https://github.com/FoundationDB/fdb-record-layer/blob/86bf52bea76dbebf749a9f38999af8c62ae584b7/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java#L1204

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 13]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+        AtomicInteger attemptCount = new AtomicInteger(0);
+
+        TestFactory.register(indexType, state -> {
+            adjustMergeControl(state);
+
+            attemptCount.incrementAndGet();
+
+            // Wrap FDBException in multiple layers to test deep unwrapping
+            final CompletableFuture<Void> future = new CompletableFuture<>();
+            FDBException fdbEx = new FDBException("Transaction too old", FDBError.TRANSACTION_TOO_OLD.code());
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: This is an error code that was explicitly marked as lessening work codes before, should this test be parameterized to:
1. An errorCode that the runner would retry
2. An ErrorCode that was in shouldLessen
3. An ErrorCode that was not, and shouldn't (e.g. `no_cluster_file_found`)

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 14]
```diff
@@ -119,7 +119,7 @@ private LuceneConcurrency() {
     /**
      * An exception that is thrown when the async to sync operation times out.
      */
-    public static class AsyncToSyncTimeoutException extends RecordCoreException {
+    public static class AsyncToSyncTimeoutException extends RecordCoreTimeoutException {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:122]: Other than backwards compatibility, is there any reason to keep this class around? Should we mark it as `API.Status.DEPRECATED`, and then, in the future have lucene throw `RecordCoreTimeoutException` instead?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 5 above)
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:485]: I think it would be better to disable all retries in the indexer used for merging.
The point of this test is to validate that if Lucene merge fails randomly in the middle it will still be usable, and not corrupted. Having retries in the IndexingMerger means that it could heal, but we want to make sure that requests coming in while the merge is ongoing don't get a corrupted view.

I'd also recommend on any comments necessary to make that clear.
The javadoc on the test is, apparently, too brief.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 15]
```diff
@@ -461,14 +461,18 @@ void flakyMerge(boolean isGrouped,
...
                 fdb.setAsyncToSyncTimeout(asyncToSyncTimeout);
                 waitCounts.set(i);
                 boolean success = false;
                 try {
                     LOGGER.info(KeyValueLogMessage.of("Merge started",
                             "iteration", i));
-                    explicitMergeIndex(dataModel.index, contextProps, dataModel.schemaSetup);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:488]: Why not use `explicitMergeIndex` anymore? A comment in the code would probably be valuable indicating why we're not using the helper method.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java [hunk 16]
```diff
@@ -197,6 +202,185 @@ void testMergeTimeout() {
...
+     */
+    @ParameterizedTest
+    @BooleanSource
+    void testTimeoutExceptionRetries(boolean customTimeout) {
+        final String indexType = "timeoutExceptionIndex";
+        final String exceptionMessage = "my timeout";
+        AtomicInteger attemptCount = new AtomicInteger(0);
+
+        TestFactory.register(indexType, state -> {
+            adjustMergeControl(state);
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:250]: The code does not retry any errors while opening the store. Are you intentionally leaving that as-is?
Are you intending to change that in a followup?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 5 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:485]: Added this clarification to the javadoc. 
Since there is not control on the number of retries (the merger will retry until it cannot reduce the amount of work / transaction time quota anymore), this PR is calling the lower level `mergeIndex` from the index maintainer. 
I wonder if the `100` loop will not get the 5 minutes test timeout because the lower level is quick enough to set the file-lock before getting the asyncToSync timeout...

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 7 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java]: √

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 8 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: √

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 9 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: No particular reason. Removed.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 10 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:281]: √

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 11 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: √

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 12 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: √

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 13 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java]: √

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 14 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:122]: Probably. Should that be done in another PR?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 15 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:488]: Added a comment.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java (hunk 16 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:250]: Do you mean the merger's code or the test?

Comment (ScottDugas) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMergeTest.java:250]: I mean the code. It still only retries if the MergeControl is set, which happens after the store is opened.

**Review by ScottDugas — APPROVED** [review]
