### PR TITLE
FIXES #2784: Fix out of bound exception with repartitioning

### LINKED ISSUE #2784: Fix out of bound exception with repartitioning
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.apple.foundationdb.record.lucene.LucenePartitioner.lambda$moveDocsFromPartition$41(LucenePartitioner.java:1048)
```

### PR DESCRIPTION
**Pull request by wshaib-apple**
- added a check to array size
- fixed sort order in query for oldest/newest docs

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java [hunk 1]
```diff
@@ -1013,6 +1013,14 @@ private CompletableFuture<Integer> moveDocsFromPartition(@Nonnull final LuceneRe
                 newBoundaryPartitionKey = toPartitionKey(records.get(records.size() - 1));
                 records.remove(records.size() - 1);
             }
+
+            if (records.size() == 0) {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java:1017]: Should this be above the check above 
```
if (!repartitioningContext.emptyingPartition && repartitioningContext.newBoundaryRecordPresent) {
```

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java (hunk 1 above)
Comment (wshaib-apple) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java:1017]: `records.size()` should be `> 0` in all cases **unless** `fetchedRecordsFuture` failed to fetch the required records. The check here is made to ensure that `records.remove(records.size() - 1)` a couple of lines above didn't empty the records list.

**Review by ScottDugas — APPROVED** [review]
