### PR TITLE
FIxes #1267: OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersis…

### LINKED ISSUE #1267: OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersistentContinueRebuildWhenTypeStampChange timeout failures
I've seen at least once during a PRB run that the test `OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersistentContinueRebuildWhenTypeStampChange` has failed. The error message isn't particularly helpful, with it essentially saying that there's some kind of timeout. Here's the stack trace:

```
com.apple.foundationdb.record.RecordCoreException
	at com.apple.foundationdb.record.provider.foundationdb.FDBExceptions.wrapException(FDBExceptions.java:200)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabase.lambda$new$0(FDBDatabase.java:167)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabase.asyncToSync(FDBDatabase.java:1037)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseRunnerImpl.asyncToSync(FDBDatabaseRunnerImpl.java:340)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexer.asyncToSync(OnlineIndexer.java:790)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexer.buildIndex(OnlineIndexer.java:714)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexerIndexFromIndexTest.buildSrcIndex(OnlineIndexerIndexFromIndexTest.java:71)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersistentContinueRebuildWhenTypeStampChange(OnlineIndexerIndexFromIndexTest.java:595)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabase.asyncToSync(FDBDatabase.java:1028)
	... 95 more
```

Unclear if this is really the test or if the CI environment can get overwhelmed, though

### PR DESCRIPTION
**Pull request by jjezra**
…tentContinueRebuildWhenTypeStampChange timeout failures

        Reduce the number of records.

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java [hunk 1]
```diff
@@ -66,10 +68,23 @@ private void populateData(final long numRecords) {
...
+                built = true;
+            } catch (Exception ex) {
+                if (-- sanity <= 0) {
+                    throw ex;
+                }
+                Logger logger = LoggerFactory.getLogger(OnlineIndexerIndexFromIndexTest.class);
+                if (logger.isWarnEnabled()) {
+                    logger.warn("Attempt failed" , ex);
+                }
+            }
```
Comment (scgray) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java:87]: I think it is important to look into the underlying cause. Looking at: https://github.com/FoundationDB/fdb-record-layer/blob/b2d961a47ae3c7f160c2d3affa32c5f971ef2dcc/fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java#L83 the timeout for building an index is 5 minutes (!) and looking at the log lines from the test failure referenced in my comments in the issue:

```
2021-08-09 17:12:23,507 [DEBUG] c.a.f.r.p.f.FDBRecordStore - indexes need rebuilding indexesReadable="[MySimpleRecord$num_value_unique, MySimpleRecord$num_value_3_indexed, MySimpleRecord$str_value_indexed]" new_store="true" record_count="0" subspace="\x15("
2021-08-09 17:17:23,857 [WARN] c.a.f.r.p.f.IndexingBase - build index online index_name="src_index" index_version="4" indexer_id="6ed6524d-01d1-44dc-86fe-1f90face04ff" indexing_method="by records" records_scanned="0" result="failure" should_mark_readable="true"
```

there looks to be a 5 minute gap between starting the index and the failure.  Should this really, even conceivably, be taking more than 5 minutes?

**Review by scgray — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java:87]: To the best of my understanding, it shouldn't be even close to 5 minutes (it's only 1328 records). Something is either hanged or deadlocked, and it never happened on my laptop.

**Review by MMcM — APPROVED** [review]

**Review by scgray — APPROVED** [review]
