### PR TITLE
Fix internal errors from version queries: Part 1

### LINKED ISSUE #3734: Index scans with enum fields fail when resumed from a serialized continuation
If you have a schema template like:

```
CREATE TYPE AS ENUM blah ( 'a', 'b', 'c')
CREATE TABLE T (id bigint, blah blah, primary key (id) )
CREATE INDEX T_blah AS SELECT blah FROM T
```

Then execute a query like:

```
SELECT * FROM T WHERE blah = ?b
```

Then that gets planned as an index scan on the `T_blah` index, as you might expect:

```
ISCAN(T_BLAH [EQUALS promote(@c7 AS ENUM<a(0), b(1), c(2)>)])
```

This plan executes and returns the correct results. However, if the plan is serialized into a continuation and then resumed, we encounter a `NullPointerException`:

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:904)
	at com.apple.foundationdb.record.query.plan.cascades.typing.TypeRepository.getProtoTypeName(TypeRepository.java:165)
	at com.apple.foundationdb.record.query.plan.cascades.typing.TypeRepository.getEnumDescriptor(TypeRepository.java:251)
	at com.apple.foundationdb.record.query.plan.cascades.values.PromoteValue.eval(PromoteValue.java:252)
	at com.apple.foundationdb.record.query.expressions.Comparisons$ValueComparison.getComparand(Comparisons.java:1605)
	at com.apple.foundationdb.record.query.plan.ScanComparisons.addComparandToList(ScanComparisons.java:325)
	at com.apple.foundationdb.record.query.plan.ScanComparisons.toTupleRange(ScanComparisons.java:292)
	at com.apple.foundationdb.record.provider.foundationdb.IndexScanComparisons.bind(IndexScanComparisons.java:103)
	at com.apple.foundationdb.record.provider.foundationdb.IndexScanComparisons.bind(IndexScanComparisons.java:53)
	at com.apple.foundationdb.record.query.plan.plans.RecordQueryIndexPlan.executeEntries(RecordQueryIndexPlan.java:325)
	at com.apple.foundationdb.record.query.plan.plans.RecordQueryPlanWithIndex.lambda$executePlan$0(RecordQueryPlanWithIndex.java:88)
	at com.apple.foundationdb.record.query.plan.plans.RecordQueryPlanWithIndex.fetchIndexRecords(RecordQueryPlanWithIndex.java:99)
	at com.apple.foundationdb.record.query.plan.plans.RecordQueryPlanWithIndex.executePlan(RecordQueryPlanWithIndex.java:89)
	at com.apple.foundationdb.record.query.plan.plans.RecordQueryIndexPlan.executePlan(RecordQueryIndexPlan.java:275)
	at com.apple.foundationdb.relational.recordlayer.query.QueryPlan$PhysicalQueryPlan.lambda$executePhysicalPlan$6(QueryPlan.java:403)
	at com.apple.foundationdb.relational.recordlayer.metric.RecordLayerMetricCollector.clock(RecordLayerMetricCollector.java:65)
	at com.apple.foundationdb.relational.recordlayer.query.QueryPlan$PhysicalQueryPlan.executePhysicalPlan(QueryPlan.java:402)
	at com.apple.foundationdb.relational.recordlayer.query.QueryPlan$PhysicalQueryPlan.executeInternal(QueryPlan.java:256)
	at com.apple.foundationdb.relational.recordlayer.query.QueryPlan$PhysicalQueryPlan.executeInternal(QueryPlan.java:106)
	at com.apple.foundationdb.relational.recordlayer.query.Plan.lambda$execute$0(Plan.java:98)
	at com.apple.foundationdb.relational.recordlayer.metric.RecordLayerMetricCollector.clock(RecordLayerMetricCollector.java:65)
	at com.apple.foundationdb.relational.recordlayer.query.Plan.execute(Plan.java:98)
	at com.apple.foundationdb.relational.recordlayer.AbstractEmbeddedStatement.lambda$executeInternal$0(AbstractEmbeddedStatement.java:92)
```

The issue appears to be that we aren't populating the type repository with the enum type when we deserialize the plan, which then means that when we translate the argument into an index scan entry, we get this null pointer exception: https://github.com/FoundationDB/fdb-record-layer/blob/f032a9154e0c2af9fe725938bc8aa11bcf700316/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/TypeRepository.java#L166

A null pointer exception seems like the wrong error to throw here, but also, we should be populating the type repository, or eschewing the type repository entirely. Note that the index is a necessary component to this, as the non-index based variant of this plan (`SCAN(<,>) | TFILTER T | FILTER _.blah EQUALS promote(@c7 AS ENUM<a(0), b(1), c(2)>)` executes without issue.

### PR DESCRIPTION
**Pull request by alecgrieser**
This begins the work necessary to fix internal errors related to `VersionValue` queries. The ultimate goal is to remove `VersionValue`, but for now, what this does is it modifies the way the various operators that sit on top of record fetches and has them copy out the version into a field, called `__ROW_VERSION`. Once that's done, then in a future version (say, 4.9), we'll be able to modify the `PlanGenerator` so that it references that field. Note that we'll need to wait for that rather than do it immediately for backwards compatibility reasons. If we took the final version right away, then any plan that wants the version when sent to an older version that doesn't do this copying will be unable to process that `FieldValue`.

This is in furtherance of #3796.

This also fixes #3734. This is because the type repository updates that are done to make the new copied-to types present in the type repository also put in the enum fields that were previously missing (and causing #3734).

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java [hunk 1]
```diff
@@ -125,7 +125,7 @@ public <S extends KeyExpressionVisitor.State, R> R expand(@Nonnull final KeyExpr
     @Nonnull
     @Override
     public Value toValue(@Nonnull final CorrelationIdentifier baseAlias, @Nonnull final Type baseType) {
-        return new RecordTypeValue(QuantifiedObjectValue.of(baseAlias, new Type.AnyRecord(true)));
+        return new RecordTypeValue(QuantifiedRecordValue.of(baseAlias, new Type.AnyRecord(true)));
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java:128]: Why is this change needed?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java [hunk 2]
```diff
@@ -396,8 +395,7 @@ public RecordQueryPlan toEquivalentPlan(@Nonnull final PartialMatch partialMatch
                                             @Nonnull final Memoizer memoizer,
                                             @Nonnull final List<ComparisonRange> comparisonRanges,
                                             final boolean reverseScanOrder) {
-        final var baseRecordType =
-                Type.Record.fromFieldDescriptorsMap(RecordMetaData.getFieldDescriptorMapFromTypes(queriedRecordTypes));
+        final Type.Record baseRecordType = baseType.narrowRecordMaybe().orElseThrow(() -> new RecordCoreException("type is of wrong implementor"));
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java]: We could possibly just make the `baseType` to be `Type.Rercord`. With the exception of `ExplodeExpression` the type for any `RelationalExpression` always is `Type.Record`. I think that should also be true for the other match candidates.

File: yaml-tests/src/test/resources/enum.yamsql [hunk 3]
```diff
@@ -70,12 +70,12 @@ test_block:
...
     -
       - query: SELECT * From TABLE_A where "mood" = 'CONFUSED'
-      - explain: "SCAN(<,>) | TFILTER TABLE_A | FILTER _.mood EQUALS promote(@c8 AS ENUM<JOYFUL(0), HAPPY(1), RELAXED(2), INDIFFERENT(3), CONFUSED(4), SAD(5), ANXIOUS(6), ANGRY(7)>)"
+      - explain: "SCAN(<,>) | TFILTER TABLE_A | FILTER _.mood EQUALS promote(@c8 AS ENUM<JOYFUL(0), HAPPY(1), RELAXED(2), INDIFFERENT(3), CONFUSED(4), SAD(5), ANXIOUS(6), ANGRY(7)>) | MAP (_.id AS id, _.name AS name, _.mood AS mood)"
       - unorderedResult: [{2, 'bar', 'CONFUSED'},
                           {11, 'plugh', 'CONFUSED'}]
     -
       - query: SELECT * From TABLE_A where "mood" > 'INDIFFERENT'
-      - explain: "SCAN(<,>) | TFILTER TABLE_A | FILTER _.mood GREATER_THAN promote(@c8 AS ENUM<JOYFUL(0), HAPPY(1), RELAXED(2), INDIFFERENT(3), CONFUSED(4), SAD(5), ANXIOUS(6), ANGRY(7)>)"
+      - explain: "SCAN(<,>) | TFILTER TABLE_A | FILTER _.mood GREATER_THAN promote(@c8 AS ENUM<JOYFUL(0), HAPPY(1), RELAXED(2), INDIFFERENT(3), CONFUSED(4), SAD(5), ANXIOUS(6), ANGRY(7)>) | MAP (_.id AS id, _.name AS name, _.mood AS mood)"
```
Comment (normen662) [inline yaml-tests/src/test/resources/enum.yamsql]: Why is this happening?

File: yaml-tests/src/test/resources/field-index-tests-proto.yamsql [hunk 4]
```diff
@@ -58,7 +58,7 @@ test_block:
       - result: [{ID: !l 5, COL1: !l 10, COL31: !l 5, COL32: !null _, COL2: !l 5}]
     -
       - query: select count(*) from (select * from (select * from (select * from "MyTable"  where ID = 5) as x) as y) as z;
-      - explain: "SCAN([EQUALS promote(@c23 AS LONG)]) | MAP (_ AS _0) | AGG (count_star(*) AS _0) | ON EMPTY NULL | MAP (coalesce_long(_._0._0, promote(0l AS LONG)) AS _0)"
+      - explain: "SCAN([EQUALS promote(@c23 AS LONG)]) | MAP ((_.ID AS ID, _.COL1 AS COL1, _.COL31 AS COL31, _.COL32 AS COL32, _.COL2 AS COL2) AS _0) | AGG (count_star(*) AS _0) | ON EMPTY NULL | MAP (coalesce_long(_._0._0, promote(0l AS LONG)) AS _0)"
```
Comment (normen662) [inline yaml-tests/src/test/resources/field-index-tests-proto.yamsql:61]: It seems there is some explicit expansion from `*` to `a, b, c, ...` happening.

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java [hunk 5]
```diff
@@ -397,50 +400,15 @@ public static LogicalOperator generateSimpleSelect(@Nonnull Expressions output,
         });
         final var expandedOutput = output.expanded();
         SelectExpression selectExpression;
-
-        if (canAvoidProjectingIndividualFields(output, logicalOperators)) {
```
Comment (normen662) [inline fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java:401]: Can you give an example of when we can and when we cannot build with `*`

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java [hunk 6]
```diff
@@ -787,13 +787,13 @@ public Expression visitRecordConstructor(@Nonnull RelationalParser.RecordConstru
...
                 final var star = getDelegate().getSemanticAnalyzer().expandStar(Optional.of(id), getDelegate().getLogicalOperators());
-                final var resultValue = star.getUnderlying();
+                final var resultValue = RecordConstructorValue.ofColumns(Expressions.of(star.getExpansion()).underlyingAsColumns());
                 return Expression.ofUnnamed(resultValue);
             }
         }
         if (ctx.STAR() != null) {
             final var star = getDelegate().getSemanticAnalyzer().expandStar(Optional.empty(), getDelegate().getLogicalOperators());
-            final var resultValue = star.getUnderlying();
+            final var resultValue = RecordConstructorValue.ofColumns(Expressions.of(star.getExpansion()).underlyingAsColumns());
```
Comment (normen662) [inline fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java]: Why is this needed? Shouldn't `getUnderlying()` do the right thing?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java [hunk 7]
```diff
@@ -121,9 +121,9 @@ public interface RelationalExpression extends Correlated<RelationalExpression>,
     static RelationalExpression fromRecordQuery(@Nonnull RecordMetaData recordMetaData,
                                                 @Nonnull RecordQuery query) {
         query.validate(recordMetaData);
-        final var allRecordTypes = recordMetaData.getRecordTypes().keySet();
-        final var recordTypesFromQuery = query.getRecordTypes();
-        final var queriedRecordTypes = recordTypesFromQuery.isEmpty() ? allRecordTypes : recordTypesFromQuery;
+        final Set<String> allRecordTypes = recordMetaData.getRecordTypes().keySet();
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java:124]: you don't like `var`s?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java [hunk 8]
```diff
@@ -68,6 +69,9 @@ public void onMatch(@Nonnull final ValueComputationRuleCall<Value, Map<Value, Va
         if (!rootValue.isFunctionallyDependentOn(baseValue)) {
             return;
         }
+        if (rootValue.getResultType().equals(PseudoField.ROW_VERSION.getType())) {
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java:72]: Wouldn't that prevent us from being able to copy that over in the covering-to-partial codepath?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java [hunk 9]
```diff
@@ -64,6 +65,9 @@ public RecordTypeValue(@Nonnull final Value in) {
     @Override
     public <M extends Message> Object eval(@Nullable final FDBRecordStoreBase<M> store, @Nonnull final EvaluationContext context) {
         final var inRecord = in.eval(store, context);
+        if (inRecord instanceof FDBQueriedRecord<?>) {
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java:75]: can't we make `RecordTypeValue` only accept `QuantifiedRecordValue` as `in` and then insist on an `FDBQueriedRecord` here?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java [hunk 10]
```diff
@@ -122,8 +122,9 @@ default Type getResultType() {
     @Nonnull
     default Set<Type> getDynamicTypes() {
         return fold(p -> {
-            if (p instanceof CreatesDynamicTypesValue) {
-                return ImmutableSet.of(p.getResultType());
+            final Type resultType = p.getResultType();
+            if (!resultType.isPrimitive() && !resultType.isUuid()) {
+                return ImmutableSet.of(resultType);
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java:127]: Did this really return a type even if the type is not a record? I guess something using the set that is returned here would then filter it.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java [hunk 11]
```diff
@@ -399,8 +398,6 @@ public RecordQueryPlan toEquivalentPlan(@Nonnull final PartialMatch partialMatch
                                             @Nonnull final Memoizer memoizer,
                                             @Nonnull final List<ComparisonRange> comparisonRanges,
                                             final boolean reverseScanOrder) {
-        final var baseRecordType = Type.Record.fromFieldDescriptorsMap(RecordMetaData.getFieldDescriptorMapFromTypes(recordTypes));
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java:402]: This seems odd that it didn't just derive this from `baseType`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java [hunk 12]
```diff
@@ -51,18 +52,22 @@ public final class IndexExpansionInfo {
     private final Collection<RecordType> indexedRecordTypes;
     @Nonnull
     private final Set<String> indexedRecordTypeNames;
+    @Nonnull
+    private final Type.Record plannerBaseType;
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java]: `baseType` sufficient? I mean is there a difference of `baseType` in all the candidate implementations and this `baseType`?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryLoadByKeysPlan.java [hunk 13]
```diff
@@ -102,7 +102,7 @@ public <M extends Message> RecordCursor<QueryResult> executePlan(@Nonnull final
                 .filter(Objects::nonNull)
                 .map(store::queriedRecord)
                 .skipThenLimit(executeProperties.getSkip(), executeProperties.getReturnedRowLimit())
-                .map(QueryResult::fromQueriedRecord);
+                .map(queriedRecord -> QueryResult.fromQueriedRecord(getResultValue().getResultType(), context, queriedRecord));
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryLoadByKeysPlan.java:105]: `LoadByKeys` is never generated by the cascades planner. This means the `getResultValue()` is very likely to be `Type.UNKNOWN`. Looking at `QueryResult.fromQueriedRecord(.)` that is probably fine but I thought I should point that out.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java [hunk 14]
```diff
@@ -736,39 +729,48 @@ public Map<String, View> getViewMap() {
...
+        if (storeRecordVersions) {
+            plannerType = plannerType.addPseudoFields();
         }
-        return getFieldDescriptorMap(recordTypes.stream());
+        return plannerType;
     }
 
     @Nonnull
-    private static Map<String, Descriptors.FieldDescriptor> getFieldDescriptorMap(@Nonnull final Stream<RecordType> recordTypeStream) {
+    public Type.Record getPlannerType(@Nonnull Collection<String> recordTypeNames) {
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java:742]: Shouldn't we cache this?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java (hunk 1 above)
Comment (normen662) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java:128]: I think this was resolved offline.

File: yaml-tests/src/test/resources/enum.yamsql (hunk 3 above)
Comment (normen662) [reply yaml-tests/src/test/resources/enum.yamsql]: I understand that now.

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java (hunk 5 above)
Comment (normen662) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java:401]: I think after chatting with you this is clear, but I think I would like to not create expanded stars unnecessarily.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java (hunk 1 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/RecordTypeKeyExpression.java:128]: Just for completeness: the problem is that the `RecordTypeValue` used to use look up the record meta-data by looking up the record type key in the meta-data by the name of the message. Now that we're copying things over, the type has a random name, so evaluating the `RecordTypeValue` from the name doesn't work. We need to have access to the `FDBQueriedRecord` so that we can grab the record type key directly.

This sort of has the same problems as the `VersionValue` did, so it may make sense to just make the `RecordTypeKey` (and the record type name?) a different pseudo-field.

It is also worth noting that this isn't backwards compatible, which is why there are a few queries that needed to add `supported_version` clauses.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java (hunk 7 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/RelationalExpression.java:124]: In general, no, not really. In this case, it's not _just_ persnickety-ness, but it was legitimately hard to tell here whether it was using `RecordType`s or `String`s, which made it hard to understand and what signature to make the new method I was adding to grab the planner type

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java (hunk 8 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java:72]: Yes, it would prevent us from using a version index in a covering optimization. That's actually the purpose of this code, as the `IndexKeyValueToPartialRecord` machinery doesn't actually have a way of threading that information through. It's not currently possible to define a `Copier` which can put the version into the partial record. There are some ways to fix this, including replacing the `IndexKeyValueToPartialRecord` with an RCV (at least for Cascades) or adding a new `Copier` or having the `Copier` create a message from the (dynamic) result type rather than the original type. But until then, we need to block this from trying to extract the row version, as it won't put it anywhere useful.

File: yaml-tests/src/test/resources/enum.yamsql (hunk 3 above)
Comment (alecgrieser) [reply yaml-tests/src/test/resources/enum.yamsql]: For reference, this is an artifact of having a different plan that inserted an extra RCV on top. This is now no longer done in cases like this, and I've reverted this back to its value before the PR in 04bab1f

File: yaml-tests/src/test/resources/field-index-tests-proto.yamsql (hunk 4 above)
Comment (alecgrieser) [reply yaml-tests/src/test/resources/field-index-tests-proto.yamsql:61]: Reverted by 04bab1f

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java (hunk 5 above)
Comment (alecgrieser) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java:401]: Addressed this with 04bab1f where it now looks at the expected new type and compares it to the underlying value's type, and then omits the extra RCV if the types are the same. This change was necessary in order to have the `__ROW_VERSION` not exposed during star expansion, which is (and has always been) the desired semantics of `select *`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java (hunk 14 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java:742]: It would be nice (or at least, it would be nice to cache the single-type variant returned by `getPlannerType(String)`). My initial version of this constructed these structures during `RecordMetaData.build` and then just retrieves it from a `Map`. However, the descriptor to `Type.Record` logic cannot handle cyclic type relationships (e.g., a type `X` with a field of type `Y` which has a field of type `X`), and there are (it turns out) a bunch of tests in our code base with that kind of structure.

We _could_ make this a memoized thing, and then we'd avoid re-creating the same object multiple times. We weren't doing that before, though, in the old code path, so this is at least treading water.

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java (hunk 6 above)
Comment (alecgrieser) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java]: Yeah, that's a good point. I've modified this so that now the RCV construction is done when we make the star expansion, and only if we actually need it to to avoid projecting the `__ROW_VERSION` column (that is, if the RCV type and the underlying value type match). With that, I can simplify these uses to just get the underlying

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java (hunk 9 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java:75]: I tried that and unfortunately, not really, at least not without causing additional trouble. There are places in the planner where we currently do things like construct a `RecordTypeValue` on top of a field value. This is more-or-less the same mistake we're making with `VersionValue`. So, I think we'd be best off if we fixed this with a different pseudo-field and then abandoned the whole thing.

I _did_ make one change along those lines, which is I now have this class deserialize a `QuantifiedObjectValue` into a `QuantifiedRecordValue`. This allowed me to maintain cross-version compatibility, as now older plans get deserialized as new plans. It's all a _bit_ suspect, but the planner can't make much use of this value at the moment at all, so I think we should be okay.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java (hunk 10 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java:127]: I'm not sure I follow. This returns the type _only_ if it's a record or an enum. Primitive types (and UUIDs) get filtered out. This is necessary so that the type repository has the type when it goes to copy it. It also fixed #3734

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java (hunk 11 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java:402]: Yeah, I'm not sure why it was like this before

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java (hunk 12 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java]: There shouldn't be. It's primary raison d'être is to be there when we create the `baseRef`, which currently doesn't have access to the match candidates. We could thread that through, but it seemed easier to put it here. I have renamed this to `baseType`, though, so that it at least aligns with that other set of variables.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/WindowedIndexScanMatchCandidate.java]: Yeah, that makes sense. I've switched the match candidates over to having a `Type.Record`. It unfortunately does mean the same amount of casting, but it happens at match candidate creation time, which is probably better.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java (hunk 8 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/MatchSimpleFieldValueRule.java:72]: I've added a comment in the code about why this is there. Hopefully, we'll be able to remove it at some point

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java (hunk 10 above)
Comment (normen662) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java:127]: This method only really needs to return types that are `Type.Record`. Before your change, it seems it added primitive types as well which made me think about what happens here.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java (hunk 12 above)
Comment (normen662) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/IndexExpansionInfo.java]: Sorry, this was meant as in please rename it to `baseType`. Sorry for being vague and confusing here.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java (hunk 14 above)
Comment (normen662) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java:742]: >However, the descriptor to Type.Record logic cannot handle cyclic type relationships (e.g., a type X with a field of type Y which has a field of type X), and there are (it turns out) a bunch of tests in our code base with that kind of structure.

How is that possible? `Type` is immutable so how can you create those cyclic types. Can you point to a test case that does this?

**Review by normen662 — APPROVED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java (hunk 10 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java:127]: Ah. I believe that before, because it was basing its choice on whether the type was a `CreatesDynamicTypesValue`, which was mostly `RecordConstructorValue` and `AbstractArrayConstructorValue`. So, it would have returned a primitive if that was somehow the return type of one of those (like, say, `PromoteValue`). That no longer works as more things require dynamic types. No one is actually using that marker interface any more, so it could be removed, I suppose.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java (hunk 14 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaData.java:742]: In some sense, it's the immutability of `Type` that is the problem. We have test cases like [`UnnestedRecordTypeTest.unnestDoubleNestedMapType`](https://github.com/FoundationDB/fdb-record-layer/blob/7faaed80631bc371746ed5294b29a4e4f668595a/fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java#L945)  that use `test_records_double_nested.proto` as the basis of their meta-data definition: https://github.com/FoundationDB/fdb-record-layer/blob/main/fdb-record-layer-core/src/test/proto/test_records_double_nested.proto

Note that the types in that file (like, say `MiddleRecord`, which has a field of type `MiddleRecord`) have a cyclic graph. I don't think you _can_ construct a `Type.Record` that models this correctly, and if you try to, you get a `StackOverflowError`. FWIW, I think you would always have gotten a stack overflow error if you tried to use cascades to query this type, and trying to do that eagerly just overturned the bug

**Comment by alecgrieser** [comment]
Adding `DO NOT MERGE`. We have some things regarding the way type names are handled that we may want to work out. Once that's agreed upon, we'll want to take this, possibly with some adjustments for the type naming
