### PR TITLE
set skip and limit for the recursive union cursor correctly.

### LINKED ISSUE #3100: Continuations ignored for query
Summary:
Specifying maxRows:1 for recursive query has no effect
Steps To Reproduce:
1. Look at cte.yamsql
2. Add maxRows:1 to the test:
      - query: with c1 as (select col1, col2 from t1) select col1, col2 from c1
      - maxRows: 1
      - unorderedResult: [{COL1: 10, COL2: 1},
                          {COL1: 10, COL2: 2},
                          {COL1: 20, COL2: 6},
                          {COL1: 20, COL2: 7}]
3. The test still passes

Note: The same happens for UPDATE queries.

### PR DESCRIPTION
**Pull request by hatyo**
This sets the `limit` and `skip` (if any) on the recursive union cursor correctly. It also includes a number of small fixes to the YAML test framework error reporting in case of result mismatches, and a small optimization of handling unordered result matching.

This fixes #3100.

### CODE REVIEW

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java [hunk 1]
```diff
@@ -449,20 +451,24 @@ private static ImmutablePair<ResultSetMatchResult, ResultSetPrettyPrinter> match
 
     private static ImmutablePair<ResultSetMatchResult, ResultSetPrettyPrinter> matchUnorderedResultSet(final RelationalResultSet actual, final @Nonnull Multiset<?> expectedAsMultiSet) throws SQLException {
         final ResultSetPrettyPrinter resultSetPrettyPrinter = new ResultSetPrettyPrinter();
-        var i = 1;
-        // O(n^2) -- we all got M1s
```
Comment (normen662) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java:453]: This is super important! :-)

File: yaml-tests/src/test/resources/recursive-cte.yamsql [hunk 2]
```diff
@@ -68,6 +68,49 @@ test_block:
                  {210, 20},
                  {250, 50},
                  {250, 50}]
+    -
+      - query: with recursive c1 as (
+            select id, parent from t1 where parent = -1
+            union all
+            select b.id, b.parent from c1 as a, t1 as b where a.id = b.parent) select id from c1
+      - maxRows: 1
+      - result: [{ID: 1}]
```
Comment (normen662) [inline yaml-tests/src/test/resources/recursive-cte.yamsql:77]: there is an outstanding PR that does this stuff automatically for up/downlevel testing. So you may not need these tests in a week from now.

**Review by normen662 — APPROVED** [review]

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java [hunk 3]
```diff
@@ -471,12 +477,12 @@ private static ImmutablePair<ResultSetMatchResult, ResultSetPrettyPrinter> match
...
                 printCurrentAndRemaining(actual, resultSetPrettyPrinter);
-                return ImmutablePair.of(ResultSetMatchResult.fail(String.format("result row at %d does not match any expected records", i)), resultSetPrettyPrinter);
+                return ImmutablePair.of(ResultSetMatchResult.fail(String.format("actual row at %d does not match any expected records", actualRowsCounter)), resultSetPrettyPrinter);
             }
-            i++;
+            actualRowsCounter++;
         }
         if (!expectedAsMultiSet.isEmpty()) {
-            return ImmutablePair.of(ResultSetMatchResult.fail("result does not contain all expected rows"), null);
+            return ImmutablePair.of(ResultSetMatchResult.fail(String.format("result does not contain all expected rows, expected %d row(s), got %d row(s) instead.", expectedRowCount, actualRowsCounter - 1)), null);
```
Comment (alecgrieser) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java:485]: I understand that this is tests, but I think we want to refrain from `String.format` (especially without a locale) if we can avoid it. That does seem to be a larger problem in this file, though

**Review by alecgrieser — APPROVED** [review]

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java (hunk 3 above)
Comment (hatyo) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java:485]: I made all the `String.format` calls here use `Locale.ROOT`. I will propose a separate PR that extends this fix to the entire codebase.

File: yaml-tests/src/test/resources/recursive-cte.yamsql (hunk 2 above)
Comment (hatyo) [reply yaml-tests/src/test/resources/recursive-cte.yamsql:77]: Got it, I would leave it for now not to lose test coverage, and we can clean up later when we have a way to automatically test continuations in YAML.

**Review by alecgrieser — APPROVED** [review]

**Review by normen662 — APPROVED** [review]

File: yaml-tests/src/test/resources/recursive-cte.yamsql [hunk 4]
```diff
@@ -68,6 +68,51 @@ test_block:
                  {210, 20},
                  {250, 50},
                  {250, 50}]
+    -
+      - query: with recursive c1 as (
+            select id, parent from t1 where parent = -1
+            union all
+            select b.id, b.parent from c1 as a, t1 as b where a.id = b.parent) select id from c1
+      - supported_version: !current_version
```
Comment (hatyo) [inline yaml-tests/src/test/resources/recursive-cte.yamsql:76]: It looks like without this, some JDBC tests were failing as they were incorrectly trying to run continuations against `4.0.575.0`. If I understand what this configuration means correctly, the query will be tested against current commit onwards only, which is the correct thing to do, considering that recursive CTE support of continuations was misbehaving before this PR. @ScottDugas can you please have a look?

**Review by normen662 — APPROVED** [review]

**Review by alecgrieser — DISMISSED** [review]
LGTM. I'm not sure we have great documentation of the stability of this feature, which is for all intents and purposes experimental. We should probably still call out that limit and skip behavior have changed in the release notes, potentially calling it out as a breaking change. We'll be updating to 4.1 fairly soon (see #3082), and I don't think we'd usually update the minor version on an experimental change like this, but it wouldn't be a bad idea to piggy back on that minor version bump in this case (which basically just means merging but not releasing until the other PR goes in)

**Comment by alecgrieser** [comment]
Given the state of the PRs, we could even update the release notes on #3082 to avoid merge conflicts

**Review by alecgrieser — APPROVED** [review]
