### PR TITLE
Resolve #2234: Fix readSchema deadlock.

### LINKED ISSUE #2234: ReadSchema deadlock
The Lucene code for FieldInfos' read_schema is deadlocking. It looks like the caching mechanism is causing threads to block and for the readSchema call to time out.

### PR DESCRIPTION
**Pull request by ohadzeliger**
Create a reproducing test for the Lucene thread deadlock

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 1]
```diff
@@ -138,14 +144,14 @@ public static void setup() {
             TextSamples.AETHELRED,
             TextSamples.PARTIAL_ROMEO_AND_JULIET_PROLOGUE,
             TextSamples.FRENCH,
-            TextSamples.ROMEO_AND_JULIET_PROLOGUE,
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:141]: We should keep this consistent with the rest, and avoid the static import

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 2]
```diff
@@ -1271,4 +1277,55 @@ void continuations(boolean sorted) throws Exception {
             }
         }
     }
+
+    /**
+     * This tests is reproducing a thread deadlock that happened with Lucene threads when reading schema information.
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1282]:
```suggestion
     * This test is reproducing a thread deadlock that happened with Lucene threads when reading schema information.
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 3]
```diff
@@ -1271,4 +1277,55 @@ void continuations(boolean sorted) throws Exception {
...
+     * The fix for the deadlock has removed the {@code Map.computeIfAbsent} call (with the {@code synchronized} block)
+     * that blocked the {@code asyncToSync} calls.
+     * This test creates a large enough set of {@link org.apache.lucene.index.SegmentReader} futures so as to flood the thread pool,
+     * and then queries Lucene. THe large number of futures in the pool, together with the {@code synchronized} block
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1286]:
```suggestion
     * and then queries Lucene. The large number of futures in the pool, together with the {@code synchronized} block
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 4]
```diff
@@ -1271,4 +1277,55 @@ void continuations(boolean sorted) throws Exception {
...
+     * would cause a deadlock.
+     */
+    @Test
+    void testQueryWithManyDocuments() {
+        String[] words = generateRandomWords(1000);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1291]: It's probably worth commenting here that we generate random words, rather than using the `TextSamples`, or choosing random words from the `TextSamples`, because Lucene is too efficient at compressing those, so even with a lot of documents (100k+ If I remember correctly), it still falls short of creating enough segments to cause a problem.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 5]
```diff
@@ -1271,4 +1277,55 @@ void continuations(boolean sorted) throws Exception {
...
+        FDBDatabaseFactory.instance().setExecutor(new ForkJoinPool(Runtime.getRuntime().availableProcessors(),
+                ForkJoinPool.defaultForkJoinWorkerThreadFactory,
+                null, false));
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1294]: Setting it to `availableProcessors` might more accurately represent how someone would use a `ForkJoinPool` as the executor, but it makes this test less reproducible. For example if you ran this on a machine with 128 cores, it would probably pass even with the deadlock, but reproduce the issue on a machine with 4 cores (like a docker container, or a rather old computer).
4 might be too small and detect other deadlocks, so maybe 8 or 16 is more appropriate for now, although I think, ideally we would be able to use lucene with a million segments with a parallelism of 1.
```suggestion
        FDBDatabaseFactory.instance().setExecutor(new ForkJoinPool(4,
                ForkJoinPool.defaultForkJoinWorkerThreadFactory,
                null, false));
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java [hunk 6]
```diff
@@ -1271,4 +1277,55 @@ void continuations(boolean sorted) throws Exception {
...
+        FDBDatabaseFactory.instance().getDatabase().setAsyncToSyncTimeout( event -> {
+            // Make AsyncToSync calls timeout after one second
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1296]:
```suggestion
            // Make AsyncToSync calls timeout after one second, otherwise a deadlock would just result in the test taking forever
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 4 above)
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1291]: IF `generateRandomWords` is `public`, and used by a variety of tests, it should probably be moved to `LuceneIndexTestutils`

Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java:1291]: I don't understand the api for `generateRandomWords`, but you're not using it correctly here.
IIUC it generates an array of two elements:
`words[1]` is a string of 1,000 randomly generated words, separated by a string
`words[0]` is the last word in `words[1]`

The otherr two usages just use `words[1]` and completely forget `words[0]`.

It might also be simpler by having a `String generateRandomWord(int minLength, int maxLength)`
And then you could have two methods that easily use that:
```
Stream.generate(() -> generateRandomWord(3, 10)).limit(1000).collect(Collectors.joining(" "));
```
and
```
Stream.generate(() -> generateRandomWords(3, 10)).limit(1000).collect(Collectors.toList())
```
and use the later in this test, and then randomly chose from that. Or you could perhaps use the former repeatedly, which would basically result in every document having completely unique sets of words, at least until you generate 141 trillion words. It would be very detached from legitimate use cases of lucene, but might force it to make many segments.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Sure, done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 3 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 4 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Done.

Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Done.

Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Sorry, my mistake. The actual usage of generateRandomWords(500) would generate the string that we eventually need, so no need to process further. The code was the result of having the prior random word selector in place.
Done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 5 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Good point. The test should be reproducible under all conditions and the existing code would make it unpredictable.
Done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java (hunk 6 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java]: Done.

**Review by ScottDugas — APPROVED** [review]
