### PR TITLE
Resolves #2293: Rethrow original IOExceptions in lucene code

### LINKED ISSUE #2293: Rethrow IOException instead of UncheckedIOException
A bunch of LuceneOptimized formats add laziness so that we don't read data from FDB that we don't have to, going against Lucene's aggressive reading.

When we do this we turn `IOException` into `UncheckedIOException`, when we actually access it, we should unwrap the exception, throwing the original.

### PR DESCRIPTION
**Pull request by ScottDugas**
We were wrapping them in UncheckedIOException, this creates two new helpers `LuceneOpener` and `LuceneCloseable` that make it easier to unwrap the exception appropriately, and close the lazily opened object correctly.

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+import static org.junit.jupiter.api.Assertions.assertThrows;
+
+class LazyCloseableTest {
+
+    @Test
+    void testOpensLazilyExactlyOnce() throws IOException {
+        final AtomicInteger openCounter = new AtomicInteger(0);
+        final AtomicInteger closeCounter = new AtomicInteger(0);
+        try (LazyCloseable<CountingCloseable> opener = LazyCloseable.supply(
+                () -> new CountingCloseable(openCounter.incrementAndGet(), closeCounter))) {
```
Comment (ohadzeliger) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:41]: It may be more interesting to pass the openCounter itself to the CountingCloseable and increment it at the constructor

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+    @Test
+    void testCloseCloses() throws IOException {
+        final AtomicInteger openCounter = new AtomicInteger(0);
+        final AtomicInteger closeCounter = new AtomicInteger(0);
+        try (LazyCloseable<CountingCloseable> opener = LazyCloseable.supply(() -> new CountingCloseable(openCounter.incrementAndGet(), closeCounter))) {
+            opener.get();
+        }
+        assertEquals(1, openCounter.get());
+        assertEquals(1, closeCounter.get());
```
Comment (ohadzeliger) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:68]: Call `close()` multiple times? (This is to ensure the `LazyCloseable` doesn't do anything funky during close)

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+    @Test
+    void testThrowsUncheckedIoException() {
+        IOException thrownException = new IOException("test foo");
+        final LazyCloseable<Closeable> opener = LazyCloseable.supply(() -> {
+            throw thrownException;
+        });
+        final UncheckedIOException resultingException = assertThrows(UncheckedIOException.class, opener::getUnchecked);
+        assertSame(thrownException, resultingException.getCause());
+    }
```
Comment (ohadzeliger) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:89]: Add tests that use the `clone()` method? This is of particular interest for the way this is used...

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+        final AtomicInteger closeCounter;
+
+        private CountingCloseable(final int openCounts, final AtomicInteger closeCounter) {
+            this.openCounts = openCounts;
+            this.closeCounter = closeCounter;
+        }
+
+        @Override
+        public void close() {
+            closeCounter.incrementAndGet();
```
Comment (ohadzeliger) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:102]: Should we add tests where the `close()` throws exception?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+        try (LazyCloseable<CountingCloseable> opener = LazyCloseable.supply(() -> new CountingCloseable(openCounter.incrementAndGet(), closeCounter))) {
+            opener.get();
+        }
+        assertEquals(1, openCounter.get());
+        assertEquals(1, closeCounter.get());
+    }
+
+    @Test
+    void testThrowsIoException() {
+        IOException thrownException = new IOException("test foo");
```
Comment (ohadzeliger) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:73]: This does not assert on the counters, but the expectation is that they are 1 and 0, and that initialized == false?

**Review by ohadzeliger — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java [hunk 6]
```diff
@@ -0,0 +1,243 @@
...
+                    return opener.getUnchecked();
+                })
+                .collect(Collectors.toList());
+        MatcherAssert.assertThat(allValues, Matchers.everyItem(Matchers.sameInstance(allValues.get(0))));
+        // Stream.parallel doesn't guarantee that it will run in 100 parallel threads
+        MatcherAssert.assertThat(threads.keySet(), Matchers.hasSize(Matchers.greaterThan(10)));
+    }
+
+    @Test
+    void testForkJoinPoolDeadlock() throws ExecutionException, InterruptedException, TimeoutException {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java:98]: I was inspired to add this test, and the version on `LazyOpenerTest`, since this seems particularly important for our use case.

**Review by ohadzeliger — APPROVED** [review]
Approved. Build failures are for Style checks.

**Review by ohadzeliger — APPROVED** [review]
