### PR TITLE
Resolves #2754: FDBDirectoryLock won't fail if flushed in close

### LINKED ISSUE #2754: FDBDirectoryLock commit check may fail if called after clearing the key
In a recent test run, `LuceneIndexMaintenanceTest.flakyMerge` failed twice.

I suspect this is due to #2730

```
2024-06-07T08:02:56.972153Z LuceneIndexMaintenanceTest > flakyMerge(true, true, true, 31, -644766138635622644, true) STARTED
2024-06-07T08:03:56.310772Z LuceneIndexMaintenanceTest > flakyMerge(true, true, true, 31, -644766138635622644, true) SUCCESS (59302ms)

2024-06-07T08:03:56.310887Z LuceneIndexMaintenanceTest > flakyMerge(true, false, false, 50, 9237590782644, true) STARTED
2024-06-07T08:05:10.284911Z LuceneIndexMaintenanceTest > flakyMerge(true, false, false, 50, 9237590782644, true) SUCCESS (74011ms)

2024-06-07T08:05:10.285607Z LuceneIndexMaintenanceTest > flakyMerge(false, true, true, 33, -1089113174774589435, true) STARTED
2024-06-07T08:05:47.682215Z LuceneIndexMaintenanceTest > flakyMerge(false, true, true, 33, -1089113174774589435, true) SUCCESS (37398ms)

2024-06-07T08:05:47.682881Z LuceneIndexMaintenanceTest > flakyMerge(false, false, false, 35, 6223372946177329440, true) STARTED
2024-06-07T08:06:19.058313Z LuceneIndexMaintenanceTest > flakyMerge(false, false, false, 35, 6223372946177329440, true) FAILURE (31304ms)


LuceneIndexMaintenanceTest > flakyMerge(boolean, boolean, boolean, int, long, boolean) > com.apple.foundationdb.record.lucene.LuceneIndexMaintenanceTest.flakyMerge(boolean, boolean, boolean, int, long, boolean)[4] FAILED
    org.apache.lucene.store.AlreadyClosedException: Lock file was deleted. This={FDBDirectoryLock: name=write.lock uuid=5d80e743-9939-4cd5-a27e-3c24e56ff3ee timeMillis=1717747578973}
        at app//com.apple.foundationdb.record.lucene.directory.FDBDirectoryLockFactory$FDBDirectoryLock.fileLockCheckHeartBeat(FDBDirectoryLockFactory.java:159)
        at app//com.apple.foundationdb.record.lucene.directory.FDBDirectoryLockFactory$FDBDirectoryLock.lambda$fileLockSet$1(FDBDirectoryLockFactory.java:144)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
        at app//com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:72)
        at app//com.apple.foundationdb.async.TaskNotifyingExecutor$Notifier.run(TaskNotifyingExecutor.java:77)
        at java.base@11.0.23/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.23/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.23/java.lang.Thread.run(Thread.java:829)
2024-06-07T08:06:19.069569Z LuceneIndexMaintenanceTest > flakyMerge(true, false, true, 21, -3788184932912394428, false) STARTED
2024-06-07T08:07:12.868925Z LuceneIndexMaintenanceTest > flakyMerge(true, false, true, 21, -3788184932912394428, false) SUCCESS (53882ms)

2024-06-07T08:07:12.869653Z LuceneIndexMaintenanceTest > flakyMerge(true, true, true, 14, 965615350796802421, false) STARTED
2024-06-07T08:07:45.553803Z LuceneIndexMaintenanceTest > flakyMerge(true, true, true, 14, 965615350796802421, false) FAILURE (32664ms)


LuceneIndexMaintenanceTest > flakyMerge(boolean, boolean, boolean, int, long, boolean) > com.apple.foundationdb.record.lucene.LuceneIndexMaintenanceTest.flakyMerge(boolean, boolean, boolean, int, long, boolean)[6] FAILED
    org.apache.lucene.store.AlreadyClosedException: Lock file was deleted. This={FDBDirectoryLock: name=write.lock uuid=76a7d255-c7cc-4f92-af4d-85e499f69410 timeMillis=1717747665519}
        at app//com.apple.foundationdb.record.lucene.directory.FDBDirectoryLockFactory$FDBDirectoryLock.fileLockCheckHeartBeat(FDBDirectoryLockFactory.java:159)
        at app//com.apple.foundationdb.record.lucene.directory.FDBDirectoryLockFactory$FDBDirectoryLock.lambda$fileLockSet$1(FDBDirectoryLockFactory.java:144)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.23/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)
        at app//com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:72)
        at app//com.apple.foundationdb.async.TaskNotifyingExecutor$Notifier.run(TaskNotifyingExecutor.java:77)
        at java.base@11.0.23/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.23/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.23/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by ScottDugas**
Previously, if the context that was clearing the lock was flushed, the commit check would fail because the lock is missing. It now protects against this.
This also means that LuceneIndexMaintenanceTest.flakyMerge is no longer flaky.

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java [hunk 1]
```diff
@@ -130,6 +131,46 @@ void testFileLockCallback() throws IOException {
         }
     }
 
+    @Test
+    void testFileLockCallbackFrequently() throws IOException {
+        // This test simulates the situation where the AgilityContext flushes as part of the call to clear
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java:136]: This test specifically failed without the code change

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java [hunk 2]
```diff
@@ -130,6 +131,46 @@ void testFileLockCallback() throws IOException {
...
+            try {
+                final Lock lock1 = directory.obtainLock(lockName);
+                if (clearLock) {
+                    forceClearLock(lockName);
+                } else {
+                    forceStealLock(lockName);
+                }
+                assertThrows(AlreadyClosedException.class, lock1::close);
+            } finally {
+                assertThrows(AlreadyClosedException.class, directory::close);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java:167]: I'm not entirely sure if this is the behavior we want here. 
Note: the `directory.close()` only fails if the lock is stolen above, if it is cleared, it won't throw an exception.

Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java:167]: Perhaps the lock should throw it, but the directory should not, at least from the javadoc for Lock:
```
   * Releases exclusive access.
   * <p>
   * Note that exceptions thrown from close may require
   * human intervention, as it may mean the lock was no
   * longer valid, or that fs permissions prevent removal
   * of the lock file, or other reasons.
   * <p>
 ```

Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockTest.java:167]: I agree that both stolen and cleared locks should cause an exception during an explicit lock close - as it means that Lucene assumes it has the lock while it doesn't.
The directory only calls `fileLockClearIfLocked` during close, so the scenario may be:

Getting an IO exception that leaves the lock behind
Closing the directory
Something else had stolen or cleared
An exception would not help in this recovery path, but maybe an error message will be appropriate if the lock was less than `timeWindowMilliseconds` ms old (again, for both stolen and cleared).

**Review by jjezra — APPROVED** [review]
