### PR TITLE
Resolves #903 Reorganize tests

### LINKED ISSUE #903: FDBRecordStoreTest is huge
FDBRecordStoreTest is almost 4000 lines of test code. It should be broken up into more focused test fixtures for different features or components.

### PR DESCRIPTION
**Pull request by ScottDugas**
This has 4 commits that do cleanup, and one that moves all the tests around

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniquenessTest.java [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+import java.util.concurrent.CompletableFuture;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertThrows;
+
+/**
+ * Tests of uniqueness checks.
+ */
+@Tag(Tags.RequiresFDB)
+public class FDBRecordStoreUniquenessTest extends FDBRecordStoreTestBase {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniquenessTest.java:43]: This kind of feels like it should be, like, an "index" test rather than a uniqueness test, in that it's really testing that behavior rather than the store's. But probably a rename that could happen later.

**Comment by alecgrieser** [comment]
Great, will merge after successful PRB
