### PR TITLE
Fixes #756: Serialization of LiteralKeyExpression can be incorrect.

### LINKED ISSUE #756: Serialization of LiteralKeyExpression casts long value to floats
When we create a `LiteralKeyExpression` using Java objects (instead of passing an existing Protobuf), we use the `LiteraKeyExpression.toProtoValue()` method to create a serialized form, which is used (among other things) for the `LiteralKeyExpression`s `equals()` method.

Currently, all numeric types, including integers, are converted to floating point values in this serialization.

### PR DESCRIPTION
**Pull request by nschiefer**
Previously, serializing certain `LiteralKeyExpression`s (of type`Long` or `byte[]`) would produce a Protobuf that, when deserialized, would not contain a value of a different type (`Float` or `ByteString`, respectively). This fixes #756 and adds some tests that should give us more confidence that the serialization is correct.

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+                1.0f,
+                2.0d,
+                100L,
+                Long.MIN_VALUE,
+                Long.MAX_VALUE,
+                true,
+                false,
+                "a string",
+                "(╯°□°)╯︵ ┻━┻",
+                "┳━┳ ヽ(ಠل͜ಠ)ﾉ",
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java]: So there's a weird other case that might be worth seeing what it does:

`"malformed surrogate pair: \uD83C"`

That unicode character is a high-surrogate and it's missing its low surrogate buddy, so it can't be expressed in UTF-8, so Protobuf might do weird things with it.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+                TextSamples.EMOJIS,
+                TextSamples.YIDDISH,
+                "\n",
+                byteArray);
+    }
+
+    private static Stream<Integer> incorrectValues() {
+        return Stream.of(5, -10, Integer.MAX_VALUE, Integer.MIN_VALUE);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java]: Ideally, it would be good to validate that these at least refer to longs that are semantically equal, but maybe that's difficult (that it's the integer cast as long).

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java (hunk 1 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java]: Added a test. It works fine if we do everything with Java's protobuf objects, but things break if we add a byte serialization in the middle.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java (hunk 2 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/expressions/LiteralKeyExpressionTest.java]: Done.
