### PR TITLE
Resolves #85: Create a validator to check if a new meta-data is a valid evolution of an old one

### LINKED ISSUE #85: Create a validator to check if a new meta-data is a valid evolution of an old one
This is useful for meta-data evolution. I believe what it needs to do is:

* Validate that each record type in the old schema is also in the new schema.
* Validate that every field in each record type in the old schema is still present in the new schema and that its type hasn't changed (or has changed to a valid value) and it has the same repeated/optional/required whateverthatscalled.
* The primary key of each record type should be the same.
* Do some validation of the union descriptors to make sure people are deprecating rather than changing old fields (see: #27 and #45).
* Check the indexes to make sure that all of the old indexes are either in the new one or registered as former indexes; each index should continue to be on the same key expression; and each should generally have the same set of options with a few exceptions and should have the same type. New indexes should not reuse the same type or subspace key as former or existing indexes.

I think that's it. In theory, a more advanced validator could do things like:

* Field renaming: Has to make sure all references in the primary key or within indexes that referenced the old value now use the new value; if it's a field that is in a multi-type index, then all of the other types need to be similarly renamed.
* Field type changing: Only need to follow the [Protobuf rules](https://developers.google.com/protocol-buffers/docs/proto#updating) for safely updating a message type if the field isn't indexed; otherwise, the rules are stricter (for example, `string` -> `bytes` is valid in Protobuf because a `string` is just a `bytes` that must be UTF-8 whereas in the Tuple layer, those two are encoded with separate type codes, so `string` -> `bytes` would *not* be legal).

The validator would need to take both the old meta-data and the new meta-data to make this comparison. This is known if one is, for example, using the `FDBMetaDataStore`, but it could (in theory) be known by other users who just so happen to have both meta-data objects lying around. (For example, you could imagine a client testing a new schema locally, and then they could invoke this method before pushing their change.)

### PR DESCRIPTION
**Pull request by alecgrieser**
The `MetaDataEvolutionValidator` takes two `RecordMetaData` objects. It then validates that the second can be constructed by evolving the first within the parameters of our meta-data evolution guidelines. The checks here are rather strict in that they make conservative choices like *never* allowing field renames (even on non-indexed fields for which that is safe), but I think it is loose enough to allow most users evolve their schema responsibly.

### CODE REVIEW

**Comment by alecgrieser** [comment]
Sorry also that the changes in this PR are a little...big. Most of the changes I think are actually in the tests, but it's still a lot to go through. Tests also took up a significant amount of the development time, as one might expect.

**Comment by alecgrieser** [comment]
This resolves #85.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 1]
```diff
@@ -0,0 +1,906 @@
...
+                    LogMessageKeys.NEW_FIELD_NAME, newFieldDescriptor.getName());
+        }
+        if (!oldFieldDescriptor.getType().equals(newFieldDescriptor.getType())) {
+            validateTypeChange(oldFieldDescriptor, newFieldDescriptor);
+        }
+        if (oldFieldDescriptor.isRequired() && !newFieldDescriptor.isRequired()) {
+            throw new MetaDataException("required field is no longer required",
+                    LogMessageKeys.FIELD_NAME, oldFieldDescriptor.getName());
+        } else if (oldFieldDescriptor.isOptional() && !newFieldDescriptor.isOptional()) {
+            // TODO: In theory, optional -> repeated is okay, but only if the field is not indexed
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: Or if the index definition is changed to fan-out at the same time, I think. Not for this branch, but maybe update the comment?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 2]
```diff
@@ -0,0 +1,906 @@
...
+            // TODO: Field renaming should be allowed with some caveats about if the field is indexed or not
+            throw new MetaDataException("field renamed",
+                    LogMessageKeys.OLD_FIELD_NAME, oldFieldDescriptor.getName(),
+                    LogMessageKeys.NEW_FIELD_NAME, newFieldDescriptor.getName());
+        }
+        if (!oldFieldDescriptor.getType().equals(newFieldDescriptor.getType())) {
+            validateTypeChange(oldFieldDescriptor, newFieldDescriptor);
+        }
+        if (oldFieldDescriptor.isRequired() && !newFieldDescriptor.isRequired()) {
+            throw new MetaDataException("required field is no longer required",
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: Isn't required -> optional okay?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 3]
```diff
@@ -0,0 +1,906 @@
...
+                if (newSinceVersion == null) {
+                    if (!allowNoSinceVersion) {
+                        throw new MetaDataException("new record type is missing since version",
+                                LogMessageKeys.RECORD_TYPE, recordTypeName);
+                    }
+                } else if (newSinceVersion <= oldMetaData.getVersion()) {
+                    throw new MetaDataException("new record type has since version older than old meta-data",
+                            LogMessageKeys.RECORD_TYPE, recordTypeName);
+                } else if (newSinceVersion > newMetaData.getVersion()) {
+                    throw new MetaDataException("new record type has since version new than new meta-data",
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]:
```suggestion
                    throw new MetaDataException("new record type has since version newer than new meta-data",
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 4]
```diff
@@ -0,0 +1,906 @@
...
+                                LogMessageKeys.SUBSPACE_KEY, subspaceKey,
+                                LogMessageKeys.OLD_VERSION, oldMetaData.getVersion(),
+                                LogMessageKeys.NEW_VERSION, newFormerIndex.getAddedVersion());
+                    }
+                } else {
+                    validateFormerIndexFromIndex(subspaceKey, oldIndex, newFormerIndex);
+                }
+            }
+        }
+        // Validate each index in the new meta-data matches the existing one or is new
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]:
```suggestion
        // Validate each index in the new meta-data matches an existing one or is new
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 5]
```diff
@@ -0,0 +1,906 @@
...
+        }
+        if (!oldIndex.getRootExpression().equals(newIndex.getRootExpression())) {
+            throw new MetaDataException("index key expression changed",
+                    LogMessageKeys.INDEX_NAME, newIndex.getName(),
+                    LogMessageKeys.OLD_KEY_EXPRESSION, oldIndex.getRootExpression(),
+                    LogMessageKeys.NEW_KEY_EXPRESSION, newIndex.getRootExpression());
+        }
+        // All of the record types associated with the old index should be contained in the new index.
+        // The new index might have new record types, but they need to be from record types associated
+        // with newer record types than the old meta-data.
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: I think this could be clearer. Maybe "additional" record types and maybe strike "from ... with."

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java [hunk 6]
```diff
@@ -0,0 +1,1238 @@
...
+                        message.getFieldBuilderList().forEach(field -> {
+                            if (field.getName().equals("header")) {
+                                field.setTypeName("." + fileBuilder.getPackage() + ".Header");
+                            }
+                        });
+                    }
+                })
+        );
+        assertThat(updatedFile.getMessageTypes().stream().map(Descriptor::getName).collect(Collectors.toList()), containsInAnyOrder("MyRecord", "RecordTypeUnion", "Header"));
+        validator.validateUnion(TestRecordsWithHeaderProto.RecordTypeUnion.getDescriptor(), updatedFile.findMessageTypeByName("RecordTypeUnion"));
```
Comment (amouehsan) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java]: Maybe use `RecordMetaDataBuilder.DEFAULT_UNION_NAME` here and elsewhere?

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java [hunk 7]
```diff
@@ -0,0 +1,1238 @@
...
+    private RecordMetaDataProto.Index makeUnique(@Nonnull RecordMetaDataProto.Index indexProto) {
+        return changeOption(indexProto, IndexOptions.UNIQUE_OPTION, "true");
+    }
+
+    @Nonnull
+    private RecordMetaDataProto.Index clearOptions(@Nonnull RecordMetaDataProto.Index indexProto) {
+        return indexProto.toBuilder().clearOptions().build();
+    }
+
+
```
Comment (amouehsan) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTest.java]: blank line?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 8]
```diff
@@ -305,6 +309,9 @@ private void loadFromFileDescriptor(@Nonnull Descriptors.FileDescriptor fileDesc
     private Descriptors.Descriptor initRecordTypes(@Nonnull Descriptors.FileDescriptor fileDescriptor, boolean processExtensionOptions) {
         Descriptors.Descriptor unionDescriptor = fetchUnionDescriptor(fileDescriptor);
         validateRecords(fileDescriptor, unionDescriptor);
+        if (localUnionDescriptor != null) {
```
Comment (amouehsan) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: maybe move it to `validateRecords`, or even better `validateUnion`?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: Hm, I think it might be actually. (I was under the impression it used a different serialization format for required fields when I wrote this, but that's not the case.) The protobuf guidelines seem to warn against downgrading from required to optional. I think the problem case is if the user changes a field from `required` to `optional` and then someone else reads it, they will throw a validation error at deserialization time, which is what the protobuf language guide warns against: https://developers.google.com/protocol-buffers/docs/proto

I guess I mainly included this so that we conformed with the protobuf guidelines on schema evolution (or rather enforced a strict superset of their rules). I suppose we could relax this.

**Comment by alecgrieser** [comment]
Rebase is to pick up changes from master. To ease review on a PR this bug, I’m going to continue pushing commits like this. We should plan on squashing when it is merged (or I can squash).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 8 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure. what you have is fine too.

File: docs/SchemaEvolution.md [hunk 9]
```diff
@@ -21,8 +21,33 @@ So one of the following techniques should be used:
...
+## Validating Changes
+
+If it is possible to know both the previous and new values for the meta-data, one can validate that the new meta-data has been responsibly evolved from the old meta-data by using the [`MetaDataEvolutionValidator`](https://javadoc.io/page/org.foundationdb/fdb-record-layer-core/latest/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.html) class. Basic usage is something like:
+
+```java
+MetaDataEvolutionValidator validator = MetaDataEvolutionValidator.getDefaultInstance();
+validator.validate(oldMetaData, newMetaData);
+``` 
+
+The `validate` function will throw a `MetaDataException` if the new meta-data has not been evolved from the old one in a way that does not require migrating data already stored by the record store. It is generally strict about the kinds of meta-data modifications it allows, and it attempts to be conservative. For example, it will not allow modifications to existing indexes that require they be rebuilt as the assumption is that such a modification is likely to be accidental.
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply docs/SchemaEvolution.md]: I see thanks for the clarification.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java (hunk 2 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: Yeah, okay, that sounds right. So I guess we leave it for now.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java (hunk 1 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: That sounds like more than this branch attempts.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 10]
```diff
@@ -0,0 +1,906 @@
...
+        return new Builder(DEFAULT_INSTANCE);
+    }
+
+    /**
+     * Get the default validator. This has all options set to their default values.
+     *
+     * @return the default validator
+     */
+    @Nonnull
+    public static MetaDataEvolutionValidator getDefaultInstance() {
```
[the remark this answers is not in the document]
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: We can try that for a while and see how difficult it turns out to be in practice.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 11]
```diff
@@ -0,0 +1,906 @@
...
+import java.util.Set;
+import java.util.stream.Collectors;
+
+/**
+ * This class can be used to validate that the new meta-data for a record store is responsibly evolved from its
+ * existing meta-data. In particular, this validates that:
+ *
+ * <ul>
+ *     <li>No record types are dropped.</li>
+ *     <li>None of the existing records drops one of its fields.</li>
```
[the remark this answers is not in the document]
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: How come I don't see that here? Is the GitHub UI confused or are we missing a commit?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java [hunk 12]
```diff
@@ -0,0 +1,906 @@
...
+        this.allowOlderFormerIndexAddedVersions = builder.allowOlderFormerIndexAddedVersions;
+    }
+
+    /**
+     * Validate that the new meta-data for a store are a valid evolution from the existing meta-data.
+     * This makes sure that existing records saved within the record store can still be read using the
+     * new meta-data and it verifies that indexes are added and removed in a safe way.
+     *
+     * @param oldMetaData the existing meta-data for a record store
+     * @param newMetaData the new meta-data for the same record store
```
[the remark this answers is not in the document]
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: That's pretty good. It keeps the idea that they are supposed to be used for the same ones.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: It was apparently hiding in my `git stash`. Updated in a new commit.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java]: Okay, change made.

**Comment by alecgrieser** [comment]
As I mentioned in a comment on #377, I am not sure whether `RecordMetaDataBuilder.setEvolutionValidator` should return `this` (like most `setX` methods on `Builder`s) or `void` (like most of the other `setX`  methods on `RecordMetaDataBuilder`). In the code right now, it returns `void`, but I kind of want to make it return `this`, but I wanted to see if there were other opinions. It also might be nice to come up with a firm rule to determine which is which.

**Comment by MMcM** [comment]
I do not have a strong opinion one way or the other. I'm happy to take this as is to to accept a change to the builder's return types.

**Comment by amouehsan** [comment]
> As I mentioned in a comment on #377, I am not sure whether `RecordMetaDataBuilder.setEvolutionValidator` should return `this` (like most `setX` methods on `Builder`s) or `void` (like most of the other `setX` methods on `RecordMetaDataBuilder`). In the code right now, it returns `void`, but I kind of want to make it return `this`, but I wanted to see if there were other opinions. It also might be nice to come up with a firm rule to determine which to use in general.

I think either way is fine. I generally prefer setX methods to return `this`.

**Comment by alecgrieser** [comment]
Okay, I updated it to return `this`. It means the user can now do:

```java
RecordMetaData metaData = RecordMetaData.newBuilder()
      .setEvolutionValidator(evoluationValidator)
      .setLocalFileDescriptor(localFileDescriptor)
      .setRecords(metaDataProto)
      .getRecordMetaData();
```

You definitely want the `evolutionValidator` set before you set `records` (otherwise, you might not get the options you want for validating that the local file descriptor is a valid evolution of the existing meta-data), so if it were a `void` method, it would have broken that flow.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 13]
```diff
@@ -1020,11 +1020,14 @@ public MetaDataEvolutionValidator getEvolutionValidator() {
      * in the meta-data proto.
      *
      * @param evolutionValidator the validator used to check the local file descriptor against the one in the meta-data proto
+     * @return this builder
      * @see #setLocalFileDescriptor(Descriptors.FileDescriptor)
      * @see MetaDataEvolutionValidator
      */
-    public void setEvolutionValidator(@Nonnull MetaDataEvolutionValidator evolutionValidator) {
+    @Nonnull
+    public RecordMetaDataBuilder setEvolutionValidator(@Nonnull MetaDataEvolutionValidator evolutionValidator) {
```
Comment (amouehsan) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: > You definitely want the `evolutionValidator` set before you set `records`

Then how about you explicitly disallow it here?

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Good idea. Done.

**Comment by alecgrieser** [comment]
The PRB failed I think to due to #395. I have a local fix for that, but it should be a separate PR.

test this please

**Comment by alecgrieser** [comment]
(The fix for #395 should be a separate PR because that issue is wholly unrelated to this PR in every way.)

**Comment by alecgrieser** [comment]
Rebase squashes the various commits and puts it against master.
