### PR TITLE
Resolve #1725: Reconstruct KeyWithValue expression correctly.

### LINKED ISSUE #1725: Cascades does not reconstruct a KeyWithValue correctly
When Cascades expands a Index into a `KeyExpression`, there is some logic that examines the index's root expression keys and appends any missing primary keys to the end via concat. This works as expected for `ThenKeyExpression`.

However if the root expression is `KeyWithValue` such as e.g. (`KeyWithValue({RecordType, A, B} 2)`, where `A` is a primary key), then it will pass the `KeyWithValue` as-is to concat causing it to fail, because concat thinks there is only a single key to be concatenated (but in our example above, we have two keys: `RecordType` and `A`).

### PR DESCRIPTION
**Pull request by hatyo**
When Cascades expands a `Index` into a `KeyExpression`, there is some logic that examines the index's root expression keys and appends any missing primary keys to the end via `concat`. This works as expected for `ThenKeyExpression`.

However if the root expression is `KeyWithValue` such as e.g. (`KeyWithValue({RecordType, A, B} 2)`, where `A` is a primary key), then it will pass the `KeyWithValue` as-is to `concat` causing it to fail, because `concat` thinks there is only a single key to be concatenated (but in our example above, we have two keys: `RecordType` and `A`).

To fix this problem, we check first if the root expression is a `KeyWithValue`, if so, we get its key expression, and proceed with the same logic.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java [hunk 1]
```diff
@@ -156,13 +156,16 @@ public MatchCandidate expand(@Nonnull final Supplier<Quantifier.ForEach> baseQua
...
+                                             : index.getRootExpression();
         if (primaryKey == null) {
-            return index.getRootExpression();
+            return rootExpression;
         }
         final var trimmedPrimaryKeyComponents = new ArrayList<>(primaryKey.normalizeKeyForPositions());
         index.trimPrimaryKey(trimmedPrimaryKeyComponents);
         final var fullKeyListBuilder = ImmutableList.<KeyExpression>builder();
-        fullKeyListBuilder.add(index.getRootExpression());
+        fullKeyListBuilder.add(rootExpression);
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java:168]: This is wrong (and it used to be wrong). We should not just blindly use the `rootExpression` here either in the presence of `KeyWithValue`. I think we should also call `normalizeKeyForPositions()` on the `rootExpression` and then properly pick and merge the pieces from normalized root and from normalized primary..

Comment (normen662) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java:168]: Do you mind changing that? It's great you found this (admittedly quite old) problem...

**Review by normen662 — DISMISSED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java (hunk 1 above)
Comment (hatyo) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ValueIndexExpansionVisitor.java:168]: It looks like there was some misunderstanding, after some discussion we found the fix is actually correct 😄 .
