### PR TITLE
Resolves #3: Use evolved meta-data file descriptor to build meta-data

### LINKED ISSUE #3: Using stored MetaData can lead to "descriptor did not match record type" when saving records
If one is using a statically-generated proto file (rather than a dynamically generated one) that has extensions specifying indexes on fields and are also using the MetaDataStore to try and distribute the metadata to applications, then the following set of circumstances can lead to an `IllegalArgumentException` being thrown with the message "descriptor did not match record type":

1) One serializes and stores the record meta data using a meta data store.
2) One then creates a record store off of the stored and (now) deserialized record meta data.
3) One takes a record whose type is specified using the same record meta data that was serialized in step 1 and tries to save it in the store created in step 2.
4) ILLEGAL ARGUMENT EXCEPTION

The problem here is that the descriptor of the record may have changed during the serialization and deserialization process. In particular, when we serialize `RecordMetaData` objects into `MetaData` proto messages, we strip out the extensions that specify indexes. Doing this simplifies our serialization process when it comes to how indexes are serialized and avoids issues that might arise from someone deleting a record that was specified with the extensions (and a few other edge cases), but it also means that this problem can happen because we check that the record type of records we try and serialize is within the record meta data of the store before we try and serialize it. We could loosen the rule and simply require that the *name* matches, and this would all work, but it would also create potential problems if people did weird things with their metadata that we don't check.

For now, this sterling bit of code works around the issue by serializing and then deserializing the message:
```
 Message recreatedRecord = DynamicMessage.parseFrom(
      recordStore.getRecordMetaData()
          .getRecordType(record.getDescriptorForType.getName()).getDescriptor(),
      record.toByteString());
```
Clients can use this today to get around the issue, but it's not pretty.

### PR DESCRIPTION
**Pull request by amouehsan**
(This supersedes #276 and applies Alec's comments)

Storing a record to a record store used to fail, if the record's meta-data was an evolved version of
the record store's meta-data shared using a meta-data store. This change should fix the issue by
passing the evolved meta-data to the builder.

Testing: ran FDBRecordStoreTest and RecordMetaDataBuilderTest

### CODE REVIEW

**Comment by alecgrieser** [comment]
Looks like a style check failed:

```
14:27:55 > Task :fdb-record-layer-core:checkstyleMain
14:27:55 [ant:checkstyle] [ERROR] /code/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:93:1: Duplicate import to line 91 - com.google.protobuf.Descriptors. [RedundantImport]
14:27:55 
14:27:55 > Task :fdb-record-layer-core:checkstyleMain FAILED
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 1]
```diff
@@ -374,10 +377,31 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+     * Sets the evolved file descriptor.
+     *
+     * WARNING: There is currently no validation done to make sure the evolved descriptor is compatible with the records
+     * descriptor included in the meta-data proto. This work is being tracked with Issue #85.
+     *
+     * @param evolvedFileDescriptor a file descriptor that contains updated record types
+     * @return this builder
+     */
+    @Nonnull
+    public RecordMetaDataBuilder setEvolvedFileDescriptor(@Nullable Descriptors.FileDescriptor evolvedFileDescriptor) {
```
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Hm, what about "local"? That is to say that it's useful if you have a locally generated file descriptor that is distinct from the record descriptor from some other source (which is given to it in `setRecords`)?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 2]
```diff
@@ -484,7 +508,7 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
         }
     }
 
-    private Descriptors.Descriptor initRecordTypes(boolean processExtensionOptions) {
+    private Descriptors.Descriptor initRecordTypes(@Nullable RecordMetaData evolvedRecordMetaData, boolean processExtensionOptions) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Discussion copied from #276:

@alecgrieser:

> I think generated the record meta-data like this is a little too heavy weight. If I'm reading the code correctly, the reason for passing it here (rather than just passing the evolved descriptor) is to get the union descriptor. Would it be cleaner to refactor that code out of this method, and then this method only needs the evolved descriptor (and not the full meta-data)?

@amouehsan:

> It's also used for record types. The filedescriptor only gives a list of descriptors, not a map of them. I was initially using a RecordMetaDataBuilder, but while they are not very different, this felt more natural. I can create the builder / metadata inside this method if you prefer so.

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I still feel like creating the record meta-data from the evolved descriptor is too heavy weight just to get (1) the union descriptor message and (2) the map from record type names to record types (especially as all that is needed from the record type is the descriptor.

I think once you've extracted the union descriptor, you should be able to extract a mapping from type names to descriptors from that. (And if the type is missing in the union descriptor, that it's own error.)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 3]
```diff
@@ -214,8 +214,14 @@ public void setMaintainHistory(boolean maintainHistory) {
 
     @Nonnull
     protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProto, boolean validate) {
+        return buildMetaData(metaDataProto, validate, null);
+    }
+
+    @Nonnull
+    protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProto, boolean validate, @Nullable Descriptors.FileDescriptor evolvedDescriptor) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Discussion copied from #276:

@alecgrieser:
> I'm going back and forth in my head whether the evolved descriptor should be a member of the `FDBMetaDataStore` or a parameter like this.
> 
> It kind of seems to me is that what we need is either an `FDBMetaDataStore` provider or builder. (We might want a builder anyway. If you'll notice, there is not a way of specifying both a `KeySpacePath` and a (non-null) `MetaDataCache` to this class.) I think you would want to be able to specify the `evolvedDescriptor` and maybe the seed meta-data as well. I think that would be necessary to re-use the same object across multiple `FDBRecordStore` instances. (This is analogous to the problems that we ran into with the `KeySpacePath`.)
> 
> @MMcM, do you have thoughts on this?

@amouehsan:

> Yeah I noticed that, while working on the cache. I like the idea of making it a member. It already has dependencies / setDependencies too.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 4]
```diff
@@ -2870,6 +2874,12 @@ public FDBMetaDataStore getMetaDataStore() {
             return metaDataStore;
         }
 
+        @Nonnull
+        public Builder setEvolvedMetaDataFileDescriptor(@Nullable Descriptors.FileDescriptor evolvedMetaDataFileDescriptor) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: This method should probably be added to `BaseBuilder` as well.

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: It also looks like the `evolvedMetaDataFileDescriptor` is not used within this file (i.e., it isn't passed to the meta-data builder). There should probably be a test somewhere that would have caught this.

**Comment by alecgrieser** [comment]
I think I copied over all of the discussion from #276 that I think is still relevant for this PR, so hopefully, we don't need to consult that one any more.

**Comment by alecgrieser** [comment]
Oh, and this should also update the release notes with this change.

**Comment by amouehsan** [comment]
> It looks like those tests aren't here. Did they not get pushed?

I haven't added them yet. Working on them now.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 2 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I may be wrong, but I think the union descriptor only has a subset of record types; I.e., not all record types are necessarily present in the union. Assuming this is true, if we do not want to create a builder, we probably have two options: 
(a) Get the updated descriptors only if they are present in the union. Would this be correct? it would solve the problem in issue #3, but not sure if it's correct from the schema evolution point of view; some descriptors will come from the local descriptor and some will come from the proto.
(b) We could scan the list of message types in the evolved file descriptor once, and create a map. Let me give the second a shot.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 5]
```diff
@@ -374,10 +377,31 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+        }
         loadFromFileDescriptor(fileDescriptor, processExtensionOptions);
         return this;
     }
 
+    /**
+     * Sets the evolved file descriptor.
+     *
+     * WARNING: There is currently no validation done to make sure the evolved descriptor is compatible with the records
+     * descriptor included in the meta-data proto. This work is being tracked with Issue #85.
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: The way things stand now, it's disallowed to pass in evolvedFileDescriptor before setRecords(FileDescriptor). I couldn't think of any plausible use case for allowing it. Do you have one in mind?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 4 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: Hmm, interesting. FDBRecordStoreTest.open is the test that should have caught it. I debugged it step by step now, and with evolvedMetaDataFileDescriptor = null it still passes without hitting issue #3. Let me test it on top of tree master.

Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: I see, the test passes because of the metaDataStore.saveAndSetCurrent() call that happens right before open/uncheckedOpen calls. getRecordMetaDataAsync will return the metadata store's pre-computed recordMetaData. I will add more tests to cover this.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I'm using local for now, I will refactor it later if we decide to use something else.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 2 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: OK, (a) doesn't seem correct to me. Also,  I gave (b) a shot but it is not going to work if we want to support this:

> A record type is moved from the descriptor to being in an imported file in the evolved descriptor. Then the record should be present (using the imported file) in the new meta-data.

The record types are not in the messageTypes list, and we need to fish it from the imported files.

Extracting the descriptors from the union descriptor without verifying that the record type is already known, does not look right to me either. 

To fetch all of the record types defined in the local file descriptor, we may need to do most of the heavy work that the builder does. Hence, IMO, the cleanest way of doing this is to build the builder.

**Comment by amouehsan** [comment]
Few tests are failing with NullPointerException. I'm working into it now.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 6]
```diff
@@ -374,10 +378,41 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
 
+    /**
+     * Sets the local file descriptor.
+     *
+     * A local meta-data file descriptor may contain newer versions of record types or indexes that follows the
+     *
+     * This method is handy when two record meta-data are compatible (i.e., they follow
+     * <a href="https://foundationdb.github.io/fdb-record-layer/SchemaEvolution.html">Record Layer guidelines on schema evolution</a>),
+     * but their descriptors are not equal; e.g., a statically-generated proto and its serialized version that's stored
+     * in a meta-data store. A record store created off of the meta-data store may not be able to store a record created
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I think "meta-data store" should link to the `FDBMetaDataStore` class.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 7]
```diff
@@ -374,10 +378,41 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+     * by the statically-generated proto file because of descriptors mismatch. Using this method, the builder can use
+     * the correct version of the descriptor that the record was created with.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]:
```suggestion
     * the same version of the descriptor as the record.
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 8]
```diff
@@ -374,10 +378,41 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+     *
+     * WARNING: There is currently no validation done to make sure the local descriptor is compatible with the records
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Needs a paragraph tag to render correctly. Also, "records" to "record's" or "record".

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 9]
```diff
@@ -535,6 +575,11 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
         return union;
     }
 
+    private boolean isImported(@Nonnull Descriptors.Descriptor descriptor) {
+        return !recordsDescriptor.getMessageTypes().stream()
+                .map(Descriptors.Descriptor::getName).filter(descriptor.getName()::equals).findFirst().isPresent();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: A previous version checked the message descriptor for pointer equality with one of the two file descriptors (either the local one or the one from the proto). I thought that was sufficient; why was this changed?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 10]
```diff
@@ -556,17 +601,16 @@ private void fillUnionFields(Descriptors.Descriptor union, boolean processExtens
...
                 }
 
-                if (descriptor.getFile() != recordsDescriptor) {
-                    // An imported record type.
+                if (isImported(descriptor)) {
+                    // Record type is imported or it used to be imported but it's not part of the local descriptor
                     RecordTypeBuilder recordType = new RecordTypeBuilder(descriptor);
                     if (recordTypes.putIfAbsent(recordType.getName(), recordType) != null) {
-                        throw new MetaDataException("There is already a record type named" + recordType.getName());
+                        throw new MetaDataException("already exists");
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I think the old error message was better.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 11]
```diff
@@ -234,7 +241,17 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
      * @return a future that completes when the save is done
      */
     public CompletableFuture<Void> saveAndSetCurrent(@Nonnull RecordMetaDataProto.MetaData metaDataProto) {
-        RecordMetaData validatedMetaData = buildMetaData(metaDataProto, true);
+        return saveAndSetCurrent(metaDataProto, null);
+    }
+
+    /**
+     * Build meta-data to use from Protobuf and save.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Might be worth including a link to the `setLocalFileDescriptor` method in `RecordMetaDataBuilder` and including something briefly about what a "local file descriptor" is, because that isn't necessarily obvious to a user who arrives at this function.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 12]
```diff
@@ -319,13 +336,25 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
      */
     @Nonnull
     public CompletableFuture<Void> preloadMetaData(@Nullable RecordMetaDataProvider metaDataProvider) {
+        return preloadMetaData(metaDataProvider, null);
+    }
+
+    /**
+     * Prepare a meta-data store for use by loading any existing {@link RecordMetaData} or storing an initial
+     * seed from the given provider.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Same comment about linking to `setLocalFileDescriptor` or something along those lines.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 13]
```diff
@@ -183,6 +183,9 @@
     @Nonnull
     protected final RecordMetaDataProvider metaDataProvider;
 
+    @Nullable
+    protected final Descriptors.FileDescriptor localMetaDataFileDescriptor;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: Why does the record store need this? Isn't this included in the `RecordType` information in the `RecordMetaData`?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 14]
```diff
@@ -2883,6 +2891,19 @@ public Builder setMetaDataStore(@Nullable FDBMetaDataStore metaDataStore) {
...
+        @Nullable
+        public Descriptors.FileDescriptor getLocalMetaDataFileDescriptor() {
+            return localMetaDataFileDescriptor;
+        }
+
+        @Override
+        @Nonnull
+        public Builder setLocalMetaDataFileDescriptor(@Nullable Descriptors.FileDescriptor localMetaDataFileDescriptor) {
+            this.localMetaDataFileDescriptor = localMetaDataFileDescriptor;
+            return this;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: The `localMetaDataFileDescriptor` still isn't being used to construct the `RecordMetaData` when using an `FDBMetaDataStore`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 15]
```diff
@@ -374,10 +378,41 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
         if (recordsDescriptor != null) {
             throw new MetaDataException("Records already set.");
         }
+        if (localFileDescriptor != null || !explicitDependencies.isEmpty()) {
+            throw new MetaDataException("Invalid arguments set.");
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java [hunk 16]
```diff
@@ -1511,6 +1512,24 @@ default int getPipelineSize(@Nonnull PipelineOperation pipelineOperation) {
         @Nonnull
         BaseBuilder<M, R> setMetaDataStore(@Nullable FDBMetaDataStore metaDataStore);
 
+        /**
+         * Set the local version of the record meta-data file descriptor. Users may have a local meta-data file descriptor
+         * containing a newer version of record types or indexes that follows the
+         * <a href="https://foundationdb.github.io/fdb-record-layer/SchemaEvolution.html">Record Layer guidelines on schema evolution</a>.
+         * This will only be used if {@link #setMetaDataProvider} and {@link #setMetaDataStore} are also called.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java]: I think it's reasonable to only use this if `setMetaDataStore` is also called. I think requiring the user *also* set `setMetaDataProvider` is unnecessary (as that just provides a seed meta-data in the case where `MetaDataStore` is set).

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 17]
```diff
@@ -224,4 +227,58 @@ public void badUnionFields() {
...
+                .addDependency(TestRecords2Proto.getDescriptor())
+                .setRecords(serializedLocalMetaData);
+        assertNotNull(localMetaDataBuilder.getRecordType("MyLongRecord"));
+        RecordMetaData localMetaData = localMetaDataBuilder.build();
+
+        // Create a new builder of the original meta-data
+        RecordMetaDataBuilder newMetaDataBuilder = RecordMetaData.newBuilder()
+                .setLocalFileDescriptor(localMetaData.getRecordsDescriptor())
+                .setRecords(originalMetaData);
+        Throwable t = assertThrows(MetaDataException.class, () ->
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: I think the lhs can be a `MetaDataException` instead of a `Throwable`.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 18]
```diff
@@ -224,4 +227,58 @@ public void badUnionFields() {
...
+        RecordMetaDataProto.MetaData.Builder serializedLocalMetaDataBuilder = RecordMetaDataProto.MetaData.newBuilder()
+                .setRecords(originalMetaData.getRecords());
+        serializedLocalMetaDataBuilder.addDependencies(TestRecords2Proto.getDescriptor().toProto());
+        serializedLocalMetaDataBuilder.addRecordTypes(serializedLocalMetaDataBuilder
+                                                            .addRecordTypesBuilder()
+                                                            .setName("MyLongRecord").build());
+        serializedLocalMetaDataBuilder.setRecords(serializedLocalMetaDataBuilder
+                                                            .getRecordsBuilder()
+                                                            .addMessageType(TestRecords2Proto.MyLongRecord.getDescriptor().toProto())
+                                                            .build());
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: The `MyLongRecord` record type is not being added to the meta-data's union descriptor, which means that the new meta-data is malformed. That's a fine thing to test, but we should also test that it actually works when everything is updated correctly.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 19]
```diff
@@ -224,4 +227,58 @@ public void badUnionFields() {
...
+        assertEquals(newMetaData.toProto(null), originalMetaData);
+        assertEquals(newMetaData.getUnionDescriptor(), localMetaData.getUnionDescriptor());
+
+        // Record type moved from being imported to being present in the local descriptor
+        RecordMetaDataProto.MetaData previouslyImportedMetaData = RecordMetaData.build(TestRecordsImportProto.getDescriptor()).toProto(null);
+        RecordMetaDataBuilder nowFlatMetaData = RecordMetaData.newBuilder()
+                .setLocalFileDescriptor(TestRecordsImportFlatProto.getDescriptor())
+                .setRecords(previouslyImportedMetaData);
+        assertNotNull(nowFlatMetaData.getRecordType("MySimpleRecord"));
+        assertNotNull(nowFlatMetaData.getRecordType("MyLongRecord"));
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: It should also verify that the file descriptor of the record type is the expected descriptor.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 20]
```diff
@@ -224,4 +227,58 @@ public void badUnionFields() {
...
+
+        // Record type moved from the descriptor to being in an imported file
+        RecordMetaDataProto.MetaData previouslyFlatMetaData = RecordMetaData.build(TestRecordsImportFlatProto.getDescriptor()).toProto(null);
+        RecordMetaDataBuilder nowImportedMetaData = RecordMetaData.newBuilder()
+                .setLocalFileDescriptor(TestRecordsImportProto.getDescriptor())
+                .setRecords(previouslyFlatMetaData);
+        assertNotNull(nowImportedMetaData.getRecordType("MySimpleRecord"));
+        assertNotNull(nowImportedMetaData.getRecordType("MyLongRecord"));
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Same comment about verifying the file descriptor

File: fdb-record-layer-core/src/test/proto/test_records_chained_2.proto [hunk 21]
```diff
@@ -1,5 +1,5 @@
 /*
- * test_records_import.proto
+ * test_records_chained.proto
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_chained_2.proto]: should be `test_records_chained_2.proto`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 9 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Because it breaks when a record type used to be imported but it's moved to the local file descriptor. Hence, the record type will not be a message type in recordsDescriptor but since it is a message type in the local descriptor, the files will match.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java (hunk 18 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: How do you add it to the union dynamically?

Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: added this statically.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 13 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: I proposed adding it to the record store builder, but I don't think it should be in the record store itself. I think on the builders, it should be explicitly set (as it was before), though I can kind of get behind using the record meta-data if possible.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java (hunk 16 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java]: That wasn't necessarily my suggestion.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Maybe I'm missing something.

By contract, all record types *must* be defined in the union descriptor (until such time as we decide we generate the union descriptor from the records, but we're not there yet). So if you look at all record types defined the records descriptor's union descriptor, they should each exist in the *local* file descriptor's union descriptor (though they may be imported in one descriptor or the other).

> Extracting the descriptors from the union descriptor without verifying that the record type is already known, does not look right to me either.

This is essentially what the logic to handle importing records from other files is already doing, right?

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 22]
```diff
@@ -224,4 +228,70 @@ public void badUnionFields() {
...
+        assertEquals(nowImportedMetaData.getRecordType("MySimpleRecord").getDescriptor(), TestRecords1Proto.MySimpleRecord.getDescriptor());
+        assertNotNull(nowImportedMetaData.getRecordType("MyLongRecord"));
+        assertEquals(nowImportedMetaData.getRecordType("MyLongRecord").getDescriptor(), TestRecords2Proto.MyLongRecord.getDescriptor());
+
+        // Evolve the local file descriptor by adding a record type to the union
+        RecordMetaDataBuilder evolvedMetaDataBuilder = RecordMetaData.newBuilder()
+                .setLocalFileDescriptor(TestRecords1EvolvedProto.getDescriptor())
+                .setRecords(originalMetaData);
+        assertNotNull(evolvedMetaDataBuilder.getRecordType("AnotherRecord"));
+        assertEquals(evolvedMetaDataBuilder.getUnionDescriptor(), TestRecords1EvolvedProto.RecordTypeUnion.getDescriptor());
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Right, but this is coming from the union now. Probably we should sync up on this. If the union descriptor is taken from the evolved file descriptor, then its record types will come with it.

File: fdb-record-layer-core/src/test/proto/test_records_chained_2.proto [hunk 23]
```diff
@@ -1,5 +1,5 @@
 /*
- * test_records_import.proto
+ * test_records_chained2.proto
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_chained_2.proto]: sure, lets see if I finally can get this right :)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 24]
```diff
@@ -319,13 +342,33 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
...
+     * See {@link RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)} for more information.
+     *
+     * @param metaDataProvider a provider for a seed meta-data to be used when this store is empty
+     * @param localFileDescriptor the file descriptor of the local meta-data
+     * @return a future that is complete when this store is ready for use
+     */
+    @Nonnull
+    public CompletableFuture<Void> preloadMetaData(@Nullable RecordMetaDataProvider metaDataProvider, @Nullable Descriptors.FileDescriptor localFileDescriptor) {
         // Must exist in store if don't have a separate seed meta-data.
         return getRecordMetaDataAsync(metaDataProvider == null)
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: buildMetaData only has two call sites, both in loadAndSetCurrent that's only called by getRecordMetaDataAsync. It's now passed down to buildMetaData.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 2 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Iterated thru the list of message types and union fields, as a superset of all record types. done.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 13 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: dropped it.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java (hunk 16 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java]: Have dropped the method.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 25]
```diff
@@ -319,13 +367,33 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
      */
     @Nonnull
     public CompletableFuture<Void> preloadMetaData(@Nullable RecordMetaDataProvider metaDataProvider) {
+        Descriptors.FileDescriptor localFileDescriptor = metaDataProvider == null ? null :
+                                                                                    metaDataProvider.getRecordMetaData().getRecordsDescriptor();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Hm, I think this is a...sensible enough default. It kind of assumes that getting the meta-data from the seed provider is cheap, but maybe that's a fine enough assumption.

As it is, this is the *only* way to specify a seed descriptor from an `FDBRecordStore` builder, which I don't think we want.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 26]
```diff
@@ -374,10 +378,94 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+        for (Descriptors.Descriptor descriptor : localFileDescriptor.getMessageTypes()) {
+            RecordMetaDataOptionsProto.RecordTypeOptions recordTypeOptions = descriptor.getOptions()
+                    .getExtension(RecordMetaDataOptionsProto.record);
+            if (recordTypeOptions != null) {
+                switch (recordTypeOptions.getUsage()) {
+                    case UNION:
+                        if (union != null) {
+                            throw new MetaDataException("Only one union descriptor is allowed");
+                        }
+                        localRecordTypes.put("RecordTypeUnion", descriptor); // Adding this to access the union descriptor conveniently
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java [hunk 27]
```diff
@@ -1867,19 +1861,15 @@ public void open() throws Exception {
             assertEquals(version, recordStore.getRecordMetaData().getVersion());
 
             metaDataBuilder.addIndex("MySimpleRecord", newIndex);
-            metaDataStore.saveAndSetCurrent(metaDataBuilder.getRecordMetaData().toProto()).join();
+            metaDataStore.saveAndSetCurrent(metaDataBuilder.getRecordMetaData().toProto(), TestRecords1Proto.getDescriptor()).join();
             recordStore = FDBRecordStore.newBuilder().setContext(context).setSubspace(expectedSubspace)
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java]: Sure I can do that.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 28]
```diff
@@ -224,4 +228,73 @@ public void badUnionFields() {
...
+                                                            .build());
+        RecordMetaDataProto.MetaData serializedLocalMetaData = serializedLocalMetaDataBuilder.build();
+        assertTrue(serializedLocalMetaData.getRecordTypesList().stream()
+                .map(RecordMetaDataProto.RecordType::getName)
+                .filter("MyLongRecord"::equals).findAny().isPresent());
+        RecordMetaDataBuilder localMetaDataBuilder = RecordMetaData.newBuilder()
+                .addDependency(TestRecords2Proto.getDescriptor())
+                .setRecords(serializedLocalMetaData);
+        assertNotNull(localMetaDataBuilder.getRecordType("MyLongRecord"));
+        RecordMetaData localMetaData = localMetaDataBuilder.build();
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Yeah, good catch. build(true) could have found it, probably. Adding record types by taking the union as base, exposed it too. Not sure if this test case is worth it. I will drop it.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 29]
```diff
@@ -520,75 +608,93 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
             } else {
                 // The preferred field is the last one, except if there is one whose name matches.
-                unionFields.compute(descriptor, (d, f) -> f != null && f.getName().equals("_" + d.getName()) ? f : unionField);
+                unionFields.compute(descriptor, (d, f) -> f != null && f.getName().equals("_" + d.getName()) ? f : adjustedUnionField);
             }
         }
     }
 
-    private void protoFieldOptions(RecordTypeBuilder recordType, Descriptors.Descriptor descriptor) {
+    private Descriptors.FieldDescriptor adjustUnionField(@Nonnull Descriptors.FieldDescriptor unionField) {
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: done

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 30]
```diff
@@ -374,10 +378,94 @@ public RecordMetaDataBuilder setRecords(@Nonnull Descriptors.FileDescriptor file
...
+    public RecordMetaDataBuilder setLocalFileDescriptor(@Nonnull Descriptors.FileDescriptor localFileDescriptor) {
+        if (recordsDescriptor != null) {
+            throw new MetaDataException("Records already set.");
+        }
+        this.localFileDescriptor = localFileDescriptor;
+        fetchLocalRecordTypes();
+        return this;
+    }
+
+    private void fetchLocalRecordTypes() {
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Most of it done. I will move validation to validateRecords().

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 9 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: done.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 31]
```diff
@@ -302,7 +350,7 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
                             recordMetaData = null;
                         }
                     }
-                    return loadAndSetCurrent(true, currentVersion).thenApply(ignore -> {
+                    return loadAndSetCurrent(localMetaDataFileDescriptor,true, currentVersion).thenApply(ignore -> {
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: sure.

**Comment by amouehsan** [comment]
The current build failure seems unrelated to the changes. It's running out of space (@alecgrieser @AlvinMooreSr):

16:29:09 Running Prebuild steps
16:29:11 FATAL: Unable to produce a script file
16:29:11 java.io.IOException: No space left on device
16:29:11 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
16:29:11 	at java.io.File.createTempFile(File.java:2024)
... 
16:29:14 Recording test results
16:29:14 Sending e-mails to: alvinm@apple.com alloc@apple.com

**Comment by AlvinMooreSr** [comment]
test this please

**Comment by AlvinMooreSr** [comment]
@amouehsan Space has been freed on the CI server but the PRBs still seem to be failing due to test failures.
248 tests completed, 4 failed
18:40:03 > Task :fdb-record-layer-core:test FAILED

**Comment by amouehsan** [comment]
> @amouehsan Space has been freed on the CI server but the PRBs still seem to be failing due to test failures.
> 248 tests completed, 4 failed
> 18:40:03 > Task :fdb-record-layer-core:test FAILED

@AlvinMooreSr thank you. Yeah, it looks like the my validator piece is failing on some of the proto files. I'll take a look:

18:40:03 com.apple.foundationdb.record.metadata.MetaDataValidatorTest > badPrimaryKeyType() FAILED
18:40:03     com.apple.foundationdb.record.metadata.MetaDataException: Record message type ReviewerStats must be a union field.
18:40:03         at com.apple.foundationdb.record.RecordMetaDataBuilder.validateUnion(RecordMetaDataBuilder.java:610)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 32]
```diff
@@ -266,8 +310,12 @@ protected RecordMetaData buildMetaData(RecordMetaDataProto.MetaData metaDataProt
         return instrument(FDBStoreTimer.Events.SAVE_META_DATA, future);
     }
 
-    // TODO: FDBMetadataStore should assign index keys based on a counter (https://github.com/FoundationDB/fdb-record-layer/issues/11)
     public CompletableFuture<RecordMetaData> getRecordMetaDataAsync(boolean errorIfMissing) {
+        return getRecordMetaDataAsync(null, errorIfMissing);
+    }
+
+    // TODO: FDBMetadataStore should assign index keys based on a counter (https://github.com/FoundationDB/fdb-record-layer/issues/11)
+    public CompletableFuture<RecordMetaData> getRecordMetaDataAsync(@Nullable Descriptors.FileDescriptor localMetaDataFileDescriptor, boolean errorIfMissing) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: This seems like it also should but the `localMetaDataFileDescriptor` at the end (and it should use the same parameter name as whatever is decided for the other methods).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 33]
```diff
@@ -3039,12 +3049,23 @@ private RecordMetaDataProvider getMetaDataProviderForBuild() {
...
             }
         }
 
+        @Nullable
+        public Descriptors.FileDescriptor getLocalMetaDataFileDescriptor() {
+            return localMetaDataFileDescriptor;
+        }
+
+        public void setLocalMetaDataFileDescriptor(@Nullable Descriptors.FileDescriptor localMetaDataFileDescriptor) {
+            this.localMetaDataFileDescriptor = localMetaDataFileDescriptor;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: The getter and setter for `localMetaDataFileDescriptor` should be moved to live next to the other getters and setters; the setter should return `this` to match the builder pattern; and then I believe the `BaseBuilder` implementations need versions of the setter in order to override the return type (until Java implements [`SELF_TYPE`](https://dijkstra.eecs.umich.edu/eecs483/cool-manual/node8.html)).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 34]
```diff
@@ -484,111 +576,116 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
-    private void protoFieldOptions(RecordTypeBuilder recordType, Descriptors.Descriptor descriptor) {
+    private void processRecordType(@Nonnull Descriptors.FieldDescriptor unionField, boolean processExtensionOptions) {
+        Descriptors.Descriptor descriptor = unionField.getMessageType();
+        RecordMetaDataOptionsProto.RecordTypeOptions recordTypeOptions = descriptor.getOptions()
+                .getExtension(RecordMetaDataOptionsProto.record);
+        if (recordTypeOptions != null &&
+            recordTypeOptions.getUsage() != RecordMetaDataOptionsProto.RecordTypeOptions.Usage.RECORD) {
+            throw new MetaDataException("Union field " + unionField.getName() +
+                                        " has type " + descriptor.getName() +
+                                        " which is not a record");
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: right. Also to clarify: the validation done in validateUnion is the other way around. It verifies that all RECORD message types defined in this proto are also present in the union. As you also mentioned, here we are checking if a union member is a RECORD message type, which effectively double checks the message types that are present in the file in addition to checking the message types that are imported. I think it may be cleaner and clearer to move this to validateUnion too. I'll add a comment and put it there. Thanks.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 35]
```diff
@@ -484,111 +576,116 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
+            protoFieldOptions(recordType);
+        }
+    }
+
+    @Nonnull
+    private Descriptors.FieldDescriptor adjustUnionField(@Nonnull Descriptors.FieldDescriptor unionField) {
+        if (localUnionDescriptor == null) {
+            return unionField;
+        }
+        return localUnionDescriptor.getFields().stream().filter(field -> unionField.getName().equals(field.getName())).findAny().get();
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: good point. thanks.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 36]
```diff
@@ -636,7 +733,7 @@ private void protoFieldOptions(RecordTypeBuilder recordType, Descriptors.Descrip
 
     @Nonnull
     public Descriptors.Descriptor getUnionDescriptor() {
-        return unionDescriptor;
+        return localUnionDescriptor == null ? unionDescriptor : localUnionDescriptor;
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Sure. We could also drop localFileDescriptor now.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 37]
```diff
@@ -124,14 +124,33 @@ public void setMaintainHistory(boolean maintainHistory) {
...
+     * mismatched descriptors. Using this method, the meta-data can use the same version of the descriptor as the record.
+     * See {@link RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)} for more information.
+     * </p>
+     *
+     * @param localMetaDataFileDescriptor local file descriptor of the record meta-data.
+     * @param checkCache {@code true} if the cache should be checked first
+     * @param currentVersion the version to load
+     * @return a future that completes with the Protobuf form of the meta-data
+     */
+    public CompletableFuture<RecordMetaDataProto.MetaData> loadAndSetCurrent(@Nullable Descriptors.FileDescriptor localMetaDataFileDescriptor, boolean checkCache, int currentVersion) {
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java (hunk 32 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 33 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: oh good catch! Thanks!

File: fdb-record-layer-core/src/test/proto/test_records_4.proto [hunk 38]
```diff
@@ -34,6 +34,7 @@ message RestaurantReviewer {
 }
 
 message ReviewerStats {
+  option (com.apple.foundationdb.record.record).usage = NESTED;
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_4.proto]: dropped this and the other occurrences. I was under impression all unmarked message types must be part of the union.

File: fdb-record-layer-core/src/test/proto/expression_tests.proto [hunk 39]
```diff
@@ -49,6 +49,7 @@ message NestedField {
 }
 
 message SubString {
+  option (com.apple.foundationdb.record.record).usage = NESTED;
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/expression_tests.proto]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 40]
```diff
@@ -484,111 +576,116 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
         }
-        if (union == null) {
-            throw new MetaDataException("Union descriptor is required");
-        }
-        fillUnionFields(union, processExtensionOptions);
-        return union;
     }
 
+    private static boolean unionHasMessageType(@Nonnull Descriptors.Descriptor unionDescriptor, @Nonnull Descriptors.Descriptor descriptor) {
+        return unionDescriptor.getFields().stream().filter(field -> descriptor.equals(field.getMessageType())).findAny().isPresent();
```
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Sure. Suppose someone has a "union descriptor" that looks like this:

```proto
message MalformedUnion {
    optional RecordTypeOne _RecordTypeOne = 1;
    optional int32 _NotAMessageType = 2;
}
```

Suppose then one calls this method with, say, a message type called `SomeMessageType`. Then when this is called, eventually the `SomeMessageType` descriptor will be compared for equality with `MalformedUnion.getDescriptor().findFieldByName("_NotAMessageType").getMessagteType()`...and that function throws an `UnsupportedOperationException`. Which, like, the union is malformed, but the error is way too leaky. (It should throw a `MetaDataException` complaining about having non-message type fields in the union which is already something that happens in `fillUnionFields`.) I think this validation should occur before this method is invoked in order to avoid that happening.

----

Also, taking a closer look at this method it should probably use pointer equality (rather than `.equals` equality) on the descriptors, and instead of `filter`ing and checking if `findAny` returns a present `Optional`, it should probably just call `anyMatch`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Doesn't it validate both ways in `validateUnion`? It validates that all `RECORD`s are in the union (after the `switch` statement currently) and that all `NESTED`s and `UNION`s are not in the union in their respective `switch` cases, if I'm reading it correctly.

I'm not sure `validateUnion` is the right place to put this (or, like, I'm not sure how I see how it's *better* there than here) if the idea is that it should be validating imported records as well.

[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: The first part is right. My point was: validateUnion only validates the message types defined in the original records descriptor. It does not check if ALL of the union fields (i.e., the imported message types) are RECORD types. This check is meant to do that. Moving it validateUnion makes sense, IMO, because it puts all major union-related validations together.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 40 above)
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: >  I think this validation should occur before this method is invoked in order to avoid that happening.

As it stands now, this will not happen, right? As you also said, not-message-type validation happens in fillUnionFields which is called before validateUnion. At this point, we're certain that all union fields are message types. I don't mind adding the check to here too, if that's the ask? 

> Also, taking a closer look at this method it should probably use pointer equality (rather than .equals equality) on the descriptors, and instead of filtering and checking if findAny returns a present Optional, it should probably just call anyMatch.

sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: Oh, I see; I think I misunderstood your comment.

I could see putting this check here or in `validateUnion` going either way in terms of cleanliness. Your call, I suppose.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 41]
```diff
@@ -484,111 +577,127 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
-                        continue;
+                        break;
+                    case UNION:
+                        // Already checked above that none of the union fields is UNION.
                     case NESTED:
-                        continue;
-                    case RECORD:
+                        // Already checked above that none of the union fields is NESTED.
+                    case UNSET:
+                        // Unset message types can appear in both union fields or as nested messages. Only possible issue
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]:
```suggestion
                        // Unset message types can appear in either union fields or as nested messages. The only possible issue
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 42]
```diff
@@ -484,111 +577,127 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
+                        // is the message type's name that might equal "RecordTypeUnion" and this is already checked above.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]:
```suggestion
                        // that is the message type's name might equal "RecordTypeUnion", and this is already checked above.
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 43]
```diff
@@ -484,111 +577,127 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
             }
         }
     }
 
-    private void protoFieldOptions(RecordTypeBuilder recordType, Descriptors.Descriptor descriptor) {
+    private void processRecordType(@Nonnull Descriptors.FieldDescriptor unionField, boolean processExtensionOptions) {
+        Descriptors.Descriptor descriptor = unionField.getMessageType();
+        RecordTypeBuilder recordType = new RecordTypeBuilder(descriptor);
+        if (recordTypes.putIfAbsent(recordType.getName(), recordType) != null) {
+            throw new MetaDataException("There is already a record type named" + recordType.getName());
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]:
```suggestion
            throw new MetaDataException("There is already a record type named " + recordType.getName());
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 44]
```diff
@@ -222,6 +226,7 @@ protected FDBRecordStore(@Nonnull FDBRecordContext context,
 
         this.omitUnsplitRecordSuffix = formatVersion < SAVE_UNSPLIT_WITH_SUFFIX_FORMAT_VERSION;
         this.preloadCache = CacheBuilder.<Tuple,FDBRawRecord>newBuilder().maximumSize(PRELOAD_CACHE_SIZE).build();
+        this.localMetaDataFileDescriptor = localMetaDataFileDescriptor;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: This should go next to the initialization of `metaDataProvider` in order to match the order in which the parameters are given in the constructor.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 45]
```diff
@@ -275,6 +280,15 @@ public RecordMetaDataProvider getMetaDataProvider() {
         return metaDataProvider;
     }
 
+    /**
+     * Get the local meta-data file descriptor.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: This should probably include a link to some other Javadoc that explains what the local meta-data file descriptor is useful for.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 46]
```diff
@@ -2979,6 +2998,19 @@ public Builder setPipelineSizer(@Nonnull PipelineSizer pipelineSizer) {
             return this;
         }
 
+        @Nullable
+        @Override
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: The order of `Nullable` and `Override` should be swapped to match the others in this file.

I don't think we have a consistent order of these things throughout our codebase, but I feel like they should at least match within a file.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 47]
```diff
@@ -2979,6 +2998,19 @@ public Builder setPipelineSizer(@Nonnull PipelineSizer pipelineSizer) {
...
+        public Descriptors.FileDescriptor getLocalMetaDataFileDescriptor() {
+            return localMetaDataFileDescriptor;
+        }
+
+        @Nonnull
+        @Override
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: Same comment here about annotation order.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 48]
```diff
@@ -87,11 +87,14 @@
 
     private static final Logger logger = LoggerFactory.getLogger(RecordMetaDataBuilder.class);
     private static final Descriptors.FileDescriptor[] emptyDependencyList = new Descriptors.FileDescriptor[0];
+    public static final String recordTypeUnionMessageName = "RecordTypeUnion";
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: this is already fixed, as it was apparently a PMD violation. I like DEFAULT_UNION_NAME.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 41 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 42 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 43 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 44 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 45 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 46 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: ok. sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 47 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: done.

**Comment by amouehsan** [comment]
> It doesn't look there are tests added to make sure that, say, if one marks a message type as a `RECORD` and then doesn't import it that one gets a validation error. I think you mentioned that there was some other issue relating to that, but I kind of feel like that should go in with this change (as it's testing what's being changed here). At the least, the issue should be linked somewhere.

Right I created a new issue for this (issue #348), but I can add this test now. 

Currently I'm trying to understand why proto3 keeps failing. It looks like after my changes, in proto3, the following code from FDBRecordStoreTest.java fails to parse the serialized metadata, complaining that the extensionRegistry is NULL:

```
            recordStore = FDBRecordStore.newBuilder().setContext(context).setKeySpacePath(path)
                    .setMetaDataStore(metaDataStore).setMetaDataProvider(origMetaData)
                    .open();
```

**Comment by amouehsan** [comment]
Alec's change requests are now pushed. proto3's checks have also passed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 49]
```diff
@@ -484,111 +577,127 @@ private static void validateRecords(@Nonnull Descriptors.FileDescriptor fileDesc
...
+                        break;
+                    case UNION:
+                        // Already checked above that none of the union fields is UNION.
                     case NESTED:
-                        continue;
-                    case RECORD:
+                        // Already checked above that none of the union fields is NESTED.
+                    case UNSET:
+                        // Unset message types can appear in either union fields or as nested messages. The only possible issue
+                        // that is the message type's name that might equal "RecordTypeUnion", is already checked above.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]:
```suggestion
                        // is that the message type's name that might equal "RecordTypeUnion", is already checked above.
```

Sorry, this was my bad (I messed up the order of a few words in a previous suggestion).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 50]
```diff
@@ -269,12 +274,22 @@ private boolean useOldVersionFormat() {
     /**
      * Get the provider for the record store's meta-data.
      * @return the meta-data source to use
+     * See {@link com.apple.foundationdb.record.RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)}.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]:
```suggestion
     * @see com.apple.foundationdb.record.RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)}
```

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: It also looks like this was applied to wrong getter (i.e., this should go on `getLocalMetaDataFileDescriptor` instead of `getMetaDataProvider`).

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 51]
```diff
@@ -224,4 +231,57 @@ public void badUnionFields() {
...
+        assertSame(evolvedMetaDataBuilder.build(true).getUnionDescriptor(), TestRecords1EvolvedProto.RecordTypeUnion.getDescriptor());
+    }
+
+    @Test
+    public void markedUnmarkedMessageTypes() {
+        RecordMetaDataBuilder builder = RecordMetaData.newBuilder().setRecords(TestRecordsMarkedUnmarkedProto.getDescriptor());
+        RecordMetaData recordMetaData = builder.build(true);
+        assertNotNull(recordMetaData.getRecordType("MyMarkedRecord"));
+        assertNotNull(recordMetaData.getRecordType("MyUnmarkedRecord1"));
+        assertNotNull(recordMetaData.getRecordType("MyUnmarkedRecord1"));
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Duplicate line

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java [hunk 52]
```diff
@@ -1898,6 +1887,18 @@ public void open() throws Exception {
...
 
+    @Nonnull
+    private FDBMetaDataStore createMetaDataStore(@Nonnull FDBRecordContext context, @Nonnull KeySpacePath metaDataPath, @Nonnull Subspace metaDataSubspace) {
+        FDBMetaDataStore metaDataStore = new FDBMetaDataStore(context, metaDataPath);
+        metaDataStore.setMaintainHistory(false);
+        assertEquals(metaDataSubspace, metaDataStore.getSubspace());
+        metaDataStore.setDependencies(new Descriptors.FileDescriptor[]{RecordMetaDataOptionsProto.getDescriptor()});
+        ExtensionRegistry extensionRegistry = ExtensionRegistry.newInstance();
+        RecordMetaDataOptionsProto.registerAllExtensions(extensionRegistry);
+        metaDataStore.setExtensionRegistry(extensionRegistry);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java]: I'm uncomfortable that the user has to set the `extensionRegistry` in an `FDBMetaDataStore` to avoid null pointer exceptions. I don't think this needs to be addressed with this PR necessarily, but we should have an issue (probably included as a subtask of #283) to track setting a default extension registry within  an `FDBMetaDataStore` to avoid every client having to do the same.

File: fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto [hunk 53]
```diff
@@ -0,0 +1,49 @@
+/*
+ * test_records_1.proto
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto]:
```suggestion
 * test_records_marked_unmarked.proto
```

File: fdb-record-layer-core/src/test/proto/test_records_two_unions.proto [hunk 54]
```diff
@@ -0,0 +1,39 @@
+/*
+ * test_records_1.proto
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_two_unions.proto]:
```suggestion
 * test_records_two_unions.proto
```

File: fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto [hunk 55]
```diff
@@ -0,0 +1,35 @@
+/*
+ * test_records_1.proto
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto]:
```suggestion
 * test_records_union_default_name.proto
```

File: fdb-record-layer-core/src/test/proto/test_records_two_unions.proto [hunk 56]
```diff
@@ -0,0 +1,39 @@
...
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_two_unions.proto]:
```suggestion
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
```

File: fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto [hunk 57]
```diff
@@ -0,0 +1,49 @@
...
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto]:
```suggestion
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
```

File: fdb-record-layer-core/src/test/proto/test_records_import_flat.proto [hunk 58]
```diff
@@ -0,0 +1,47 @@
+/*
+ * test_records_import_flat.proto
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_import_flat.proto]:
```suggestion
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
```

File: fdb-record-layer-core/src/test/proto/test_records_1_evolved.proto [hunk 59]
```diff
@@ -0,0 +1,56 @@
+/*
+ * test_records_1_evolved.proto
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_1_evolved.proto]:
```suggestion
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
```

File: fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto [hunk 60]
```diff
@@ -0,0 +1,35 @@
...
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto]:
```suggestion
 * Copyright 2015-2019 Apple Inc. and the FoundationDB project authors
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 49 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: np.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 50 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: my bad. fixed now.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java (hunk 51 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: dropped.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java (hunk 52 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java]: filed issue #352.

File: fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto (hunk 53 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto]: done.

File: fdb-record-layer-core/src/test/proto/test_records_two_unions.proto (hunk 54 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_two_unions.proto]: done.

File: fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto (hunk 55 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto]: done.

File: fdb-record-layer-core/src/test/proto/test_records_two_unions.proto (hunk 56 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_two_unions.proto]: done.

File: fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto (hunk 57 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto]: sure.

File: fdb-record-layer-core/src/test/proto/test_records_import_flat.proto (hunk 58 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_import_flat.proto]: sure.

File: fdb-record-layer-core/src/test/proto/test_records_1_evolved.proto (hunk 59 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_1_evolved.proto]: sure

File: fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto (hunk 60 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/test/proto/test_records_union_default_name.proto]: sure

**Comment by amouehsan** [comment]
> I think this could use the following tests:
> 
> * Include a `RECORD` in the protobuf file that is _not_ in the descriptor
> * Include a `NESTED` in the protobuf file that _is_ in the descriptor
> * Import a `NESTED` record and include it in the union descriptor
> 

Sure. done.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 61]
```diff
@@ -275,6 +280,16 @@ public RecordMetaDataProvider getMetaDataProvider() {
         return metaDataProvider;
     }
 
+    /**
+     * Get the local meta-data file descriptor.
+     * @return the local meta-data file descriptor
+     * See {@link com.apple.foundationdb.record.RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)}.
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 62]
```diff
@@ -908,7 +1017,7 @@ public RecordMetaData build() {
     @Nonnull
     public RecordMetaData build(boolean validate) {
         Map<String, RecordType> recordTypeBuilders = new HashMap<>();
-        RecordMetaData metaData = new RecordMetaData(recordsDescriptor, unionDescriptor, unionFields, recordTypeBuilders,
+        RecordMetaData metaData = new RecordMetaData(recordsDescriptor, getUnionDescriptor(), unionFields, recordTypeBuilders,
```
[the remark this answers is not in the document]
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: sure.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 63]
```diff
@@ -124,14 +124,33 @@ public void setMaintainHistory(boolean maintainHistory) {
...
+     * mismatched descriptors. Using this method, the meta-data can use the same version of the descriptor as the record.
+     * See {@link RecordMetaDataBuilder#setLocalFileDescriptor(Descriptors.FileDescriptor)} for more information.
+     * </p>
+     *
+     * @param checkCache {@code true} if the cache should be checked first
+     * @param currentVersion the version to load
+     * @param localFileDescriptor local file descriptor of the record meta-data.
+     * @return a future that completes with the Protobuf form of the meta-data
+     */
+    public CompletableFuture<RecordMetaDataProto.MetaData> loadAndSetCurrent(boolean checkCache, int currentVersion, @Nullable Descriptors.FileDescriptor localFileDescriptor) {
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: This doesn't quite feel right. I think the local file descriptor is a more intrinsic piece of state in the meta-data store, like the list of dependency file descriptors. So I'd expect it to have a similar lifetime.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 64]
```diff
@@ -2994,6 +3014,19 @@ public Builder setPipelineSizer(@Nonnull PipelineSizer pipelineSizer) {
...
+        @Override
+        @Nullable
+        public Descriptors.FileDescriptor getLocalMetaDataFileDescriptor() {
+            return localMetaDataFileDescriptor;
+        }
+
+        @Override
+        @Nonnull
+        public Builder setLocalMetaDataFileDescriptor(@Nullable Descriptors.FileDescriptor localMetaDataFileDescriptor) {
+            this.localMetaDataFileDescriptor = localMetaDataFileDescriptor;
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: I think it would be better if the meta-data store itself knew the local file descriptor so that all the record store only knew it. In fact, I'd rather the record store (and builder) only knew a meta-data provider. That requires some tweaking to the API around async and caching. But this will make it unnecessarily harder.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 65]
```diff
@@ -79,6 +79,9 @@
     private PendingCacheUpdate pendingCacheUpdate;
     private boolean maintainHistory = true;
 
+    @Nullable
+    private Descriptors.FileDescriptor localFileDescriptor;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: I think this would live more at home between the `dependencies` and the `extensionRegistry` member variable declarations given their parallel function. It definitely shouldn't have a blank line separating it from the other member variables.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 66]
```diff
@@ -100,6 +103,29 @@ public void setDependencies(@Nonnull Descriptors.FileDescriptor[] dependencies)
         this.dependencies = dependencies;
     }
 
+    @Nullable
+    public Descriptors.FileDescriptor getLocalFileDescriptor() {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: This should have a Javadoc description.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 67]
```diff
@@ -100,6 +103,29 @@ public void setDependencies(@Nonnull Descriptors.FileDescriptor[] dependencies)
...
+        return localFileDescriptor;
+    }
+
+
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Extra blank line

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 68]
```diff
@@ -100,6 +103,29 @@ public void setDependencies(@Nonnull Descriptors.FileDescriptor[] dependencies)
...
+    /**
+     * Set local meta-data file descriptor.
+     *
+     * <p>
+     * This can optionally take a local file descriptor. A record store created off of the meta-data store may not be
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: I think this verbiage about optionally taking a local file descriptor was taken from a previous version where this referred to using a `localFileDescriptor` as an optional parameter (such as that exists in Java). I think this paragraph works without the first sentence.

File: fdb-record-layer-core/src/main/proto/record_metadata_options.proto [hunk 69]
```diff
@@ -39,8 +39,9 @@ message RecordTypeOptions {
     RECORD = 1;
     UNION = 2;
     NESTED = 3;
+    UNSET = 4;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/proto/record_metadata_options.proto]: Sorry, this occurred to me later. I think if `UNSET` is set to `0` (which is legal for enum ordinals but not record field ordinals), then this behaves the same in proto2 and proto3 insofar as the default value is ordinal 0, and then setting it explicitly to 0 is the same as leaving it unset (which are exactly the semantics that proto3 expects). It might be nice to adopt the proto3 idiom while we're here.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataProtoTest.java [hunk 70]
```diff
@@ -300,8 +306,8 @@ public void versionstampIndexDeserialization() throws Exception {
                                                 .setField(scalarField("rec_no"))))));
 
         RecordMetaData metaData = RecordMetaData.newBuilder().addDependencies(BASE_DEPENDENCIES)
-                .setRecords(protoBuilder.build())
-                .getRecordMetaData();
+                .setRecords(protoBuilder.build(), true)
+                .build(false);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataProtoTest.java]: I don't think we want the extension options processed here, but I do think we want the meta-data validated now that #354 is in.

File: fdb-record-layer-core/src/test/proto/test_records_text.proto [hunk 71]
```diff
@@ -34,7 +34,7 @@ message SimpleDocument {
 
 message ComplexDocument {
     optional int64 group = 1;
-    optional int64 doc_id = 2;
+    optional int64 doc_id = 2 [(field).primary_key = true];
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_text.proto]: The primary key for a `ComplexDocument` should be `concat("group", "doc_id")`. I think this should mention that the PK is set in the test, unless there is one that's missing it.

File: fdb-record-layer-core/src/test/proto/test_records_union_missing_record.proto [hunk 72]
```diff
@@ -0,0 +1,43 @@
...
+  option (com.apple.foundationdb.record.record).usage = RECORD;
+  optional int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+
+message MyUsedRecord {
+  required int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+message RecordTypeUnion {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_union_missing_record.proto]: Should have a blank line after `MyUsedRecord`'s definition.

File: fdb-record-layer-core/src/test/proto/test_records_union_with_imported_nested.proto [hunk 73]
```diff
@@ -0,0 +1,39 @@
...
+import "record_metadata_options.proto";
+import "test_records_4.proto";
+
+option (schema).store_record_versions = true;
+
+message MyUsedRecord {
+  required int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+message RecordTypeUnion {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_union_with_imported_nested.proto]: Same need for a blank line.

File: fdb-record-layer-core/src/test/proto/test_records_union_with_nested.proto [hunk 74]
```diff
@@ -0,0 +1,44 @@
...
+  option (com.apple.foundationdb.record.record).usage = NESTED;
+  optional int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+
+message MyUsedRecord {
+  required int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+message RecordTypeUnion {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_union_with_nested.proto]: Same need for a blank line.

File: fdb-record-layer-core/src/test/proto/expression_tests.proto [hunk 75]
```diff
@@ -75,6 +75,8 @@ message Customer {
   }
 }
 
+// Note that none of the message types in this proto file has a primary key. Records are instantiated and expression evaluates
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/expression_tests.proto]:
```suggestion
// Note that none of the message types in this proto file have a primary key. Records are instantiated and expressions are evaluated
```

File: fdb-record-layer-core/src/test/proto/expression_tests.proto [hunk 76]
```diff
@@ -75,6 +75,8 @@ message Customer {
...
+// against those but the metadata is never built. RecordMetaDataBuilder will fail if we attempt to build them.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/expression_tests.proto]:
```suggestion
// against those records, but the meta-data is never built. RecordMetaDataBuilder will fail if we attempt to build them.
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 77]
```diff
@@ -919,14 +1024,9 @@ public RecordMetaData build(boolean validate) {
...
-                    if (logger.isWarnEnabled()) {
-                        logger.warn(KeyValueLogMessage.of("Created Index indexes a record type without a primary key",
-                                "record_type", recordTypeBuilder.getName(),
-                                "indexName", index.getName()));
-                    }
-                    indexes.remove(index.getName());
-                }
+                throw new MetaDataException("Record type " +
+                                            recordTypeBuilder.getName() +
+                                            " must have a primary key");
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I see there were a bunch of tests changed to make it so that we handle the fact that things might not have a primary key. Are there any tests were we validate that a record type without a primary key throws an error?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java (hunk 3 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: It looks like this became a member variable eventually, which sounds like a defensible decision to me.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 78]
```diff
@@ -100,6 +102,31 @@ public void setDependencies(@Nonnull Descriptors.FileDescriptor[] dependencies)
         this.dependencies = dependencies;
     }
 
+    /**
+     * Get local meta-data file descriptor.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]:
```suggestion
     * Gets the local meta-data file descriptor.
```

It probably could use a link to `RecordMetaDataBuilder.setLocalFileDescriptor`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 79]
```diff
@@ -100,6 +102,31 @@ public void setDependencies(@Nonnull Descriptors.FileDescriptor[] dependencies)
...
+     */
+    @Nullable
+    public Descriptors.FileDescriptor getLocalFileDescriptor() {
+        return localFileDescriptor;
+    }
+
+    /**
+     * Set local meta-data file descriptor.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]:
```suggestion
     * Sets the local meta-data file descriptor.
```

Sorry, should have picked up this one earlier.

File: fdb-record-layer-core/src/test/proto/expression_tests.proto [hunk 80]
```diff
@@ -75,6 +75,8 @@ message Customer {
   }
 }
 
+// Note that none of the message types in this proto file has a primary key. Records are instantiated and expressions are evaluated
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/expression_tests.proto]:
```suggestion
// Note that none of the message types in this proto file have a primary key. Records are instantiated and expressions are evaluated
```

File: fdb-record-layer-core/src/main/proto/record_metadata_options.proto (hunk 69 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/proto/record_metadata_options.proto]: Yeah, that had been my suggestion. Looks good now.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java (hunk 78 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: I believe the rest of the getters/setters in this file do not have an 's' at the end of Get and Set.  I prefer to continue following the way others are. Sure, added the link.

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: Yeah, I can live without the "s". It should have a "the", though.

Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: that's fixed. thank you for the review.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 81]
```diff
@@ -290,20 +289,62 @@ private void loadFromProto(@Nonnull RecordMetaDataProto.MetaData metaDataProto,
...
+    private Descriptors.Descriptor initRecordTypes(@Nonnull Descriptors.FileDescriptor fileDescriptor, boolean processExtensionOptions) {
+        Descriptors.Descriptor unionDescriptor = fetchUnionDescriptor(fileDescriptor);
+        validateRecords(fileDescriptor, unionDescriptor);
+        fillUnionFields(unionDescriptor, processExtensionOptions);
+        return localUnionDescriptor == null ? unionDescriptor : localUnionDescriptor;
+    }
+
+    @Nonnull
+    private Descriptors.Descriptor fetchUnionDescriptor(@Nonnull Descriptors.FileDescriptor fileDescriptor) {
+        @Nullable Descriptors.Descriptor union = null;
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: This means that you can't use an explicit usage on `DEFAULT_UNION_NAME` to use it some other way, which maybe is okay.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java [hunk 82]
```diff
@@ -290,20 +289,62 @@ private void loadFromProto(@Nonnull RecordMetaDataProto.MetaData metaDataProto,
...
+            if (recordTypeOptions != null && recordTypeOptions.hasUsage()) {
+                switch (recordTypeOptions.getUsage()) {
+                    case UNION:
+                        if (union != null) {
+                            throw new MetaDataException("Only one union descriptor is allowed");
+                        }
+                        union = descriptor;
+                        continue;
+                    case NESTED:
+                        continue;
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I think it's an accident of editing history that `NESTED` works differently from `RECORD`, etc.

Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: I kept it here intentionally because a NESTED message type cannot be a union descriptor and doesn't need the next check (at line 334). But now thinking thru it again, I guess it's missing a check that its name is not `DEFAULT_UNION_NAME`. Let me fix it.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java (hunk 81 above)
Comment (amouehsan) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordMetaDataBuilder.java]: That's right.

File: fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto [hunk 83]
```diff
@@ -0,0 +1,49 @@
...
+message MyUnmarkedRecord1 {
+  required int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+
+message MyUnmarkedRecord2 {
+  required int64 rec_no = 1 [(field).primary_key = true];
+  optional int32 num_value = 2;
+}
+message RecordTypeUnion {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/proto/test_records_marked_unmarked.proto]: Needs a blank line

**Comment by amouehsan** [comment]
> Okay, other than this one minor formatting thing, I think the only outstanding change request from this PR is a test to make sure that not setting a primary key results in the meta-data being rejected (unless I've missed that test somewhere).

Added now. thanks.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java [hunk 84]
```diff
@@ -224,4 +235,75 @@ public void badUnionFields() {
...
+        t = assertThrows(MetaDataException.class, () -> RecordMetaData.newBuilder().setRecords(TestRecordsUnionWithNestedProto.getDescriptor()));
+        assertEquals("Union field _MyNestedRecord has type MyNestedRecord which is not a record", t.getMessage());
+
+        t = assertThrows(MetaDataException.class, () -> RecordMetaData.newBuilder().setRecords(TestRecordsUnionWithImportedNestedProto.getDescriptor()));
+        assertEquals("Union field _MyNestedRecord has type RestaurantReview which is not a record", t.getMessage());
+    }
+
+    @Test
+    public void noPrimaryKey() {
+        Throwable t = assertThrows(MetaDataException.class, () ->
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: Could this be a `MetaDataException`?

Comment (amouehsan) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/RecordMetaDataBuilderTest.java]: sure.
