### PR TITLE
Validate that separate ports are assigned to each `ExternalServer`

### LINKED ISSUE #3929: `YamlTestExtension` seems to rarely start multiple external servers on the same port
This run failed when one of the `DocumentationQueryTests` displayed unexpected behavior: https://github.com/FoundationDB/fdb-record-layer/actions/runs/21530330669

From the logs included in the test reports:

```
2026-01-30 22:08:57,721 [INFO] c.a.f.r.y.s.ExternalServer - Started external server err_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-!current_version-1111-err.1754494390310835624.log" grpc_port="1111" http_port="1112" jar="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/externalServer/fdb-relational-server-4.9.6.0-all.jar" out_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-!current_version-1111-out.10676378663490580244.log" version="!current_version" {}
2026-01-30 22:09:00,742 [INFO] c.a.f.r.y.s.ExternalServer - Started external server err_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-4.9.4.0-1111-err.4689561780696515867.log" grpc_port="1111" http_port="1112" jar="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/externalServer/fdb-relational-server-4.9.4.0-all.jar" out_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-4.9.4.0-1111-out.4538351290628074477.log" version="4.9.4.0" {}
```

It looks like the 4.9.6.0 and 4.9.4.0 servers were both started on port 1111. Then we hit an error that looked like a request that was trying to target 4.9.4.0 actually went to 4.9.6.0. Which would make sense if, say, after this, the 4.9.4.0 server wasn't able to actually start because the port it was listening on was already in use.

We have a bunch of behavior in the files covered in `YamlIntegrationTests` at that same time, and those all succeeded. For that file, we see:

```
2026-01-30 22:10:37,979 [INFO] c.a.f.r.y.s.ExternalServer - Started external server err_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-!current_version-1111-err.9034997590691910401.log" grpc_port="1111" http_port="1112" jar="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/externalServer/fdb-relational-server-4.9.6.0-all.jar" out_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-!current_version-1111-out.2053876967657620012.log" version="!current_version" {}
2026-01-30 22:10:40,982 [INFO] c.a.f.r.y.s.ExternalServer - Started external server err_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-4.9.4.0-1113-err.18149555724328578421.log" grpc_port="1113" http_port="1114" jar="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/externalServer/fdb-relational-server-4.9.4.0-all.jar" out_file="/home/runner/work/fdb-record-layer/fdb-record-layer/yaml-tests/.out/tmp-test/fdb-relational-server-4.9.4.0-1113-out.10891905594048222494.log" version="4.9.4.0" {}
```

That is, the two versions get allocated separate ports. Which is in line with the problem being caused by this port issue (that is, a correct allocation of ports results in tests succeeding).

Unfortunately, we don't have any more server logs from this run, so we don't have more details as to why the builds failed. Prior to this build, we didn't even log the ports, so it's hard to say conclusively whether this explains other similar problems we saw during release, but it seems likely. Since then, we haven't had that failure re-occur, though we did add additional validation of the server version (see #3906). I did try and see if setting the version to a static 1111 would result in a re-occurrence, but it instead led to initialization errors (see #3928). So while I'm fairly confident that the errors seen are in line with the strange behavior, I suppose there is still a little bit of wiggle room remaining.

### PR DESCRIPTION
**Pull request by alecgrieser**
Based on errors that we saw during a few release builds, there are times when we were previously allocating the same port to multiple servers. It was very rare, and it is thus hard to reproduce, but we have some pretty definitive logs of this happening, though the exact cause for why is more open ended.

To combat this, I've modified the methods used to start multiple external servers. It now takes a set of ports that have previously been allocated, and it will avoid any port from that set. It then validates when it is done that all of the servers have separate ports, and it throws an error if this is violated. Note that this retains the behavior from before where it would look for ports in use and attempt to avoid them, as that's a useful feature, but it is now a bit more careful to avoid what is an apparent race condition when starting multiple servers at the same time. We also have validation that we're talking to the right external server version in the `ExternalServerConnectionFactory` (see #3906), so we should be protected if something else messes with these versions, but this makes a bit more protected.

This fixes #3929.

### CODE REVIEW

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java [hunk 1]
```diff
@@ -210,15 +226,17 @@ private boolean startServer(ProcessBuilder processBuilder) throws IOException, I
...
+     * GRPC port can be noted as unavailable when asking for the http port. If nothing is unavailable, use an empty set.
+     * The provided set must be mutable, as it will be updated during run as ports are allocated
      * @return a port that is not currently in use on the system.
      */
-    private int getAvailablePort(final int unavailablePort) {
+    private int getAvailablePort(@Nonnull final Set<Integer> unavailablePorts) {
         // running locally on my laptop, testing if a port is available takes 0 milliseconds, so no need to optimize
         for (int i = 1111; i < 9999; i++) {
-            if (i != unavailablePort && isAvailable(i)) {
+            if (unavailablePorts.add(i) && isAvailable(i)) {
```
Comment (ohadzeliger) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java:246]: This would add a port to the set even if we are not going to use it (i.e. it is `isAvailable==false`). I think this is the desired behavior since we can't bind to it so get it out of circulation and don't try it again.
If that was the intent, maybe add a comment to that effect?

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java [hunk 2]
```diff
@@ -240,4 +258,18 @@ public void stop() {
         }
     }
 
+    public static void startMultiple(@Nonnull Collection<ExternalServer> servers) throws Exception {
+        startMultiple(servers, new HashSet<>());
+    }
+
+    public static void startMultiple(@Nonnull Collection<ExternalServer> servers, @Nonnull Set<Integer> unavailablePorts) throws Exception {
+        final Map<Integer, ExternalServer> allocatedPorts = new HashMap<>();
```
Comment (ohadzeliger) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java:273]: Is this meant as extra protection for allocating ports? The `getAvailablePort` should have provided that guarantee. 
Would it make sense to add both ports to the map?

File: yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/ExternalServerTest.java [hunk 3]
```diff
@@ -60,17 +63,42 @@ void startMultiple() throws Exception {
...
             }
         }
     }
+
+    private static void assertDistinctPorts(@Nonnull Collection<ExternalServer> servers) {
+        // we can't assert about the actual values, because one of the ports may be busy,
+        // so assert that each server has its own port, and none of them have the same port
+        assertThat(servers)
+                .allSatisfy(server -> assertThat(server.getPort()).isNotEqualTo(server.getHttpPort()))
+                .map(ExternalServer::getPort)
```
Comment (ohadzeliger) [inline yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/ExternalServerTest.java]: Maybe `.flatMap(Stream.of(getPort(), getHttpPort())`? to get both ports?

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java (hunk 1 above)
Comment (alecgrieser) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java:246]: Yeah, that was the intended behavior. I've added a comment explaining in more detail about what it's doing and why

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java (hunk 2 above)
Comment (alecgrieser) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/server/ExternalServer.java:273]: Yeah, `getAvailablePort` should have provided that guarantee, so this is supposed to just be a double check. Also checking the http port seems like a good idea.

File: yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/ExternalServerTest.java (hunk 3 above)
Comment (alecgrieser) [reply yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/ExternalServerTest.java]: Done
