### PR TITLE
Fixes #512: Put a limit on the number of suppressed exceptions.

### LINKED ISSUE #512: Exceptions raised in asynchronous code can get an arbitrary number of suppressed exceptions.
When we get exceptions in async code, we prefer to throw the underlying cause. To preserve the stack trace, we add each of the `CompletionException`s to the list of suppressed exceptions of the cause. However, we can do this an arbitrary number of times, creating substantial GC pressure.

We should have an option to limit the number of suppressed exceptions.

### PR DESCRIPTION
**Pull request by nschiefer**
This adds an optional limit on the number of suppressed exceptions that can be added to a given exception. After the limit is reached, we start incrementing a special exception which holds a counter of the number of ignored exceptions that we were supposed to suppress.

The semantics of changing the limit are a bit odd. I didn't want to deal with exceptions that have a different limit, so I ended up permitting a single change from the default (unlimited) value. I don't think that @alecgrieser especially likes this but I think it suffices for most use cases while keeping the suppression-adding code pretty simple.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java [hunk 1]
```diff
@@ -78,9 +99,55 @@ private static Throwable asCauseThrowable(@Nonnull Throwable ex) {
...
+
+        private int count;
+
+        public synchronized void incrementCount() {
+            count++;
+        }
+
+        @Override
+        public StackTraceElement[] getStackTrace() {
+            return UNASSIGNED_STACK;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: It's a little unfortunate that the stack trace here won't be useful, but `fillInStackTrace` will get called in the constructor anyway. I *think* this could actually be addressed by having the default constructor for this class call this constructor: [`Exception(String, Throwable, boolean, boolean)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html#Exception-java.lang.String-java.lang.Throwable-boolean-boolean-) Then if `false` is given to `writableStackTrace`, I think it won't fill in the stack.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java [hunk 2]
```diff
@@ -65,6 +75,41 @@ private void testWrappedStackTrace(Exception cause, String methodName) {
...
+        Exception e3 = createCompletionException(base);
+        assertEquals(base, FDBExceptions.wrapException(e3));
+        suppressedExceptions = base.getSuppressed();
+        assertEquals(3, suppressedExceptions.length);
+        assertThat(Arrays.asList(suppressedExceptions), hasItems(e0, e1));
+        assertThat(Arrays.asList(suppressedExceptions), not(anyOf(hasItem(e2), hasItem(e3))));
+        countException = suppressedExceptions[2];
+        assertThat(countException, instanceOf(CompletionExceptionLogHelper.IgnoredSuppressedExceptionCount.class));
+        assertEquals(2, ((CompletionExceptionLogHelper.IgnoredSuppressedExceptionCount) countException).getCount());
+
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java]: Extra blank line

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java [hunk 3]
```diff
@@ -78,9 +99,55 @@ private static Throwable asCauseThrowable(@Nonnull Throwable ex) {
...
+
         if (addSuppressed) {
-            cause.addSuppressed(ex);    // Remember the original.
+            synchronized (cause) {
+                Throwable[] suppressedExceptions = cause.getSuppressed();
+                if (suppressedExceptions.length < maxSuppressedCount) {
+                    cause.addSuppressed(ex);
+                } else {
+                    IgnoredSuppressedExceptionCount suppressedCount;
+                    int lastIndex = suppressedExceptions.length - 1;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: Oh, I think this has a problem if `maxSuppressedCount` is set to zero or something negative. We should either (1) see if `suppressedExceptions` is empty or (2) validate that `maxSuppressedCount` is positive.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java [hunk 4]
```diff
@@ -55,6 +56,23 @@ public static void setAddSuppressed(boolean addSuppressed) {
...
 
+    /**
+     * Change the maximum number of suppressed exceptions to add to any given exception, if this maximum has not already
+     * been set. Return whether or not the maximum was changed.
+     *
+     * This method only changes behavior when {@link #addSuppressed} is {@code true}.
+     * @param count the new maximum count
+     * @return {@code true} if the count was changed and {@code false} if it was not
+     */
+    public static synchronized boolean setMaxSuppressedCountIfNotSet(int count) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: I think this will make it difficult to test different values of `count` in the unit tests, unless there's like a package-private visible-for-testing way of setting the count to something else.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java [hunk 5]
```diff
@@ -55,6 +56,23 @@ public static void setAddSuppressed(boolean addSuppressed) {
...
+        if (maxSuppressedCount == Integer.MAX_VALUE) {
+            maxSuppressedCount = count;
```
[the remark this answers is not in the document]
Comment (nschiefer) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: Sure, fine. Fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java (hunk 1 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: Great idea! Done.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java (hunk 2 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java]: Removed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java (hunk 3 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: Right, fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java (hunk 4 above)
Comment (nschiefer) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/CompletionExceptionLogHelper.java]: Yes, that's right. I added a scarily-named `@VisibleForTesting` method to allow this kind of testing and some tests to exercise it.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java [hunk 6]
```diff
@@ -65,6 +77,68 @@ private void testWrappedStackTrace(Exception cause, String methodName) {
...
+        CompletionExceptionLogHelper.forceSetMaxSuppressedCountForTesting(Integer.MAX_VALUE); //cleanup
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java]: I suppose, in theory, this should be in a `finally` block.

Comment (nschiefer) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptionsTest.java]: Sure, why not.
