### PR TITLE
Resolve #1459: Online Indexer: add time limit to OnlineIndexer.Config

### LINKED ISSUE #1459: Online Indexer: add time limit to OnlineIndexer.Config
Let the Online Indexer stop building if exceeding a user configurable time limit (default is no-limit). 
Unlike a "classic" timeout, this time limit exception should only be thrown at the end of an iteration and after committing (and updating the built area ranges).

### PR DESCRIPTION
**Pull request by jjezra**

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java [hunk 1]
```diff
@@ -563,9 +565,26 @@ RecordCoreException newPartlyBuildException(boolean continuedBuild,
...
+        }
+        final long now = System.currentTimeMillis();
+        if (startingTimeMillis + timeLimitMilliseconds >= now) {
+            return;
+        }
+        throw new TimeLimitException("Time Limit Exceeded",
+                LogMessageKeys.TIME_STARTED, startingTimeMillis,
+                LogMessageKeys.TIME_LIMIT, timeLimitMilliseconds,
+                LogMessageKeys.TIME_ENDED, now,
+                LogMessageKeys.TIME_UNIT, "milliseconds");
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:585]: In theory, it might make sense to put `MILLIS` in the name of `TIME_STARTED`, `TIME_ENDED`, and (especially) `TIME_LIMIT` instead of having a separate `TIME_UNIT` field. The logic for that is mainly that someone looking at the logs might not know that `TIME_UNIT` is associated with the other fields in the log (especially as it's not associated with every time-based field).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java [hunk 2]
```diff
@@ -872,7 +872,7 @@ public Builder setScrubbingPolicy(@Nonnull final ScrubbingPolicy.Builder scrubbi
          */
         public OnlineIndexScrubber build() {
             validate();
-            OnlineIndexer.Config conf = new OnlineIndexer.Config(limit, maxRetries, recordsPerSecond, progressLogIntervalMillis, increaseLimitAfter, maxWriteLimitBytes);
+            OnlineIndexer.Config conf = new OnlineIndexer.Config(limit, maxRetries, recordsPerSecond, progressLogIntervalMillis, increaseLimitAfter, maxWriteLimitBytes, 0);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java:875]: It might be good to define a constant somewhere so that callers can use a value that underscores the fact that they are asking for unlimited time à la `ExecuteProperties.UNLIMITED_TIME`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java [hunk 3]
```diff
@@ -838,6 +857,27 @@ public static boolean isValidationException(@Nullable Throwable ex) {
         return false;
     }
 
+    /**
+     * thrown when the indexing process exceeds the time limit.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:861]:
```suggestion
     * Thrown when the indexing process exceeds the time limit.
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java [hunk 4]
```diff
@@ -874,6 +877,14 @@ public long getMaxWriteLimitBytes() {
             return maxWriteLimitBytes;
         }
 
+        /**
+         * Exit with exception if this limit is exceeded (checked after each non-final iteration).
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:881]: Is "iteration" a term we've used before in the docs here? I wonder if "transaction" might be a better term (i.e., if that's something a user might already know about).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java [hunk 5]
```diff
@@ -991,13 +1004,26 @@ public Builder setIncreaseLimitAfter(int increaseLimitAfter) {
                 return this;
             }
 
+            /**
+             * Set the time limit. The indexer will exit with a proper exception if this time is exceeded after a non-final
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:1008]: Same comment about the word "iteration" as used above.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java [hunk 6]
```diff
@@ -1016,4 +1016,40 @@ public void testMarkReadableClearsBuiltRanges() {
...
+        try (OnlineIndexer indexer = OnlineIndexer.newBuilder()
+                .setDatabase(fdb).setMetaData(metaData).setIndex(index).setSubspace(subspace)
+                .setTimeLimitMilliseconds(1)
+                .setLimit(20)
+                .setConfigLoader(old -> {
+                    // Ensure that time limit is exceeded
+                    try {
+                        Thread.sleep(2);
+                    } catch (InterruptedException e) {
+                        e.printStackTrace();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java:1046]: Instead of printing the stack trace, it might make sense instead to call `fail` with something to indicate that the test was interrupted.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java [hunk 7]
```diff
@@ -1796,6 +1823,18 @@ public Builder setLeaseLengthMillis(long leaseLengthMillis) {
             return this;
         }
 
+        /**
+         * Set the time limit. The indexer will exit with a proper exception if this time is exceeded after a non-final
+         * iteration.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:1828]: Same comment about "iteration"

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java [hunk 8]
```diff
@@ -874,6 +877,14 @@ public long getMaxWriteLimitBytes() {
             return maxWriteLimitBytes;
         }
 
+        /**
+         * Exit with exception if this limit is exceeded (checked after each non-final iteration).
+         * @return time limit, in millisecond units.
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:882]:
```suggestion
         * @return time limit in milliseconds
```

Same for the other javadocs referencing units. I appreciate that the units here are documented, though 👍

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java [hunk 9]
```diff
@@ -563,9 +565,26 @@ RecordCoreException newPartlyBuildException(boolean continuedBuild,
                     .toString());
         }
 
+        validateTimeLimit();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:568]: I guess there's some more complicated version of this where the function factors in the fact that this build is about to wait `toWait` milliseconds, and then it throws a time limit exception before the time has actually elapsed if the extra time would cause it to exceed the time limit. I don't think that it's strictly necessary, and it may be better to leave it simpler, but food for thought.

**Review by alecgrieser — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:585]: Changed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java (hunk 2 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java:875]: Used `OnlineIndexer.Config.UNLIMITED_TIME`.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java (hunk 3 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:861]: Changed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java (hunk 4 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:881]: "transaction" is much better. Changed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java (hunk 5 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:1008]: Changed.

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java (hunk 6 above)
Comment (jjezra) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java:1046]: Changed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java (hunk 7 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:1828]: Changed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java (hunk 8 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:882]: Changed. 
(Though the comma was attributing a dramatic effect :)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java (hunk 9 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java:568]: I like your suggestion! 
Implemented.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java [hunk 10]
```diff
@@ -991,13 +1005,29 @@ public Builder setIncreaseLimitAfter(int increaseLimitAfter) {
                 return this;
             }
 
+            /**
+             * Set the time limit. The indexer will exit with a proper exception if this time is exceeded after a
+             * non-final transaction.
+             * @param timeLimitMilliseconds the time limit, in milliseconds units
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java:1011]:
```suggestion
             * @param timeLimitMilliseconds the time limit in milliseconds
```

It looks like this one got overlooked while cleaning up the Javadoc

**Review by alecgrieser — CHANGES_REQUESTED** [review]
Looks good! Just one javadoc comment change that it looks like was overlooked in the first pass

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java (hunk 10 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java]: Sure!

**Review by alecgrieser — APPROVED** [review]
