### PR TITLE
Ensure all callbacks (or close()) calls are made in the occurrence of exceptions 

### LINKED ISSUE #3899: FDBRecordContext hooks may be skipped in case of errors
The context's postCommit and postClose hooks invocation may be skipped in case the creation of the future (upon invocation of the hook) throws an exception (they work correctly in the case the future itself fails later on).

### PR DESCRIPTION
**Pull request by ohadzeliger**
This PR adds some protections around invoking callbacks in cases where some of the callbacks throw exceptions and we need to guarantee best effort in invoking each callback.
The infrastructure for the feature is an extension of the `CloseableUtils`, where a couple of methods are added (`invokeResults` with a result and `invokeAllFutures` that uses the returned list of futures from the first call to ensure all callbacks are invoked and joined.
The second part is the application of the new utilities in the `postClose` callbacks in the `FdbRecordCOntext` and in `FdbDirectoryManager` (in closing all opened directories).
Resolves #3899

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 1]
```diff
@@ -1043,30 +1045,49 @@ public PostCommit removePostCommit(@Nonnull String name) {
...
 
+    /**
+     * Run all post-commit callbacks.
+     * This method would invoke all given callbacks and will abort on exception.
+     * This semantic is correct given that any exception thrown prior to the commit should fail the commit and roll
+     * back the transaction.
+     * @return a future that completes when callbacks were invoked and futures have completed
+     */
     @Nonnull
     private CompletableFuture<Void> runPostCommits() {
```
Comment (ohadzeliger) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1054]: This returns the `runPostCommits` method to its original form (before the extraction of a helper method for use with the `postClose`).
`runPostCommit` is not modified to match the `postClose` behavior for a more resilient closing as it already exists and this would be considered a breaking change.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 2]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+    @Nonnull
+    public static <T> InvokeResults<T> invokeAll(List<Supplier<T>> callbacks) {
+        List<T> results = new ArrayList<>(callbacks.size());
+        CloseException accumulatedException = null;
+        for (Supplier<T> callback : callbacks) {
+            try {
+                results.add(callback.get());
+            } catch (Exception e) {
+                if (accumulatedException == null) {
+                    accumulatedException = new CloseException(e);
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: Is `CloseException` the appropriate exception to throw here, given that the callbacks may or may not be closes? I guess relatedly, should these methods go in a different utility class (perhaps a new one)?

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 3]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+     */
+    @API(API.Status.INTERNAL)
+    @Nonnull
+    public static <T> InvokeResults<T> invokeAll(List<Supplier<T>> callbacks) {
+        List<T> results = new ArrayList<>(callbacks.size());
+        CloseException accumulatedException = null;
+        for (Supplier<T> callback : callbacks) {
+            try {
+                results.add(callback.get());
+            } catch (Exception e) {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: `callback.get()` can't throw a non-RuntimeException, and this gets around the hypothetical possiblity that `Exception` is an `InterruptedException`
```suggestion
            } catch (RuntimeException e) {
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 4]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+     * regardless of whether they succeed or fail.
+     *
+     * @param callbacks the given sequence of callbacks
+     * @return a future that completes when all the produced futures complete. The returned future's result is
+     * <code>CompletedSuccessfully</code> if all futures were created and completed successfully, or an exception that
+     * holds all the exceptions that were thrown during the process
+     */
+    @API(API.Status.INTERNAL)
+    @Nonnull
+    public static <T> CompletableFuture<Void> invokeAllFutures(List<Supplier<CompletableFuture<T>>> callbacks) {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: What happens to the result of the futures? Does that just get dropped? Would this be better as (If the compiler will let you):
```suggestion
    public static CompletableFuture<Void> invokeAllFutures(List<Supplier<CompletableFuture<?>>> callbacks) {
```

Or should this return `CompletableFuture<InvokeResults<T>>`?

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 5]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+    public static class InvokeResults<T> {
+        private final List<T> results;
+        private final CloseException accumulatedException;
+
+        public InvokeResults(@Nonnull List<T> results, @Nullable CloseException accumulatedException) {
+            this.results = results;
+            this.accumulatedException = accumulatedException;
+        }
+
+        public @Nonnull List<T> getResults() {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]:
```suggestion
        @Nonnull
        public List<T> getResults() {
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 6]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+            return results;
+        }
+
+        public @Nullable CloseException getAccumulatedException() {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]:
```suggestion
        @Nullable
        public CloseException getAccumulatedException() {
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java [hunk 7]
```diff
@@ -26,7 +26,7 @@
  * exception thrown will be added as {@code Suppressed}.
  */
 @SuppressWarnings("serial")
-public class CloseException extends Exception {
+public class CloseException extends RuntimeException {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java]: Why change this to a `RuntimeException`?

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CloseableUtilsTest.java [hunk 8]
```diff
@@ -43,6 +49,57 @@ void closeAllNoIssue() throws Exception {
         Assertions.assertTrue(c3.isClosed());
     }
 
+    @Test
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/util/CloseableUtilsTest.java:46]: Are these just tests that you thought of while testing `invokeAll` and noticed they weren't on `closeAll`?

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java [hunk 9]
```diff
@@ -63,7 +72,84 @@ public static void closeAll(AutoCloseable... closeables) throws CloseException {
...
+        final CompletableFuture<Void> whenAll = AsyncUtil.whenAll(results.getResults());
+        return whenAll.handle((ignore, whenAllEx) -> {
+            if ((whenAllEx == null) && (results.accumulatedException == null)) {
+                // no exception was thrown in creation or invocation of callbacks
+                return null;
+            }
+            // combine creation exception with invocation exception
+            CloseException ex = results.getAccumulatedException();
+            if (ex == null) {
+                ex = new CloseException(whenAllEx);
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: hmm, I'm surprised, it looks like you can't just get the exception if a future completed exceptionally, you have to call `get` or `join` and then catch the exception, making it hard to get the exceptions back from the individual futures and rebuild the exception state.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 1 above)
Comment (ScottDugas) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1054]: Probably better as a followup, but the existing behavior for post commits seems like a bug. I would expect that one post-commit hook wouldn't stop other ones from running.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 10]
```diff
@@ -1045,28 +1047,40 @@ public PostCommit removePostCommit(@Nonnull String name) {
...
+                List<Supplier<CompletableFuture<Void>>> callbacks = postClose.values().stream().map(this::postCommitCallback).collect(Collectors.toList());
+                // This would ensure best-effort in calling all suppliers and waiting for all the futures
+                return CloseableUtils.invokeAllFutures(callbacks);
+            } finally {
+                postClose.clear();
+            }
+        }
+    }
+
+    private Supplier<CompletableFuture<Void>> postCommitCallback(PostCommit pc) {
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1088]: This method feels like it should just be inlined.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java [hunk 11]
```diff
@@ -520,4 +494,21 @@ private int getMergeDirectoryCount(@Nonnull IndexMaintainerState state) {
...
+     * @param wrapper the wrapper to invoke
+     * @return a callback that can be given to the {@link CloseableUtils}
+     */
+    private Supplier<Void> closeWithoutCommitCallback(FDBDirectoryWrapper wrapper) {
+        return () -> {
+            try {
+                wrapper.closeWithoutCommit();
+                return null;
+            } catch (IOException ex) {
+                throw new CompletionException(ex);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java:547]: Should this throw `CloseException`? At least if it stays a RuntimeException.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java [hunk 12]
```diff
@@ -520,4 +494,21 @@ private int getMergeDirectoryCount(@Nonnull IndexMaintainerState state) {
...
     }
 
+    /**
+     * A Utility to create a callback to invoke {@link FDBDirectoryWrapper#closeWithoutCommit()}.
+     * Needed in order to wrap the exception.
+     *
+     * @param wrapper the wrapper to invoke
+     * @return a callback that can be given to the {@link CloseableUtils}
+     */
+    private Supplier<Void> closeWithoutCommitCallback(FDBDirectoryWrapper wrapper) {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java:541]: Can this be static?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java [hunk 13]
```diff
@@ -407,8 +409,8 @@ void updateDocumentFailedTest(boolean useLegacyAsyncToSync) throws IOException {
                     5);
             // this should fail with injected exception
             recordStore.saveRecord(createComplexDocument(1000L , ENGINEER_JOKE, docGroupFieldValue, 2));
-            assertThrows(LuceneConcurrency.AsyncToSyncTimeoutException.class,
-                    () -> context.commit());
+            final CloseException closeException = assertThrows(CloseException.class, () -> context.commit());
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java]: Can we avoid the indirection here? I think it would be somewhat reasonable to have special handling for `AsyncToSyncTimeoutException`, but not so much `CloseException`?

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackException.java [hunk 14]
```diff
@@ -0,0 +1,35 @@
+/*
+ * CloseException.java
+ *
+ * This source file is part of the FoundationDB open source project
+ *
+ * Copyright 2015-2025 Apple Inc. and the FoundationDB project authors
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackException.java]:
```suggestion
 * Copyright 2015-2026 Apple Inc. and the FoundationDB project authors
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+     * exception (null if none).
+     *
+     * @param callbacks the given callbacks to invoke
+     *
+     * @return an {@link InvokeResults} with a list of results returned from successful invocations and a {@link CallbackException}
+     * that holds the exceptions thrown during unsuccessful invocations
+     */
+    @API(API.Status.INTERNAL)
+    @Nonnull
+    public static <T> InvokeResults<T> invokeAll(List<Supplier<T>> callbacks) {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java]:
```suggestion
    public static <T> InvokeResults<T> invokeAll(@Nonnull List<Supplier<T>> callbacks) {
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+     *
+     * @param callbacks the given sequence of callbacks
+     *
+     * @return a future that completes when all the produced futures complete. The returned future's result is
+     * <code>CompletedSuccessfully</code> if all futures were created and completed successfully, or an exception that
+     * holds all the exceptions that were thrown during the process
+     */
+    @API(API.Status.INTERNAL)
+    @Nonnull
+    public static <T> CompletableFuture<Void> invokeAllFutures(List<Supplier<CompletableFuture<T>>> callbacks) {
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java]:
```suggestion
    public static <T> CompletableFuture<Void> invokeAllFutures(@Nonnull List<Supplier<CompletableFuture<T>>> callbacks) {
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java [hunk 17]
```diff
@@ -0,0 +1,126 @@
...
+                ex = new CallbackException(whenAllEx);
+            } else if (whenAllEx != null) {
+                ex.addSuppressed(whenAllEx);
+            }
+            throw new CompletionException(ex);
+        });
+    }
+
+    public static class InvokeResults<T> {
+        private final List<T> results;
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java:106]:
```suggestion
        @Nonnull
        private final List<T> results;
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java [hunk 18]
```diff
@@ -0,0 +1,126 @@
...
+        private final CallbackException accumulatedException;
```
Comment (ScottDugas) [inline fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java:108]:
```suggestion
        @Nullable
        private final CallbackException accumulatedException;
```

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java [hunk 19]
```diff
@@ -0,0 +1,274 @@
...
+import java.util.List;
+import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.CompletionException;
+import java.util.concurrent.atomic.AtomicBoolean;
+import java.util.function.Supplier;
+
+import static org.junit.jupiter.api.Assertions.assertThrows;
+
+/**
+ * Tests for the {@link CloseableUtils} class.
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java]:
```suggestion
 * Tests for the {@link CallbackUtils} class.
```

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java [hunk 20]
```diff
@@ -0,0 +1,274 @@
...
+        @Override
+        public void close() throws InterruptedException {
+            closed = true;
+            throw new InterruptedException("interrupted");
+        }
+
+        public boolean isClosed() {
+            return closed;
+        }
+    }
```
Comment (ScottDugas) [inline fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java]: Unused in this class
```suggestion
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 10 above)
Comment (ScottDugas) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1088]: Also, this method appears to exist twice, with the same signature

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java [hunk 21]
```diff
@@ -125,8 +134,12 @@ public synchronized void close() throws IOException {
...
     public synchronized void closeWithoutCommit() throws IOException {
         try {
-            for (FDBDirectoryWrapper directory : createdDirectories.values()) {
-                directory.closeWithoutCommit();
+            List<Supplier<Void>> callbacks = createdDirectories.values().stream()
+                    .map(this::closeWithoutCommitCallback).collect(Collectors.toList());
+            // ensure we close all resources, regardless of exceptions
+            final CallbackUtils.InvokeResults<Void> results = CallbackUtils.invokeAll(callbacks);
+            if (results.getAccumulatedException() != null) {
+                throw new IOException(results.getAccumulatedException());
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java]: Should this be using `LuceneException.toIoException`

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1054]: Changed `postCommit` to follow the same logic as `postClose`.
`commitCheck` (and consequently `FdbDirecrotyManager.close()` do not apply the same logic.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java (hunk 2 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: Split the implementation in 2: `CloseableUtils` remained as-is while all new logic went over to `CallbackUtils` (and `CallbackException`)

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java (hunk 3 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java (hunk 4 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: The result of the `Future`s gets ignored (similar to the way `whenAll` does). This makes the API a little easier to use and does not cause an inconsistency when there is an exception thrown (since then you won't get any of the results).

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java (hunk 5 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java (hunk 6 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseableUtils.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java (hunk 7 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java]: Having this be a subclass of `RuntimeException` makes it easier to propagate through the flow (esp. with Lucene's `IOException` in the middle, since we don't have to wrap it. Having said that, since `FdbDirectoryManager.close()` does not throw `CloseException`, this may not be as important.

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CloseableUtilsTest.java (hunk 8 above)
Comment (ohadzeliger) [reply fdb-extensions/src/test/java/com/apple/foundationdb/util/CloseableUtilsTest.java:46]: Yes, added them after seeing that `CallbackUtils` tested more

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 10 above)
Comment (ohadzeliger) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1088]: Inlining the method gets really awkward as the compiler cannot infer the type and the resulting code gets hard to look at.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java (hunk 11 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java:547]: `CloseException` is the accumulator of thrown exceptions, whereas this is a "leaf" exception.
Ideas welcome - but we need this to be some `RuntimeException` that signifies invocation failure.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java (hunk 12 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java:541]: Yes, but why would that be better? The call site would then have to use the class name which I think is less clear.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java (hunk 13 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java]: This was actually a bug. The correct way was to not use `CloseUtils` in the `FdbDirectoryManager` but rather throw the original to stop the transaction from committing as soon as the first exception was thrown, and so now no wrapping is done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackException.java (hunk 14 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackException.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java (hunk 15 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java (hunk 16 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java (hunk 17 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java:106]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java (hunk 18 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CallbackUtils.java:108]: Done.

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java (hunk 19 above)
Comment (ohadzeliger) [reply fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java]: Done.

File: fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java (hunk 20 above)
Comment (ohadzeliger) [reply fdb-extensions/src/test/java/com/apple/foundationdb/util/CallbackUtilsTest.java]: Done - this was part of the botched merge from main

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java (hunk 21 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryManager.java]: Done.

File: fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java (hunk 7 above)
Comment (ohadzeliger) [reply fdb-extensions/src/main/java/com/apple/foundationdb/util/CloseException.java]: Reverted.
