### PR TITLE
Fix CTE Alias Visibility Bug

### LINKED ISSUE #3944: CTE Alias Visibility Issue - Subsequent CTEs Cannot Reference Earlier CTEs
This bug causes queries with multiple CTEs to fail when a later CTE tries to reference an earlier one. For example, if you define dept_counts as a CTE and then try to reference it in a second CTE called large_depts, the query fails with "Unknown table DEPT_COUNTS" even though this should be perfectly valid SQL. The issue affects any query pattern where CTEs are chained together, which is a pretty common use case for building up complex queries in a readable way.

The root cause is that CTE operators weren't being added to the plan fragment until after **all** CTEs were processed, so when the parser tried to resolve a reference to an earlier CTE, it couldn't find it yet. This is a fundamental visibility issue that prevents standard SQL patterns from working correctly.

### PR DESCRIPTION
**Pull request by hatyo**
This PR fixes a bug where subsequent CTEs in a `WITH` clause couldn't reference earlier CTEs, causing "Unknown table" errors. The problem was in how we were processing CTEs - we were collecting all the CTE operators first and then adding them to the plan fragment as a batch, which meant that when processing a CTE that references an earlier one, the earlier CTE wasn't visible yet in the plan 

The fix changes the flow so that each CTE operator gets added to the current plan fragment immediately as it's processed, rather than collecting them all and adding them at the end. This required changing the return type of `visitCtes()` from LogicalOperators to Void and updating the call sites accordingly. I've added several test cases covering two-level dependencies, three-level CTE chains, and cross-references with joins to make sure this works correctly going forward.

This fixes #3944.

### CODE REVIEW

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java [hunk 1]
```diff
@@ -132,11 +133,18 @@ public LogicalOperators visitCtes(@Nonnull RelationalParser.CtesContext ctx) {
...
+            }
+            return null;
         } else {
             Assert.thatUnchecked(ctx.traversalOrderClause() == null, ErrorCode.SYNTAX_ERROR, "traversal order clause can only be defined with recursive CTE");
         }
-        return LogicalOperators.of(ctx.namedQuery().stream().map(this::visitNamedQuery).collect(ImmutableList.toImmutableList()));
+        for (final var namedQuery : ctx.namedQuery()) {
+            currentPlanFragment.addOperator(visitNamedQuery(namedQuery));
+        }
+        return null;
```
Comment (sergei-pustovykh) [inline fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java:146]: very minor: `if block` ends by return, after we have `else block` and global block of code - looks a bit confusing. I would remove `else` here.

**Review by sergei-pustovykh — APPROVED** [review]

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java (hunk 1 above)
Comment (hatyo) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java:146]: Good point, thank you.

**Review by sergei-pustovykh — APPROVED** [review]
