### PR TITLE
resolves #2061: fixes for join enumeration

### LINKED ISSUE #2061: improve join enumeration and plan memoization
The current join-enumeration algorithm (via `ImplementNestedLoopJoin`) is inflexible and wasteful during replanning due to bad memoization. We essentially transition from a `SelectExpression` owning `n` quantifiers to a tree of nested-loop joins (`RecordQueryFlatMapPlan`). While that tree step-by-step, we pick two quantifiers of the select and join them and then re-add the remainder of the original `SelectExpression` as a new `SelectExpression` ranging over the e.g. nested loop join. That causes enumeration of that rest, but also that rest is already enumerated in the original `SelectExpression`. The rest cannot easily be memoized. Also, if the `SelectExpression` needs to be re-implemented (re-planned) due to e.g. other ordering requirements this explorations starts again. This is bad and needs to be improved.

### PR DESCRIPTION
**Pull request by normen662**

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java [hunk 1]
```diff
@@ -156,7 +143,7 @@ public boolean equalsWithoutChildren(@Nonnull final RelationalExpression other,
 
     @Override
     public int hashCodeWithoutChildren() {
-        return Objects.hash(computeResultSupplier, getGroupingValue(), getAggregateValue());
```
Comment (hatyo) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java:159]: 🤦

**Review by hatyo — APPROVED** [review]
LGTM
