### PR TITLE
KeySpaceUtils.pathToUri / toPathString no longer add extra / when path ends with NULL

### LINKED ISSUE #3912: KeySpaceUtils.pathToUri inserts extra `/` when path ends with NULL
KeySpaceUtils.pathToUri inserts extra `/` when path ends with NULL.

I created the following test:
```
    @Test
    void nullAtEnd() throws RelationalException {
        KeySpace keySpace = new KeySpace(
                createDirectory("null", KeySpaceDirectory.KeyType.NULL, true, null),
                createDirectory("parent", KeySpaceDirectory.KeyType.STRING, true, "parent")
                        .addSubdirectory(createDirectory("null", KeySpaceDirectory.KeyType.NULL, true, null)));
        URI rootUrl = URI.create("/");
        final KeySpacePath rootPath = keySpace.path("null");
        URI url = URI.create("/parent/");
        final KeySpacePath path = keySpace.path("parent").add("null");
        Assertions.assertAll(
                () -> Assertions.assertEquals(rootPath, KeySpaceUtils.toKeySpacePath(rootUrl, keySpace)),
                () -> Assertions.assertEquals(rootUrl, KeySpaceUtils.pathToUri(rootPath)),
                () -> Assertions.assertEquals(path, KeySpaceUtils.toKeySpacePath(url, keySpace)),
                () -> Assertions.assertEquals(url, KeySpaceUtils.pathToUri(path)));
    }
```

And it fails because the root produces `//` and the non-root produces `/parent//`.

### PR DESCRIPTION
**Pull request by ScottDugas**
This changes `KeySpaceUtils.pathToUri` and `toPathString` so that they no longer introduce an extraneous `/` at the end when the path ends with `NULL`. This also updates the parsing tests to help ensure that `pathToUri`, `toPathString` and `toKeySpacePath` all align.

As an example, if you have:
```java
var keySpace = new KeySpace(new KeySpaceDirectory("env", STRING)
    .addSubdirectory(new KeySpaceDirectory("app", STRING)
        .addSubdirectory(new KeySpaceDirectory("db", NULL))));
var path = keySpace.path("env", "prod").add("app", "testApp").add("db");
var uri = KeySpaceUtils.pathToUri(path);
```
Previously the `uri` would be `/prod/testApp//` but if you parse that it would fail, expecting a longer path.
Now the `uri` would be `/prod/testApp/` which would parse back into `path`.

Resolves #3912

### CODE REVIEW

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java [hunk 1]
```diff
@@ -33,33 +33,41 @@
...
     public static URI pathToUri(@Nonnull KeySpacePath dbPath) {
-        return URI.create("/" + toPathString(dbPath));
+        return URI.create(pathToUriList(dbPath).stream().collect(Collectors.joining("/", "/", "")));
     }
 
-    public static String toPathString(KeySpacePath path) {
-        String uriPath = "";
-        while (path != null) {
-            if (path.getDirectory().getKeyType() == KeySpaceDirectory.KeyType.NULL) {
-                uriPath = "/" + uriPath;
```
Comment (alecgrieser) [inline fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java:52]: Okay, it took me a while to understand what this PR was trying to do, but I see it now. Because this didn't check to see if the `uriPath.length()` was zero here, a key space path like `env=prod/app=testApp/db=NULL` would get turned into the URI `/prod/test//` instead of `/prod/test/`. There's still a slash at the end of the URI (as the `parseable` test shows), but there's not a _second_ extra slash.

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java [hunk 2]
```diff
@@ -33,33 +33,41 @@
...
-                }
-            }
-            path = path.getParent();
+    @Nonnull
+    private static List<String> pathToUriList(final @Nonnull KeySpacePath dbPath) {
+        final List<String> asList = Stream.iterate(dbPath, Objects::nonNull, KeySpacePath::getParent)
+                .map(KeySpaceUtils::toPathElement)
+                .collect(Collectors.toCollection(ArrayList::new)); // guarantee mutability, for reverse
+        Collections.reverse(asList);
+        return asList;
```
Comment (alecgrieser) [inline fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java]: I see we're returning the mutable list. That looks fine for how we're currently using the method. We could alternatively wrap this in `Collections.unmodifiableList` to avoid a user accidentally modifying it later, or we could use Guava's `Lists.reverse`, which (unlike `Collections.reverse`) returns a view rather than modifying the underlying collection.

All of this is minor though, and I'm happy to take this as-is.

**Review by alecgrieser — APPROVED** [review]

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java (hunk 1 above)
Comment (ScottDugas) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java:52]: ok, I added your example to the pr description to make it clearer. Hopefully that helps should anyone else come along.

File: fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java (hunk 2 above)
Comment (ScottDugas) [reply fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/KeySpaceUtils.java]: `Lists.reverse`, I forgot that existed, and was trying quite hard to find a simple/elegant way to reverse the stream.  I like that much better.

**Review by alecgrieser — APPROVED** [review]
