### PR TITLE
Fix filtered index matching for queries with non-compile-time range predicates

### LINKED ISSUE #3940: Filtered index matching fails for queries with non-compile-time range predicates
The planner currently cannot match filtered indexes when query predicates contain non-compile-time ranges (e.g., join predicates with parameter references). The issue is in `RangeConstraints.encloses()`, which returns false if the query range is not compile-time evaluable, even when the candidate index range is compile-time evaluable. This is overly restrictive.

Since query predicates are conjunctive, any non-compile-time components only strengthen the query condition—they don't weaken it. The enclosure check should proceed by comparing the compile-time portions of both ranges. The candidate range must still be compile-time evaluable, but we should allow the query range to have non-compile-time components and simply ignore them during the implication check. This would enable the planner to correctly match filtered indexes even when queries involve join conditions.

### PR DESCRIPTION
**Pull request by hatyo**
This PR fixes an issue where the planner failed to match filtered indexes when query predicates contained non-compile-time ranges, such as join predicates. Previously, `RangeConstraints.encloses()` would bail out if either the candidate range or the query range was not fully compile-time evaluable.

However, this was overly conservative—the candidate range must be compile-time evaluable, but the query range doesn't need to be. Since query predicates form a conjunction, any non-compile-time components only make the query stricter. The fix allows the enclosure check to proceed by comparing the compile-time portions of both ranges, correctly matching filtered indexes even when queries include non-compile-time predicates like join conditions.

As a related cleanup, this also removes the Proposition three-valued logic enum in favor of boolean returns, since the `UNKNOWN` state was always coalesced to false in practice.

This fixes #3940.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PredicateMap.java [hunk 1]
```diff
@@ -58,7 +58,7 @@ public static PredicateMap empty() {
     private static Optional<SetMultimap<QueryPredicate, PredicateMapping>> checkUniqueness(@Nonnull final SetMultimap<QueryPredicate, PredicateMapping> map) {
         for (final QueryPredicate queryPredicate : map.keySet()) {
             final Set<PredicateMapping> candidatePredicateMappings = map.get(queryPredicate);
-            if (candidatePredicateMappings.size() != 1) {
+            if (candidatePredicateMappings.stream().map(PredicateMapping::getParameterAliasOptional).flatMap(Optional::stream).count() > 1) {
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PredicateMap.java]: Can you explain what that does? How could you end up with more than one mapping here? The index side should not have more than one placeholder for the same field, etc.
