### PR TITLE
Resolves #2455 and Resolves #2457: fixes some random Lucene test failures

### LINKED ISSUE #2455: LuceneOptimizedTermVectorsFormatTest.randomExceptions fails with seed: 98282DFC9AD21883
```
java.lang.NullPointerException
	at __randomizedtesting.SeedInfo.seed([98282DFC9AD21883:F007433804DC4123]:0)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexOutput.flush(FDBIndexOutput.java:195)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexOutput.close(FDBIndexOutput.java:105)
	at org.apache.lucene.store.MockIndexOutputWrapper.close(MockIndexOutputWrapper.java:96)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:77)
	at org.apache.lucene.codecs.compressing.FieldsIndexWriter.close(FieldsIndexWriter.java:174)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:77)
	at org.apache.lucene.codecs.compressing.CompressingTermVectorsWriter.close(CompressingTermVectorsWriter.java:260)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:77)
	at org.apache.lucene.index.TermVectorsConsumer.flush(TermVectorsConsumer.java:80)
	at org.apache.lucene.index.TermsHash.flush(TermsHash.java:81)
	at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:81)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:267)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:350)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:476)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:656)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:605)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:121)
	at org.apache.lucene.index.BaseIndexFileFormatTestCase.testRandomExceptions(BaseIndexFileFormatTestCase.java:645)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

### LINKED ISSUE #2457: Closing FDBIndexOutput twice results in a NullPointerException
The following code will result in a `NullPointerException`:
```
    @Test
    void testCloseTwice() {
        FDBIndexOutput output = new FDBIndexOutput(FILE_NAME, directory);
        output.close();
        output.close();
    }
```

### PR DESCRIPTION
**Pull request by ScottDugas**
This resolves three issues:
1. #2455 - If the `FDBDirectory` is wrapped in a `NRTCachingDirectory`, we may end up only writing the output to `NRTCachingDirectory`, and not syncing it to the underlying `FDBDirectory`. This may only be a test issue, but the resolution is to call `sync`, which is a no-op in `FDBDirectory`, so this seems worthwhile.
2. Similar to #2455 there is an issue with not syncing while copying the field infos id to the `.cfe` when creating a compound file. This includes a fix, and adds a seed that reproduces it.
3. #2457 - If Lucene closes an FDBIndexOutput twice it will result in an NPE. We now make sure that doesn't happen. This is brought into this PR, because without this fix, the seed originally noted in #2455 cannot be included, as the test still fails.

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java [hunk 1]
```diff
@@ -95,4 +96,10 @@ public void testOneDimTwoValues() throws Exception {
         TestFDBDirectory.allowAddIndexes();
         super.testOneDimTwoValues();
     }
+
+    @Seeds({@Seed(), @Seed("FA63D2AE2DE7C6B0")})
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java:100]: I confirmed in the logs that it ran this test with two seeds, and used the same "random" seed both builds:
```
LuceneOptimizedPointsFormatTest > testMultiValued > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedPointsFormatTest.testMultiValued {seed=[C185081D42F0F43C:FA63D2AE2DE7C6B0]} STARTED

LuceneOptimizedPointsFormatTest > testMultiValued > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedPointsFormatTest.testMultiValued {seed=[C185081D42F0F43C:FA63D2AE2DE7C6B0]} PASSED

LuceneOptimizedPointsFormatTest > testMultiValued > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedPointsFormatTest.testMultiValued {seed=[C185081D42F0F43C:15A56C2F8C32B474]} STARTED

LuceneOptimizedPointsFormatTest > testMultiValued > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedPointsFormatTest.testMultiValued {seed=[C185081D42F0F43C:15A56C2F8C32B474]} PASSED
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedTermVectorsFormatTest.java [hunk 2]
```diff
@@ -77,4 +78,10 @@ public void tearDown() throws Exception {
     public void testMultiClose() throws IOException {
         BaseIndexFileFormatTestCaseUtils.testMultiClose(this);
     }
+
+    @Seeds({@Seed(), @Seed("F007433804DC4123")})
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedTermVectorsFormatTest.java:82]: Confirmed this ran twice with the same random seed, and the provided seed, as expected:
```
LuceneOptimizedTermVectorsFormatTest > testRandomExceptions > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedTermVectorsFormatTest.testRandomExceptions {seed=[C185081D42F0F43C:F007433804DC4123]} STARTED

LuceneOptimizedTermVectorsFormatTest > testRandomExceptions > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedTermVectorsFormatTest.testRandomExceptions {seed=[C185081D42F0F43C:F007433804DC4123]} PASSED

LuceneOptimizedTermVectorsFormatTest > testRandomExceptions > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedTermVectorsFormatTest.testRandomExceptions {seed=[C185081D42F0F43C:A9AA66D9DCFEAD9C]} STARTED

LuceneOptimizedTermVectorsFormatTest > testRandomExceptions > com.apple.foundationdb.record.lucene.codec.LuceneOptimizedTermVectorsFormatTest.testRandomExceptions {seed=[C185081D42F0F43C:A9AA66D9DCFEAD9C]} PASSED

```

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FieldInfosStorage.java [hunk 3]
```diff
@@ -103,8 +107,18 @@ public FDBLuceneFileReference getFDBLuceneFileReference(String fileName) {
...
     }
 
-    public void setFieldInfoId(String fileName, long id, BitSet fieldBitSet) {
-        directory.setFieldInfoId(fileName, id, ByteString.copyFrom(fieldBitSet.toByteArray()));
+    public void setFieldInfoId(final Directory wrappingDirectory, String fileName, long id, BitSet fieldBitSet)
+            throws IOException {
+        setFieldInfoId(wrappingDirectory, fileName, id, ByteString.copyFrom(fieldBitSet.toByteArray()));
+    }
+
+    private void setFieldInfoId(final Directory wrappingDirectory, String fileName, long id, final ByteString bitSet)
```
[the remark this answers is not in the document]
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FieldInfosStorage.java:115]: Or, maybe call the `sync()` in the `CompoundInfosFormat`, thus terminating the special case at a lower level?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java (hunk 1 above)
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LuceneOptimizedPointsFormatTest.java:100]: The `@Seed()` here uses the "random" seed, but in this case, the seed is fixed by the `@Seed` on the class.
Adding `@Seed("FA63D2AE2DE7C6B0")` means that it will always run once with that seed to ensure that we are reproducing this issue. This way, this test will run with two seeds in prb: `C185081D42F0F43C:FA63D2AE2DE7C6B0`  and `C185081D42F0F43C:15A56C2F8C32B474`. The former reproduces the issue this PR is fixing, and the latter (I believe) was the seed originally used, and passing in PRB.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FieldInfosStorage.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FieldInfosStorage.java:115]: It's not really targeting a test construct. It's targeting the possibility of other readers wrapping the `FDBDirectory`. Calling `sync` is a standard operation of the directory intended to be used to ensure that the files have been serialized. This makes our directory/codec implementation more resilient to fitting into the Lucene environment. The directory that doesn't play well with our usage is `NRTCachingDirectory`, which is part of Lucene-core, and not a testing construct.
I had thought `NRTCachingDirectory` was potentially used in Lucene, but it looks like it has no references, and the user (i.e. the record layer) would have to create an `NRTCachingDirectory` to hit the issue. 

Having a test-specific `FieldInfoStorage` feels like adding an unnecessary injection point; If we decide that it's better in test-only code, I would rather put it in the codec files.

The reason it is here, and not in `CompoundInfosFormat` is that it is necessary for both `FieldInfosFormat` and `CompoundInfosFormat`, the two places that call `setFieldInfoId`. Originally I had just added it in `FieldInfosFormat`, but that still failed. It seemed better to have it centralized in the `FieldInfoStorage`

**Review by ohadzeliger — APPROVED** [review]
