### PR TITLE
Stop implementing aggregate plans on top of non-continuable plans

### LINKED ISSUE #3979: Aggregate continued queries without an explicit group have incorrect results
For a query with an aggregate function and no explicit group such as `SELECT COUNT(*) FROM T` that ends up being planned as a `RecordQueryStreamingAggregationPlan`, partial aggregation results do not get stored in continuations correctly. As a result, the final result retrieved from the final continuation will not contain the partial results from previous executions.

For example, if T has 13 rows and no aggregate indexes defined, the query will be planned as `SCAN(<,>) | MAP (_ AS _0) | AGG (count_star(*) AS _0) | ON EMPTY NULL | MAP (coalesce_long(_._0._0, promote(0l AS LONG)) AS _0)`. If we assume an enforced scan row limit of 5, we expect the final result after 2 continuations to be 13, but instead the result is 1, which is the number of records scanned in the third scan.

### PR DESCRIPTION
**Pull request by hazefully**
This PR modifies the `ImplementStreamingAggregationRule` planner rule in b13ce882d7797e4f370293c7da7220cf8f9df555 to prevent producing a `RecordQueryStreamingAggregationPlan` plan on top of plans that can not be continued without producing duplicate records. This is because the `RecordQueryStreamingAggregationPlan` may produce incorrect results if the underlying plan returns the same record more than once across continuations.

The PR also fixes #3979 in https://github.com/FoundationDB/fdb-record-layer/commit/062a915492369cc7ec76808b90042d9c0b7a131a by correctly handling the serialisation of partial aggregation results for streaming aggregate queries without an explicit group by value. Previously, the partial aggregation results were lost whenever the query triggered a continuation as the code in `StreamGrouping` only included the partial results if the current group was non-null, which was never true in case there is no explicit group by value defined in the query. This PR fixes this by serialising the partial aggregation regardless of the value of the current group. However, this introduces a backwards compatibility complication where if an older version receives a continuation with the partial aggregation result serialised with a null grouping value, it would throw a `NullPointerException` as it would attempt to deserialise the null `currentGroup` value using the null grouping value.

To make this change backwards-compatible, a temporary workaround is added to make sure that the grouping value of `RecordQueryStreamingAggregationPlan` implemented by the planner always has a non-null grouping value, which is an empty `RecordConstructorValue` in case there is no explicit grouping. This workaround can be removed once earlier versions don't need to be supported and is tracked in #4108, with the small overhead of having to update the expected plans in YAML tests when that workaround is removed. In addition, this workaround doesn't change the result or the semantics of the `RecordQueryStreamingAggregationPlan` as any as any action that needs to be taken to account for an empty grouping value, such as making sure that a zero is returned instead of null for a COUNT aggregate query, is done before the `RecordQueryStreamingAggregationPlan` is constructed by adding additional expressions on top of it (see [1](https://github.com/FoundationDB/fdb-record-layer/blob/067832017333560be75bb7e8565882ba852fc842/fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java#L408-L409) and [2](https://github.com/FoundationDB/fdb-record-layer/blob/067832017333560be75bb7e8565882ba852fc842/fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java#L617-L622)). 

The PR also includes the following changes:

- 33d0781833a224f54c8d86df42caf035231ff103 adds a new non-tracked expression property which the `ImplementStreamingAggregationRule` cascades implementation rule makes use of in b13ce882d7797e4f370293c7da7220cf8f9df555.
- 77b031ea08de9c082f30459c1d02914cbc9664f4 fixes an issue with YAML tests running in forceContinuations mode, where continuations were consumed by the test framework even if they are caused by hitting a different limit from the enforced maxRows limit. This is necessary to make it possible to write tests with expected results being the same when `forceContinuations` is on and off.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java [hunk 1]
```diff
@@ -96,17 +98,27 @@ public void onMatch(@Nonnull final ImplementationCascadesRuleCall call) {
         for (final var planPartition : planPartitions) {
             final var providedOrdering = planPartition.getPartitionPropertyValue(OrderingProperty.ordering());
             if (requiredOrderingKeyValues == null || providedOrdering.satisfiesGroupingValues(requiredOrderingKeyValues)) {
-                call.yieldPlan(implementGroupBy(call, planPartition, groupByExpression));
+                // The aggregation result from a streaming aggregation may be incorrect if the underlying plan returns
+                // the same record multiple times across continuations for some aggregate values (e.g. COUNT).
+                final var plansWithDistinctRecordsAcrossContinuations =
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java]: Can you try to express this as a rule filter on the partitions so we can put this into the pre of the rule?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java [hunk 2]
```diff
@@ -96,17 +98,27 @@ public void onMatch(@Nonnull final ImplementationCascadesRuleCall call) {
...
+
+                call.yieldPlan(implementGroupBy(call, plansWithDistinctRecordsAcrossContinuations, groupByExpression));
             }
         }
     }
 
     @Nonnull
     private RecordQueryStreamingAggregationPlan implementGroupBy(@Nonnull final ImplementationCascadesRuleCall call,
-                                                                 @Nonnull final PlanPartition planPartition,
+                                                                 @Nonnull final Collection<RecordQueryPlan> plans,
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java]: If this was expressed in the pre, this would still be a plan partition.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java [hunk 3]
```diff
@@ -469,14 +471,18 @@ public static RecordQueryStreamingAggregationPlan of(@Nonnull final Quantifier.P
                                                          @Nonnull final BiFunction<Value, Value, Value> resultValueFunction) {
         final var groupingKeyAlias = CorrelationIdentifier.uniqueId();
         final var aggregateAlias = CorrelationIdentifier.uniqueId();
+        // TODO: this is a temporary workaround for https://github.com/FoundationDB/fdb-record-layer/issues/3979, as
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java:474]: is there an issue for the follow-up work to remove this again? if not, can you create one?

File: yaml-tests/src/test/resources/aggregate-index-tests-count-empty.yamsql [hunk 4]
```diff
@@ -57,15 +57,15 @@ test_block:
       - result: []
     -
       - query: select count(*) from t2
-      - explain: "ISCAN(MV5 <,>) | MAP (_ AS _0) | AGG (count_star(*) AS _0) | ON EMPTY NULL | MAP (coalesce_long(_._0._0, promote(0l AS LONG)) AS _0)"
+      - explain: "ISCAN(MV5 <,>) | MAP (_ AS _0) | AGG (count_star(*) AS _0) GROUP BY () | ON EMPTY NULL | MAP (coalesce_long(_._0._0, promote(0l AS LONG)) AS _0)"
```
Comment (normen662) [inline yaml-tests/src/test/resources/aggregate-index-tests-count-empty.yamsql:64]: The streaming aggregation operator reacts differently to an empty table depending on whether the underlying stream is empty or not. So `AGG agg_func(.) GROUP BY ()` is semantically different from `AGG agg_func(.)`. I am not sure why the plan has changed though.

**Review by normen662 — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java (hunk 1 above)
Comment (hazefully) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java]: As discussed offline, I extended `PlanPartitionMatchers::rollUpPartitionsTo` so it supports rolling up partitions using untracked properties, and used that to push this filter and ordering roll up to the rule matcher.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java (hunk 3 above)
Comment (hazefully) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java:474]: I created a new issue (#4108) and referenced it from the comment.

File: yaml-tests/src/test/resources/aggregate-index-tests-count-empty.yamsql (hunk 4 above)
Comment (hazefully) [reply yaml-tests/src/test/resources/aggregate-index-tests-count-empty.yamsql:64]: I expanded the comment where the workaround is documented and the pull request description to make it clear why this workaround doesn't change the semantics/results of aggregate queries.

**Comment by hazefully** [comment]
> # 📊 Metrics Diff Analysis Report
> ...
> ## Dropped Queries
> The following queries with metrics were removed:
> 
> * [yaml-tests/src/test/resources/join-with-order-by-tests.metrics.yaml:404](https://github.com/FoundationDB/fdb-record-layer/blob/5d5f64d134b657a5f0756242bd81a5e1e92cd4bb/yaml-tests/src/test/resources/join-with-order-by-tests.metrics.yaml#L404): `EXPLAIN select t1.* from t1 where exists (select 1 from t2 where t2.b1 = 1) and t1.a1 = 1 order by t1.a2 desc`
> * [yaml-tests/src/test/resources/record-type-key-tests.metrics.yaml:139](https://github.com/FoundationDB/fdb-record-layer/blob/5d5f64d134b657a5f0756242bd81a5e1e92cd4bb/yaml-tests/src/test/resources/record-type-key-tests.metrics.yaml#L139): `EXPLAIN SELECT a from t1 where b > 20`
> * [yaml-tests/src/test/resources/record-type-key-tests.metrics.yaml:151](https://github.com/FoundationDB/fdb-record-layer/blob/5d5f64d134b657a5f0756242bd81a5e1e92cd4bb/yaml-tests/src/test/resources/record-type-key-tests.metrics.yaml#L151): `EXPLAIN SELECT c from t2 where d < 202`


I think these are just a result of some outdated explain queries that were in those metrics file that no longer exist in the related YAML tests (the first query was changed recently to have an `explainContains` assertion from an `explain` assertion, and the later two queries don't exist in `record-type-key-tests.yamsql`).

**Review by normen662 — APPROVED** [review]
