### PR TITLE
Resolve #2934: translate IOException to/from RecordCoreException

### LINKED ISSUE #2934: Translate exception to/from Lucene API
Lucene API throws `IOException` whereas record layer API throws `RecordCoreException`.
In order to allow proper exception handling within each layer, translations between the two should be in place.

### PR DESCRIPTION
**Pull request by ohadzeliger**
This PR handles the exception translation between `RecordCoreException` and `IOException`. The idea is to throw `IOException` when returning from a Lucene-related API and to throw a `RecordCoreException` when returning from a record layer API.
Additionally (and with relation to #2924)  testing for proper exception handling is added. Since #2924 removed the exception injection in Lucene stack, the tests can be expected to predict the behavior under all circumstances.
Two new tests were added:
- `FDBLuceneIndexFailureTest` takes a few tests from `FDBLuceneIndexTest` and runs them through failure injection. These tests run through compete flow , like `scan index` and `save record`
- `FDBDirectoryFailuresTest` takes a few tests from `FDBDirectoryTest` and runs them through failure injection. These tests are directly running features of the FDBDirectory.

This PR leaves a few things for future Prs in the interest of time:
- Additional tests will be added
- The injection mechanism for the `MockedFDBDirectory` will be simplified

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java [hunk 1]
```diff
@@ -524,7 +529,9 @@ private CompletableFuture<byte[]> readBlock(@Nonnull IndexInput requestingInput,
             ));
         } catch (ExecutionException e) {
             // This would happen when the cache.get() fails to execute the lambda (not when the block's future is joined)
-            throw new RecordCoreException(e.getCause());
+            final RecordCoreException recordCoreException = new RecordCoreException(e.getCause());
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:532]: Should this use `CompletionExceptionLogHelper.asCause()` ?

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java [hunk 2]
```diff
@@ -129,11 +135,15 @@ public long getChecksum() {
...
-        crc.update(b);
-        currentSize++;
-        flushIfFullBuffer();
+    public void writeByte(final byte b) throws IOException {
+        try {
+            buffer.put(b);
+            crc.update(b);
+            currentSize++;
+            flushIfFullBuffer();
+        } catch (RecordCoreException ex) {
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:144]: Can that happen here?

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java [hunk 3]
```diff
@@ -148,16 +158,20 @@ void setExpectedBytes(@Nonnull final PrefetchableBufferedChecksumIndexInput inpu
...
+                LOGGER.trace(getLogMessage("copy bytes",
+                        LuceneLogMessageKeys.INPUT, input,
+                        LuceneLogMessageKeys.BYTE_NUMBER, numBytes));
+            }
+            // This is an attempt to pre-fetch blocks to speed up large copies (Segment Merge Process)
+            if (input instanceof PrefetchableBufferedChecksumIndexInput) {
+                setExpectedBytes((PrefetchableBufferedChecksumIndexInput)input, numBytes);
+            }
+            super.copyBytes(input, numBytes);
+        } catch (RecordCoreException ex) {
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:172]: Can that happen here?

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java [hunk 4]
```diff
@@ -169,27 +183,31 @@ public void copyBytes(@Nonnull final DataInput input, final long numBytes) throw
...
+                int toWrite = Math.min(
+                        length - bytesWritten, // the total leftover bytes to write
+                        (blockSize - buffer.position()) // the free space in this buffer
+                );
+                buffer.put(bytes, bytesWritten + offset, toWrite);
+                bytesWritten += toWrite;
+                currentSize += toWrite;
+                flushIfFullBuffer();
+            }
+        } catch (RecordCoreException ex) {
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:205]: Can that happen here?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java [hunk 5]
```diff
@@ -0,0 +1,248 @@
+/*
+ * FDBDirectoryTest.java
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java:2]:
```suggestion
 * FDBDirectoryFailuresTest.java
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java [hunk 6]
```diff
@@ -0,0 +1,192 @@
+/*
+ * MockedFdbDirectory.java
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java:2]:
```suggestion
 * MockedFDBDirectory.java
```

**Review by MMcM — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java]: Yeah, that looks good. It is not identical behavior (the suppressed exceptions get added to the cause rather than to the `RecordCoreException`) but I think this makes sense.
Done.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java (hunk 2 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:144]: Looks like it:
```
FDBIndexInput.writeByte -> 
flushIfFullBuffer ->
flush ->
fdbDirectory.writeData ->
agilityContext.set ->
agilityContext.accept ->
commitIfNeeded ->
commitNow -> 
commit ->
LuceneConcurrency.asyncToSync
```

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java (hunk 3 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:172]:
```
FDBIndexOutput.copyBytes ->
setExpectedBytes ->
PrefetchableBufferedChecksumIndexInput.setExpectedBytes ->
FDBIndexInput.getBlock ->
getFileReference ->
fdbDirectory.asyncToSync
```

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java (hunk 4 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBIndexOutput.java:205]:
```
FDBIndexOutput.writeBytes ->
flushIfFullBuffer ->
```
Then similar to above in `writeByte`

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java (hunk 5 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java]: Done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java (hunk 6 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java]: Done.

**Review by MMcM — APPROVED** [review]
