### PR TITLE
Fix for Lucene block leaks on file deletion

### LINKED ISSUE #3550: Lucene data blocks are leaking when files are deleted
Lucene files are leaking blocks when deleted. There seem to be dangling blocks that remain that belong to no valid file.

### PR DESCRIPTION
**Pull request by ohadzeliger**
The source of the leaking data blocks has been found and fixed.
Added more tests to verify the leakage was fixed directly as well as an addition to the `LuceneIndexTestValidator` to get some additional coverage "for free" whenever we use it in other tests.

Resolves #3550

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java [hunk 1]
```diff
@@ -741,8 +742,8 @@ protected boolean deleteFileInternal(@Nonnull Map<String, FDBLuceneFileReference
         if (fieldInfosStorage.delete(id)) {
             agilityContext.clear(fieldInfosSubspace.pack(id));
         }
-        // Nothing stored here currently.
-        agilityContext.clear(dataSubspace.subspace(Tuple.from(id)).range());
+        // Clear all data blocks for the file
+        agilityContext.clear(dataSubspace.subspace(Tuple.from(value.getId())).range());
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java]: Perhaps also worth renaming `value` to `fileReference`

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java [hunk 2]
```diff
@@ -132,14 +136,74 @@ void validate(Index index, final Map<Tuple, ? extends Map<Tuple, Tuple>> expecte
                     .collect(Collectors.toList());
             if (partitionHighWatermark > 0) {
                 validatePartitionedGroup(index, universalSearch, allowDuplicatePrimaryKeys, groupingKey, partitionLowWatermark, partitionHighWatermark, records, missingDocuments);
+                validatePartitionedDanglingBlocks(index, groupingKey);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java]: Why do this at this level, rather than inside the existing `validatePartitionedGroup`/`validateUnpartitionedGroup` which already cover iterating over the partitions, if appropriate?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java [hunk 3]
```diff
@@ -251,4 +253,75 @@ private void assertMetricCountAtMost(StoreTimer.Event metric, int maximumValue)
         assertThat("Metric " + metric + " should be called at most " + maximumValue + " times",
                 timer.getCount(metric), lessThanOrEqualTo(maximumValue));
     }
+
+    @Test
+    public void testDataBlocksProperlyCleared() throws Exception {
+        // Create a file with data blocks
+        long fileId = 1L;
+        FDBLuceneFileReference reference = new FDBLuceneFileReference(fileId, 100, 100, 1024);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java:261]: These tests are using lower-level, kind of internal aspects of `FDBDirectory`, perhaps it would be better to use public methods like `createOutput`, and `deleteFile`, and then assert that there is nothing in the `DATA` subspace. You still have to look at the raw data in FDB, so maybe not a big difference.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java [hunk 4]
```diff
@@ -741,8 +742,8 @@ protected boolean deleteFileInternal(@Nonnull Map<String, FDBLuceneFileReference
         if (fieldInfosStorage.delete(id)) {
             agilityContext.clear(fieldInfosSubspace.pack(id));
         }
-        // Nothing stored here currently.
-        agilityContext.clear(dataSubspace.subspace(Tuple.from(id)).range());
+        // Clear all data blocks for the file
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:745]: Also, confirming that `LuceneIndexMaintenanceTest` fails without this change, but with the new assertions in `LuceneIndexTestValidator`, correct?

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java]: Done.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java (hunk 4 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:745]: Yes, undoing the fix with the additional assertions in the validator causes a bunch of failures, looking like: 
```
Found orphaned data blocks for file IDs: (388, 198), (422, 37), (388, 197), (422, 38), (388, 200), (422, 35), (229, 0), (388, 199), (422, 36), (388, 202), (422, 41), (388, 201), (422, 42), (388, 204), (422, 39), (388, 203), (422, 40), (388,
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java (hunk 2 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java]: Based on the comment above `A broad validation of the lucene index`, I thought that was the original intent - for some set of validations that can be made somewhat modular. Either way would be good. Changed.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java (hunk 3 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java:261]: Yes, these are the lower-level tests that assert that the fix works, quite directly. The `TestValidator` provides more of a broad functional coverage. I thought this is a good coverage.
