### PR TITLE
Fixes #2813: Fail fast when Batch GRV Rate Limit Exceeded

### LINKED ISSUE #2813: Lucene tests sometimes stall until they timeout
Specifically some people have noticed that `LuceneIndexTest.fullDeleteHelper` times out after 5 minutes rather than completing, but it's normal runtime is less than 500ms.

Similarly the newly added  `LuceneIndexMaintenanceTest.concurrentStoreTest` can experience a similar issue.

### PR DESCRIPTION
**Pull request by ScottDugas**
Loading the metadata version key does not seem to throw Batch GRV rate limit exceeded, while other operations on the same transaciton do. Instead it stalls forever, and the tests end up timing out at the junit level.
This change introduces a new combine that will fail when the loading the record store state fails, instead of waiting forever for the metadata version to be loaded.

### CODE REVIEW

File: fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java [hunk 1]
```diff
@@ -945,6 +945,38 @@ private static RuntimeException getRuntimeException(@Nonnull Throwable exception
...
+     * @param <R> the result type for the returned future
+     *
+     * @return a future that fails with one of the exceptions from {@code future1} or {@code future2} if either of those
+     * failed, or the result of applying {@code combiner} to their results if both succeeded.
+     */
+    public static <T, U, R> CompletableFuture<R> combineAndFailFast(CompletableFuture<T> future1,
+                                                                    CompletableFuture<U> future2,
+                                                                    BiFunction<T, U, R> combiner) {
+        return CompletableFuture.anyOf(future1, future2).thenCompose(vignore -> {
+            // We know at least one of them completed
```
Comment (alecgrieser) [inline fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java:969]: We actually know that one of them completed _successfully_, because `thenCompose` only runs on successful completion of a future. I believe that the rest of the logic in the function should work, in that if one future completes successfully in more-or-less the same time as the other completes exceptionally, then we could go down one of the two cases below.

The strongest case for this is probably that if one of the futures completes unsuccessfully while the other hangs, then the `.anyOf` will complete with the exception from the one that has completed, so the end result will be an exceptional future.

**Review by alecgrieser — APPROVED** [review]
