### PR TITLE
Fix internal errors from version queries - Part 2

### LINKED ISSUE #3796: Version information can lead to internal errors when part of certain joins
The row version pseudo-column is a bit special, in that it results in a value being added to a type that is not present in the original type. We model this with a special `VersionValue` type that must be placed on top of an `FDBQueriedRecord`.

However, there are certain plan transformations that can result in expressions that break that assumption. For example, any three-play way join:

```sql
SELECT A."__ROW_VERSION" AS aVersion, B."__ROW_VERSION" AS bVersion, C."__ROW_VERSION" AS cVersion
  FROM A, B, C
```

In this case, the problem arises because the `PartitionSelect` rule will try and rewrite the join, which in turn results in an expression like:

```sql
SELECT T1."__ROW_VERSION" AS aVersion, T2."__ROW_VERSION" AS bVersion, C."__ROW_VERSION" AS cVersion
   FROM (SELECT (A.*) AS T1, (B.*) AS T2 FROM A, B), C
```

And the `__ROW_VERSION` does not survive being pulled through the sub-select. In this case, we get a `ClassCastException` from here: https://github.com/FoundationDB/fdb-record-layer/blob/65b4806cc0943aaa50817ec42f8690bca430b3e3/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java#L111

However, in other queries, we sometimes get `NullPointerExceptions`s. For instance, in certain in join queries, rewriting the predicate as an IN results in a similar transformation.

### PR DESCRIPTION
**Pull request by alecgrieser**
In version 4.9, we introduced a new pseudo-field, the `__ROW_VERSION`, which effectively pushed down the concept from the relational layer down into the planner level. See: #3809. It would not have been backwards compatible to start using this field right away, as any plans which attempted to reference the pseudo-field would fail if executed against older instances. For that reason, it only introduced the new field, but it didn't make use of it.

This fixes #3796 by using the new `__ROW_VERSION` field during queries instead of the `VersionValue`. This can then be correctly handled by `PartitionBinarySelectRule`, which was ultimately repsonsible for the internal error that we saw by allowing us to more reliably treat it as just another field.

We can't remove the `VersionValue` yet. We should be able to once we no longer want to support plans from 4.9 or older, which will still generate plans with `VersionValue`s in them.

This is a breaking change in the following sense: because it makes use of things that were introduced in 4.9.1.0, this cannot be used with older versions. Users must be sure to upgrade any servers that might deserialize plans generated by this version to 4.9 before updating to this version.

This change was previously introduced with #3800. That was backed out by #3870 which fixed a bug that was previously unknown relating to record scans. As a result, this change is only fully compatible in mixed mode with version 4.9.4.0 or later. If none of the queries involve record scans, it should be compatible with all 4.9 versions.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java [hunk 1]
```diff
@@ -209,7 +210,7 @@ public VersionFn() {
 
     @Nonnull
     private static Value encapsulate(@Nonnull final List<? extends Typed> arguments) {
-        final var childQuantifiedRecordValue = (QuantifiedRecordValue)Iterables.getOnlyElement(arguments);
-        return new VersionValue(childQuantifiedRecordValue);
+        final var childRecordValue = Iterables.getOnlyElement(arguments);
+        return FieldValue.ofFieldNameAndFuseIfPossible((Value) childRecordValue, PseudoField.ROW_VERSION.getFieldName());
```
Comment (hatyo) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java:214]: It seems that `VersionValue` is not used anymore, can you please delete this class, and move the `VersionFn` and this encapsulator a util class?

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java:214]: We can't delete `VersionValue` yet. We still need it when deserializing plans that came from an older version of the planner, as `VersionValue`s are baked into the plans

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java:214]: I've filed #3945 to remember to clean this up in the future
