### PR TITLE
Fixes #548: Fix concurrency issues with MapPipelinedCursor.close

### LINKED ISSUE #548: testOrQuery5WithLimits intermittently fails with a NoSuchElementException
The `testOrQuery5WithLimits` test has intermittently failed with `NoSuchElementException` trying to pop from the queue:

```
10:36:59 com.apple.foundationdb.record.provider.foundationdb.query.FDBOrQueryToUnionTest > testOrQuery5WithLimits(int)[1] FAILED
10:36:59     java.util.NoSuchElementException
10:36:59         at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
10:36:59         at java.util.ArrayDeque.remove(ArrayDeque.java:452)
10:36:59         at com.apple.foundationdb.record.cursors.MapPipelinedCursor.close(MapPipelinedCursor.java:148)
10:36:59         at com.apple.foundationdb.record.cursors.MapCursor.close(MapCursor.java:113)
10:36:59         at com.apple.foundationdb.record.provider.foundationdb.cursors.MergeCursorState.close(MergeCursorState.java:97)
10:36:59         at java.util.ArrayList.forEach(ArrayList.java:1257)
10:36:59         at com.apple.foundationdb.record.provider.foundationdb.cursors.MergeCursor.close(MergeCursor.java:349)
10:36:59         at com.apple.foundationdb.record.provider.foundationdb.cursors.UnorderedUnionCursor.close(UnorderedUnionCursor.java:58)
10:36:59         at com.apple.foundationdb.record.cursors.FilterCursor.close(FilterCursor.java:122)
10:36:59         at com.apple.foundationdb.record.cursors.RowLimitedCursor.close(RowLimitedCursor.java:126)
10:36:59         at com.apple.foundationdb.record.RecordCursorIterator.close(RecordCursorIterator.java:149)
10:36:59         at com.apple.foundationdb.record.provider.foundationdb.query.FDBOrQueryToUnionTest.testOrQuery5WithLimits(FDBOrQueryToUnionTest.java:416)
```

It is referencing this part of the code here:

https://github.com/FoundationDB/fdb-record-layer/blob/cb1fe996d703ab0c661844c6957f5e55e5e0a7ca/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java#L141-L155

In particular, it's the `remove` call that is causing problems. As can be seen, the remove call is guarded with an `isEmpty` check, which would seem to suggest that the problem has something to do with concurrent accesses to this data structure (which is probably at least partially why the test is intermittent). But the underlying data structure, an `ArrayDeque` is not thread safe: https://docs.oracle.com/javase/8/docs/api/java/util/ArrayDeque.html So, presumably, we need some kind of synchronization mechanism here?

### PR DESCRIPTION
**Pull request by ScottDugas**
The underlying issue is that multiple threads are interacting with the (non-thread-safe) queue at the same time, in complex ways. We could add `synchronized` to a `close` and `onNext`, (or some part of onNext), but instead I changed the cleanup around so that it only interacts with the pipeline in a single chain of futures.
The other change is the introduction of the `nextFuture` field, which removes the code that assumes that the pipeline will be non-empty, this seems like a good change to have, even if the other change makes it unnecessary.

I tried to do some trickery around how it interacts with the queue to make sure it handles an empty queue correctly, but since `ArrayDeque` is not thread safe, that resulted in `close` getting into an infinite loop with an-emptyable queue. I left the first attempt there as the first commit in this PR, although I think none of the code change remains.

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java [hunk 1]
```diff
@@ -1268,4 +1278,58 @@ void asStreamTest() {
 
     }
 
+    @RepeatedTest(100)
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java:1281]: Opening the draft PR with this repetition, but I'm going to remove it before merging, as it seems excessive.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java [hunk 2]
```diff
@@ -90,15 +93,17 @@ public CompletableFuture<RecordCursorResult<V>> onNext() {
 
     @Override
     public void close() {
-        while (!pipeline.isEmpty()) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java:93]: Should we do the same thing to the `FlatMapPipelinedCursor`, which I believe can hit similar issues?

**Review by alecgrieser — APPROVED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java:93]: I filed a new issue about this: #2953

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java [hunk 3]
```diff
@@ -77,8 +81,7 @@ public CompletableFuture<RecordCursorResult<V>> onNext() {
             return CompletableFuture.completedFuture(nextResult);
         }
         return AsyncUtil.whileTrue(this::tryToFillPipeline, getExecutor())
-                // pipeline will necessarily contain something if we stopped looping, so pipeline.remove() is nonnull
-                .thenCompose(vignore -> pipeline.peek()) // future should already be (nearly) ready if we stopped looping
+                .thenCompose(vignore -> pipeline.peek())
                 .thenApply(result -> {
                     if (result.hasNext()) {
```
[the remark this answers is not in the document]
Comment (ScottDugas) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/MapPipelinedCursor.java:86]: Added back a comment: https://github.com/FoundationDB/fdb-record-layer/pull/2955
I believe it was removed when I introduced `nextFuture`, but that didn't work, so I switched back to interacting with `pipeline`, and didn't add a comment back. I tried to thoroughly cover why the pipeline will not be empty at either of those situations.
