### PR TITLE
Fix case-sensitivity handling

### LINKED ISSUE #3513: Handle case-sensitivity option `CASE_SENSITIVE_IDENTIFIERS` correctly
The `CASE_SENSITIVE_IDENTIFIERS` option controls how the system processes SQL identifiers based on case sensitivity. When enabled, unquoted identifiers are processed exactly as written, preserving their original case. When disabled, unquoted identifiers are treated case-insensitively, while double-quoted identifiers always retain their exact case regardless of the setting.

Currently, this option suffers from implementation issues in the codebase where it is not handled correctly or consistently applied throughout the system. Additionally, the testing infrastructure lacks proper support for validating this functionality, making it difficult to verify correct behavior across both DDL and DQL operations. These problems prevent reliable case-sensitivity behavior and hinder comprehensive testing of the feature.

### PR DESCRIPTION
**Pull request by hatyo**
This PR addresses the correct handling of `CASE_SENSITIVE_IDENTIFIERS` throughout the codebase by fixing multiple issues where this option was previously ignored during parsing, logical plan generation, and `SchemaTemplate` interactions. The implementation ensures consistent case-sensitivity behavior across all components that process SQL identifiers.

The PR also enhances both testing frameworks to properly support this functionality. The JUnit test framework now accepts `Options` when performing DDL operations through the custom `Extension`s for database, schema template, and schema creation, enabling comprehensive testing scenarios.

Additionally, the YAML test framework introduces file-wide connection `Options` that influence how schema template DDL statements are parsed and persisted, while allowing developers to test various case-sensitivity scenarios by contrasting file-wide Options with block-specific Options for thorough validation coverage.

This fixes #3513, and #3498.

### CODE REVIEW

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java [hunk 1]
```diff
@@ -42,17 +43,38 @@
...
+        try {
+            if (blockKey.equals(PreambleBlock.OPTIONS)) {
+                return Optional.of(PreambleBlock.parse(lineNumber, entry.getValue(), executionContextBuilder));
+            }
+        } catch (Exception e) {
+            throw YamlExecutionContext.wrapContext(executionContextBuilder.getResourcePath(), e,
+                    () -> "Error parsing block at line " + lineNumber, blockKey, lineNumber);
+        }
+        return Optional.empty();
+    }
```
Comment (g31pranjal) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java]: I think I am a bit concerned about the out-of-the-ordinary "behaviour" of how we deal with the preamble block. I am a bit afraid that this could lead to other cases where "parsing" and "execution" of a block is different from the usual. Minor, but it seems to replicate a bit of logic too from the general parsing.

It would be great if we could follow the general notion of "parsing" and "execution".

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java [hunk 2]
```diff
@@ -59,43 +62,55 @@ public final class YamlRunner {
...
+                // Step 1/3: process preamble block (if any)
+                Optional<PreambleBlock> preambleBlockMaybe = Optional.empty();
+                if (!regions.isEmpty()) {
+                    preambleBlockMaybe = Block.parsePreambleBlock(regions.get(0), executionContextBuilder);
+                    preambleBlockMaybe.ifPresent(preambleBlock ->
+                            executionContextBuilder.setConnectionOptions(preambleBlock.getBlockOptions().getOptions()));
+                }
+
+                // Step 2/3: build the YAML execution context, potentially with file-specific options set in the preamble block
+                executionContext = executionContextBuilder.build();
```
Comment (g31pranjal) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java]: It seems to me that step 1/3 is `parse` of PreambleBlock, while 2/3 is `execute` of it which ends up changing the underlying `ExecutionContext` by adding CONNECTION_OPTION to it (which could then be overridden by test_block options). I think my suggestion won't work with builder() pattern as the same ExecutionContext is shared by all the blocks in parse-time. However, we already do "add to" the executionContext, as in `TransactionSetupsBlock.java`. I believe it could be the same for the PreambleBlock as well!

In general, is there any specific reason to deal with PreambleBlock separately ? My understanding is that we may want to stick to the existing paradigm of `parse` and `execute` as much as possible - as it maintain homogeneity. And, it feels this use-case could be covered well.

File: yaml-tests/src/test/resources/case-sensitivity.yamsql [hunk 3]
```diff
@@ -0,0 +1,153 @@
+#
+# case-sensitivity.yamsql
+#
+# This source file is part of the FoundationDB open source project
+#
+# Copyright 2021-2024 Apple Inc. and the FoundationDB project authors
```
Comment (g31pranjal) [inline yaml-tests/src/test/resources/case-sensitivity.yamsql]: Is it possible somehow to sanitize this everywhere? I see a couple of places being changed to 2015-2025, which we probably want to do here as well?

File: yaml-tests/src/test/resources/case-sensitivity.yamsql [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+        values (10, 'blah'),
+               (20, 'bleh')
+    - query: insert into table2
+        values (10, 100, 10),
+               (20, 100, 20),
+               (60, 200, 60),
+               (70, 200, 70)
+---
+test_block:
+  name: case-sensitivity-on
```
Comment (g31pranjal) [inline yaml-tests/src/test/resources/case-sensitivity.yamsql:60]: Do you think it makes sense to add tests here that tests with temporary functions as well? These tests seem to be a good contender for using the new transactions_setup_block that Scott introduced recently to create a temporary function inside the transaction.

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java (hunk 2 above)
Comment (hatyo) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java]: I initially attempted to make `executionContext` immutable by using a builder pattern instead of direct state modification. However, this approach proved overly complex, so I reverted to the original design and simply added an additional setter method for configuring connection options.

Additionally, I refactored `PreambleBlock` to better align with the existing block parsing architecture. As you noted, this makes it more consistent and streamlined with the rest of the codebase.

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java (hunk 1 above)
Comment (hatyo) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java]: See my other comment.

File: yaml-tests/src/test/resources/case-sensitivity.yamsql (hunk 4 above)
Comment (hatyo) [reply yaml-tests/src/test/resources/case-sensitivity.yamsql:60]: Nice idea, let me do that after bringing in this PR.

File: yaml-tests/src/test/resources/case-sensitivity.yamsql (hunk 3 above)
Comment (hatyo) [reply yaml-tests/src/test/resources/case-sensitivity.yamsql]: https://github.com/FoundationDB/fdb-record-layer/issues/3527

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/PreambleBlock.java [hunk 5]
```diff
@@ -1,9 +1,9 @@
 /*
- * FileOptions.java
+ * NoOpBlock.java
```
Comment (g31pranjal) [inline yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/PreambleBlock.java]: filename

**Review by g31pranjal — CHANGES_REQUESTED** [review]
Pretty minor request!

File: yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/PreambleBlock.java (hunk 5 above)
Comment (hatyo) [reply yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/PreambleBlock.java]: nice catch. Done.
