### PR TITLE
Resolves #2242: COALESCE does not work with non-scalar types

### LINKED ISSUE #2242: `COALESCE` does not work with non-scalar types
`COALESCE` has proper semantics for scalar and complex types. However currently it only works with scalar types. This should be fixed.

### PR DESCRIPTION
**Pull request by g31pranjal**
Resolves #2242

### CODE REVIEW

File: fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/VariadicFunctionValueTest.java [hunk 1]
```diff
@@ -232,41 +280,53 @@ public Stream<? extends Arguments> provideArguments(final ExtensionContext conte
                     Arguments.of(List.of(DOUBLE_3, DOUBLE_3), new VariadicFunctionValue.CoalesceFn(), 3.0, false),
                     Arguments.of(List.of(STRING_3, STRING_3), new VariadicFunctionValue.CoalesceFn(), "c", false),
                     Arguments.of(List.of(BOOLEAN_2, BOOLEAN_2), new VariadicFunctionValue.CoalesceFn(), true, false),
+                    Arguments.of(List.of(LIST_INT_1, LIST_INT_1), new VariadicFunctionValue.CoalesceFn(), List.of(1, 2, 3), false),
+                    Arguments.of(List.of(RECORD_1, RECORD_1), new VariadicFunctionValue.CoalesceFn(), buildMessageForRecordType(List.of("a", 1, 1.0f)), false),
```
Comment (hatyo) [inline fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/VariadicFunctionValueTest.java:284]: could you please put this `buildMessageForRecordType(List.of("a", 1, 1.0f))` in a method?

Comment (g31pranjal) [reply fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/VariadicFunctionValueTest.java:284]: done

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java [hunk 2]
```diff
@@ -115,7 +117,7 @@ public Value getChild() {
     @Nonnull
     @Override
     public PromoteValue withNewChild(@Nonnull final Value newChild) {
-        return new PromoteValue(inValue, promoteToType, promotionTrie);
+        return new PromoteValue(newChild, promoteToType, promotionTrie);
```
Comment (hatyo) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java:120]: Nice catch.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java [hunk 3]
```diff
@@ -186,8 +188,7 @@ public static MessageHelpers.CoercionTrieNode computePromotionsTrie(@Nonnull fin
         }
 
         if (currentType.isPrimitive()) {
-            SemanticException.check(targetType.isPrimitive(), SemanticException.ErrorCode.INCOMPATIBLE_TYPE);
-            if (!isPromotionNeeded(currentType, targetType)) {
+            if (currentType.getTypeCode() != Type.TypeCode.NULL && !isPromotionNeeded(currentType, targetType)) {
```
Comment (hatyo) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java:191]: Please move condition `currentType.getTypeCode() != Type.TypeCodeNULL` to `isPromotionNeeded` and restore the check.

**Review by hatyo — CHANGES_REQUESTED** [review]

**Comment by hatyo** [comment]
LGTM, with just a minor comment related to code-tidiness. Great work.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java (hunk 3 above)
Comment (g31pranjal) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java:191]: Moved the condition, but cannot put back the condition without explicitly testing if the `currentType` in NULL. I think the semantic check here is a bit redundant because the coercion will promotion will anyways return null if not possible.

Comment (g31pranjal) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PromoteValue.java:191]: semantic check also happens in `isPromotionNeeded` so indeed redundant.

**Review by hatyo — APPROVED** [review]

**Review by hatyo — APPROVED** [review]
