### PR TITLE
Resolve #1415: Caches the first and last block (checksum)

### LINKED ISSUE #1415: Either cache both the first and last block in a segment or remove the checksum check in read path
Currently we cache the first block for each segment in the read path in a parallel, asynchronous manner knowing that we will have to read the first block.  Unfortunately, we also are guaranteed to read the last block during a request into the segment as well.

Two options:

1) Cache the last block as well as the first block during listAllFiles()
2) Remove the checksum check in the Lucene50PostingsReader.

Even if we parallelize the execution of the segment reads, it would be nice to have those blocks pre-warmed.

15:08:17.386 [Test worker] ERROR com.apple.foundationdb.record.lucene.directory.FDBDirectory - actual seek -> resource=_b.cfs, block=28
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
	at com.apple.foundationdb.record.lucene.directory.FDBDirectory.lambda$readBlock$2(FDBDirectory.java:245)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
	at com.apple.foundationdb.record.lucene.directory.FDBDirectory.readBlock(FDBDirectory.java:241)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.seek(FDBIndexInput.java:137)
	at org.apache.lucene.codecs.CodecUtil.retrieveChecksum(CodecUtil.java:486)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.<init>(Lucene50PostingsReader.java:84)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat.fieldsProducer(Lucene50PostingsFormat.java:442)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.<init>(PerFieldPostingsFormat.java:283)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProducer(PerFieldPostingsFormat.java:363)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:113)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:172)
	at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:214)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:106)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:525)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:103)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:79)
	at com.apple.foundationdb.record.lucene.LuceneRecordCursor.getIndexReader(LuceneRecordCursor.java:244)
	at com.apple.foundationdb.record.lucene.LuceneRecordCursor.performScan(LuceneRecordCursor.java:249)

### PR DESCRIPTION
**Pull request by jleach4**
The read pipeline for Lucene will always read the first (already cached) and the last block.  This PR attempts to cache that last block when germane during listAll (always called by directory in Lucene).

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java [hunk 1]
```diff
@@ -288,6 +288,10 @@ private void record(StoreTimer.Event event, long durationNanos) {
             if (name.endsWith(".cfs") || name.endsWith(".si") || name.endsWith(".cfe")) {
                 try {
                     readBlock(name, CompletableFuture.completedFuture(fileReference), 0);
+                    int lastBlock = (int) (fileReference.getSize() / fileReference.getBlockSize());
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:291]: Probably deserves a comment on why this is a worthwhile thing to do.

**Review by MMcM — CHANGES_REQUESTED** [review]

**Review by sophiabuell — APPROVED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java (hunk 1 above)
Comment (jleach4) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:291]: :)

Comment (jleach4) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java:293]: Added Comment

**Review by MMcM — APPROVED** [review]

**Review by sophiabuell — APPROVED** [review]
