### PR TITLE
Resolve #2731: Reproduce abandoned FileLock due to conflict issue

### LINKED ISSUE #2731: Reproduce abandoned FileLock due to conflict issue
Recreate the scenario of: 
- Lucene file lock is successfully acquired. 
- Another transaction fails with conflict while attempting to release the file lock. 
With a recent code, the lock is released during the directory's close.

### PR DESCRIPTION
**Pull request by jjezra**
Attempt to cause a conflict and abandon a file lock. 
The test is failing for 3.4.485.0

### CODE REVIEW

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 1]
```diff
@@ -1344,5 +1351,118 @@ void luceneOnlineIndexingTestTerribleRebalance2ndChance() {
...
+                }).join();
+                tr.set(conflictKey, Tuple.from(100, 20).pack());
+                say("main thread set agile:    " + Arrays.toString(conflictKey));
+            });
+
+
+            // Cause conflict, and wait for it
+            s1.release();
+            acquire(s2);
+            s2.release();
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1417]: Because of the semaphores, I don't think you don't actually have multiple threads (which makes the test more deterministic, which is great), but I think it also means you could move the code for `conflictThread` here and remove all the semaphores.

Although you are adding a nested context, so perhaps putting it in a `Runnable` (or helper function) outside the `try (context = fdb.openContext)` above would help reduce the possibility of accidentally using the wrong context. The same probably goes for the `agile.accept`

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 2]
```diff
@@ -1344,5 +1351,118 @@ void luceneOnlineIndexingTestTerribleRebalance2ndChance() {
...
+
+    private void say(String msg) {
+        LOGGER.debug("::::::" + msg);
+    }
+
+    private void acquire(Semaphore semaphore) {
+        try {
+            semaphore.acquire();
+        } catch (InterruptedException ex) {
+            throw new RuntimeException(ex);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1464]: Not super important because it's a test, but generally, you should always re-interrupt the current thread if you catch `InterruptedException`, and it's good to be consistently in that habit.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 3]
```diff
@@ -1344,5 +1351,118 @@ void luceneOnlineIndexingTestTerribleRebalance2ndChance() {
             assertTrue(Terriblerebalnce2ndChanceIndexMaintainer.isSecondPass);
         }
     }
+
+
+    @Test
+    void testConflictWithLock() throws IOException, InterruptedException {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1357]: This test has a bunch of moving pieces, for posterity it would probably be good to comment exactly what is trying to happen here, something like:
> If the file lock gets a conflict while closing the lock, it should ensure that the lock is released either during it's close, or the directory's close so that future operations can continue.

Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1357]: Probably also worth adding some similar context to the Issue #2731 which currently has no description.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 4]
```diff
@@ -1344,5 +1351,118 @@ void luceneOnlineIndexingTestTerribleRebalance2ndChance() {
             assertTrue(Terriblerebalnce2ndChanceIndexMaintainer.isSecondPass);
         }
     }
+
+
+    @Test
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1356]: Moved to `LuceneIndexTest`, as `recordStore` is needed.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java (hunk 3 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1357]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java [hunk 5]
```diff
@@ -6063,4 +6068,92 @@ private void assertIndexEntryPrimaryKeyTuples(Set<Tuple> primaryKeys, RecordCurs
...
+            store.saveRecord(doc3);
+            context.commit();
+        }
+    }
+
+    private void testConflictWithLockAgileSet(AgilityContext agile1, Tuple conflictTuple) {
+        agile1.accept(aContext -> {
+            byte [] conflictKey = path.toSubspace(aContext).pack(conflictTuple);
+            final Transaction tr = aContext.ensureActive();
+            tr.get(conflictKey).thenApply(val -> null).join();
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java:6143]: Why have `.thenApply(val -> null)` here and below?

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java (hunk 5 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java]: Probably a leftover. Removed. 
✅

**Review by ScottDugas — APPROVED** [review]
