### PR TITLE
A couple of additions to FDBRecordContextConfig

### LINKED ISSUE #2115: Expose tags in FDBRecordContextConfig
Allow caller to specify string(s) to be placed in underlying transaction.

### LINKED ISSUE #2116: Expose conflict tracking to FDBRecordContextConfig
Allow caller to request that conflict keys are tracked by the underlying transaction and preserved in the process of throwing any not-committed exception.

### PR DESCRIPTION
**Pull request by MMcM**
* Resolves #2115: Add throttling tags to context config.
* Resolves #2116: Add optional conflict tracking to context config.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java [hunk 1]
```diff
@@ -597,6 +628,39 @@ public Builder setRecordContextProperties(@Nonnull final RecordLayerPropertyStor
...
+         */
+        public boolean isReportConflictingKeys() {
+            return reportConflictingKeys;
+        }
+
+        /**
+         * Set whether to report conflicting key rangs on commit conflict.
+         * @param reportConflictingKeys {@code true} to report conflicting keys
+         */
+        public void setReportConflictingKeys(final boolean reportConflictingKeys) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java:660]: Should these two new setters return `Builder`s to make them more fluent?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java [hunk 2]
```diff
@@ -597,6 +628,39 @@ public Builder setRecordContextProperties(@Nonnull final RecordLayerPropertyStor
...
+        public Set<String> getTags() {
+            return tags;
+        }
+
+        /**
+         * Set tags used for throttling.
+         * @param tags new set of tags
+         */
+        public void setTags(@Nonnull final Set<String> tags) {
+            this.tags = tags;
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java:645]: I guess I was a little surprised that the builder here took a `Set<String>` instead of having an `addTag` method. As written, it looks like this has the advantage that it doesn't need to allocate any objects if the (default) empty set is used, which nice, so maybe this is preferable.

Reading the docs, it also sounds like each transaction can have at most 5 tags, and each tag should be 16 characters or less. Given that FDB's own error handling here makes it hard to associate an error from option value validation with the origin, should this method validate the options (and throw if invalid)?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 3]
```diff
@@ -1397,4 +1427,31 @@ public RecordLayerPropertyStorage getPropertyStorage() {
...
+    @Nullable
+    public List<Range> getNotCommittedConflictingKeys() {
+        return notCommittedConflictingKeys;
+    }
+
+    @SuppressWarnings("PMD.CloseResource")
+    private CompletableFuture<Void> readConflictingKeys() {
+        notCommittedConflictingKeys = new ArrayList<>();
+        final Transaction tr = ensureActive();
+        tr.options().setReadSystemKeys();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1443]: Is this option necessary? I thought the special keyspace (i.e., the `\xff\xff` keyspace) didn't need it, unlike the non-special system keyspace (i.e., the `\xff` keyspace). I could have that wrong, though

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 4]
```diff
@@ -1397,4 +1427,31 @@ public RecordLayerPropertyStorage getPropertyStorage() {
...
+     * @return list of conflict ranges
+     */
+    @Nullable
+    public List<Range> getNotCommittedConflictingKeys() {
+        return notCommittedConflictingKeys;
+    }
+
+    @SuppressWarnings("PMD.CloseResource")
+    private CompletableFuture<Void> readConflictingKeys() {
+        notCommittedConflictingKeys = new ArrayList<>();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:1441]: It seems a bit strange that this sets the instance variable at the beginning of the method and then updates the instance variable asynchronously. It feels like this should have a local variable, and then when the async callback completes, ether it returns the list (and `commit()` sets the instance variable) or the instance variable gets set within this method. That would then mean that the `notCommittedConflictingKeys` variable would either be `null` or would contain a complete set of conflicts (rather than certain incorrect usage resulting in the viewer getting a non-`null` but incomplete set of conflicts).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 5]
```diff
@@ -462,6 +477,21 @@ public CompletableFuture<Void> commitAsync() {
                 return AsyncUtil.DONE;
             }
         });
+        if (config.isReportConflictingKeys()) {
+            // Do this before the close (below).
+            commit = MoreAsyncUtil.composeWhenCompleteAndHandle(commit, (v, ex) -> {
+                if (ex instanceof CompletionException) {
+                    final Throwable cause = ex.getCause();
+                    if (cause instanceof FDBException) {
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:485]: Is it guaranteed that the `commit` error is always a `CompletionExcpetion` wrapping an `FDBException`? Or should this use something like `FDBExceptions.getFDBCause()` to extract the causal `FDBException` (if any) from more complicated error hierarchies?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java [hunk 6]
```diff
@@ -462,6 +477,21 @@ public CompletableFuture<Void> commitAsync() {
...
+                        final FDBException fdbException = (FDBException)cause;
+                        if (FDBError.fromCode(fdbException.getCode()) == FDBError.NOT_COMMITTED) {
+                            return readConflictingKeys();
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java:488]: It would be nice to have a test of this. Something like a test that constructs two transactions with the appropriate options and then orchestrates a conflict and validates that the conflicting ranges read align

**Review by alecgrieser — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java (hunk 1 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java]: Yes, they should. Fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java (hunk 2 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java:654]: Added the validation. I have no objection to `addTag`, if that seems cleaner. I just imagined that they all happened at once.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 3 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java]: No, you're right. It isn't necessary.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 4 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java]: I switched it to a value-returning async method instead of that strange side-effecting one.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java (hunk 5 above)
Comment (MMcM) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java]: Even if it's guaranteed now, using that is more future proof. Fixed.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java (hunk 2 above)
Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContextConfig.java:654]: I think either is fine, really.

**Review by alecgrieser — APPROVED** [review]
