### PR TITLE
resolves #2846

### LINKED ISSUE #2846: DimensionsKeyExpression not handled enough by QueryToKeyMatcher
Given an index like
```
covering([[p1, p2, d1, d2, f1, f2] dimensions(2,2), v1] split 6)
```
with dimensions beneath key-with-value, `canDeleteWhere` for an equality comparison on `p1` fails.

It handles such a case at top-level, but not inside like that. It needs to be more like grouping, for the prefix key, which is what is matchable.

The specific error gets to `unexpected` because the key class isn't in `KNOWN_KEY_EXPRESSIONS`.

Also, the `toString` has `dimensions(2,2)2` for some reason.

### PR DESCRIPTION
**Pull request by g31pranjal**
resolves #2846

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/DimensionsKeyExpression.java [hunk 1]
```diff
@@ -55,15 +55,15 @@ public class DimensionsKeyExpression extends BaseKeyExpression implements KeyExp
...
+    private DimensionsKeyExpression(@Nonnull final KeyExpression wholeKey,
                                    final int prefixSize,
                                    final int dimensionsSize) {
         this.wholeKey = wholeKey;
         this.prefixSize = prefixSize;
         this.dimensionsSize = dimensionsSize;
     }
 
-    public DimensionsKeyExpression(@Nonnull RecordMetaDataProto.Dimensions dimensions) throws DeserializationException {
+    DimensionsKeyExpression(@Nonnull RecordMetaDataProto.Dimensions dimensions) throws DeserializationException {
```
Comment (g31pranjal) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/expressions/DimensionsKeyExpression.java:66]: final

File: fdb-record-layer-core/src/test/proto/test_records_multidimensional.proto [hunk 2]
```diff
@@ -29,7 +29,10 @@ import "record_metadata_options.proto";
 option (schema).store_record_versions = true;
 
 message MyMultidimensionalRecord {
-  optional string rec_domain = 1;
+  message domain_info {
+    optional string rec_domain = 1;
+  }
```
Comment (g31pranjal) [inline fdb-record-layer-core/src/test/proto/test_records_multidimensional.proto:34]: This change would have a test failing without the fix to `deleteWhere`

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java [hunk 3]
```diff
@@ -2986,9 +2986,9 @@ protected boolean planNestedFieldOrComponentChild(@Nonnull KeyExpression child,
             @Nullable ScoredMatch scoredMatch = maybeSortedMatch.apply(null);
             if (scoredMatch != null) {
                 ComparisonRanges nextComparisonRanges = scoredMatch.getComparisonRanges();
-                if (!comparisons.isEqualities() && nextComparisonRanges.getEqualitiesSize() > 0) {
-                    throw new Query.InvalidExpressionException(
-                            "Two nested fields in the same and clause, combine them into one");
+                if (comparisons.getUncommittedComparisonRanges().stream().anyMatch(range -> range.getRangeType() != ComparisonRange.Type.EQUALITY)
```
Comment (normen662) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java:2989]: maybe make an `isEqualities(form, to)` instead of using this stream expression twice (here and in `ComparisonRanges`)

**Review by normen662 — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java (hunk 3 above)
Comment (g31pranjal) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java]: done

**Review by MMcM — DISMISSED** [review]

**Review by normen662 — APPROVED** [review]
