### PR TITLE
Resolves #352: Set a default extension registry within an FDBMetaDataStore

### LINKED ISSUE #352: Set a default extension registry within an FDBMetaDataStore
User has to set the extensionRegistry in an FDBMetaDataStore to avoid null pointer exceptions if proto is version 3. This was discovered while working on issue #3 (PR #320). Lets have an issue to track setting a default extension registry within an FDBMetaDataStore to avoid every client having to do the same.

### PR DESCRIPTION
**Pull request by alecgrieser**
This creates a default extension registry that contains the extension options included in `record_metadata_options.proto`. Existing code that used an `FDBMetaDataStore` but did not set an extension registry will (a) in proto3, no longer throw a `NullPointerException` and (b) in proto2, process the `(record).usage` extension, which was not the case before.

For proto2, I think this leads to the following hypothetical situation: a user who had something like two message types defined, one called `RecordTypeUnion` and another called, say, `UnionDescriptor` where they had initially stored the meta-data using the `UnionDescriptor` message (using the `(record).usage = UNION` extension option) and then switched to using the `RecordTypeUnion` message without removing the old extension (and instead relying on the lack of extension processing to avoid a "duplicate union" conflict). I think this is rare enough to be discounted, but I wanted to bring it up as a potential pitfall of this change.

This resolves #352.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java [hunk 1]
```diff
@@ -179,13 +187,38 @@ public void setEvolutionValidator(@Nonnull MetaDataEvolutionValidator evolutionV
...
+     * if the provided registry does not at least register that extension, the {@code RecordMetaData} may
+     * fail to build.
+     * </p>
+     *
+     * @param extensionRegistry the extension registry used when parsing meta-data
+     */
     public void setExtensionRegistry(@Nullable ExtensionRegistry extensionRegistry) {
-        this.extensionRegistry = extensionRegistry;
+        if (extensionRegistry == null) {
+            this.extensionRegistry = DEFAULT_EXTENSION_REGISTRY;
```
Comment (amouehsan) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: When would we need to pass null to this method? This is already the default value of `this.extensionRegistry`. 

I actually think, probably instead, keep `this.extensionRegistry` nullable but with a default value of `DEFAULT_EXTENSION_REGISTRY`. Then users can use this method to unset it by passing null, if they truly need it (note that in past it was nullable any way, so it's not worst than before, but this way, it keeps the flexibility to behave the way it used to and also allows users to get the best out of your new change).

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java]: I guess the use case I was thinking of was someone who had set it to something else and then wanted to get back to the default value. But maybe that's not that compelling a use case.
