### PR TITLE
Resolve #2575: Lucene file lock may not be cleaned up in a failed merge

### LINKED ISSUE #2575: Lucene file lock may not be cleaned up in a failed merge
Related to: #2574
If there is a failure during merge, the file lock won't be cleaned up. Lucene has logic to take care of this, but care needs to be taken around the `AgilityContext`

### PR DESCRIPTION
**Pull request by jjezra**

### CODE REVIEW

**Review by ScottDugas — APPROVED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java [hunk 1]
```diff
@@ -57,7 +57,7 @@ public Lock obtainLock(final Directory dir, final String lockName) {
         return new FDBDirectoryLock(directory.getAgilityContext(), lockName, directory.fileLockKey(lockName), timeWindowMilliseconds);
     }
 
-    private static class FDBDirectoryLock extends Lock {
+    protected static class FDBDirectoryLock extends Lock {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java:60]: Spotbugs failed because you are now exposing a bunch of internal state.
Changing all the fields, and the constructor to `private` seems to fix the issue. I would do it as a suggested change, but I can't because you didn't change those lines.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

**Review by ScottDugas — APPROVED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryLockFactory.java:60]: Looks good to me.
