### PR TITLE
Fixes #1054: "make unbuilt index readable" exception blocks opening a record store

### LINKED ISSUE #1054: "make unbuilt index readable" exception blocks opening a record store
This happens when check version tries to `rebuildIndexWithNoRecord` but the index was not readable (probably related to reusing index name, also see #794 which was reverted)

There are two things need to be fixed:

1. In such situation it should mark the index to readable regardless

2. In any case, marking index as readable should not block the critical path (`checkVersion`), whose failure can people unable to do anything with the record store.

### PR DESCRIPTION
**Pull request by nblintao**
This happens when check version tries to `rebuildIndexWithNoRecord` but the index was not readable (probably related to reusing index name, also see #794 which was reverted)

There are two things need to be fixed:

1. In such situation it should mark the index to readable regardless

2. In any case, marking index as readable should not block the critical path (`checkVersion`), whose failure can people unable to do anything with the record store.

### CODE REVIEW

File: fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java [hunk 1]
```diff
@@ -913,6 +913,32 @@ public static void closeIterator(@Nonnull Iterator<?> iterator) {
         });
     }
 
+    /**
+     * Handle when <code>futureSupplier</code> has exception when supplying a future, or the future is completed
```
Comment (alecgrieser) [inline fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java:917]:
```suggestion
     * Handle when <code>futureSupplier</code> encounters an exception when supplying a future, or the future is completed
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java [hunk 2]
```diff
@@ -913,6 +913,32 @@ public static void closeIterator(@Nonnull Iterator<?> iterator) {
...
+     * exceptionally. Unlike the "handle" in CompletableFuture, <code>handlerOnException</code> is not executed if
+     * the future is successful.
+     * @param futureSupplier the supplier of future which need to be handled
```
Comment (alecgrieser) [inline fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java:920]:
```suggestion
     * @param futureSupplier the supplier of future which needs to be handled
```

File: fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java [hunk 3]
```diff
@@ -913,6 +913,32 @@ public static void closeIterator(@Nonnull Iterator<?> iterator) {
...
+     * @param handlerOnException the hanlder when the future has
```
Comment (alecgrieser) [inline fdb-extensions/src/main/java/com/apple/foundationdb/async/MoreAsyncUtil.java:921]: Looks like this sentence drops off half way

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 4]
```diff
@@ -3055,7 +3090,14 @@ public boolean isIndexDisabled(@Nonnull String indexName) {
                     Index index = indexItem.getKey();
                     List<RecordType> recordTypes = indexItem.getValue();
                     IndexState indexState = newStates.getOrDefault(index, IndexState.READABLE);
-                    work.add(rebuildOrMarkIndex(index, indexState, recordTypes, reason, oldMetaDataVersion));
+                    final CompletableFuture<Void> rebuildOrMarkIndexSafely = MoreAsyncUtil.handleOnException(
+                            () -> rebuildOrMarkIndex(index, indexState, recordTypes, reason, oldMetaDataVersion),
+                            exception -> {
+                                // If there is anything issue, simply mark the index as disabled without blocking checkVersion
+                                logExceptionAsWarn("unable build index", exception);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:3097]:
```suggestion
                                logExceptionAsWarn("unable to build index", exception);
```

It also seems like we might want to include things like the index name as a log key. Maybe `logExceptionAsWarn` should take a `KeyValueLogMessage` (and handle adding the log keys from the exception as well)?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 5]
```diff
@@ -3117,7 +3159,10 @@ private boolean areAllRecordTypesSince(@Nullable Collection<RecordType> recordTy
             }
         }
 
-        return markIndexReadable(index).thenApply(b -> null);
+        // The index states is supposed to be empty (i.e. readable) because this is a new index. But unfortunately, the
+        // index state is keyed by index name which can be reused. So we need to mark the index readable. In such case,
+        // the built range is unlikely to be full so we should force it.
+        return markIndexReadable(index, true).thenApply(b -> null);
```
Comment (alecgrieser) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:3165]: There's something about having this catch and then ignore the error that feels a little strange....

Given that we're going to ignore the results of doing the validation, it almost seems like we should call `uncheckedMarkIndexReadable`. I could see alternative arguments that we could, like, check there are no uniqueness violations or data in the index subspace or something and then mark it as `READABLE` (perhaps only in the error case) (and maybe it also should add the `\x00` to `\xff` range to the build space?).

I could also see an argument that if it encounters an error, it should mark the index as `DISABLED` and wait for a rebuild. Then we don't get the index right away (sad) but we also no longer block `checkVersion`.

Something about the extra flag to force marking it as readable doesn't quite seem right.

**Review by alecgrieser — CHANGES_REQUESTED** [review]
In addition to the comments I left in line, I feel like this should probably have a test. Either one that fully simulates the problem case here (adding and then removing and then adding back an index) or one that "cheats" by marking an index that "doesn't exist" as disabled and then adding the index to the meta-data in a subsequent operation.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 5 above)
Comment (nblintao) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:3165]: I didn't use `uncheckedMarkIndexReadable` mainly because I'd like it check and log exceptions even if not throw an exception.

I think " mark the index as DISABLED and wait for a **(manual, force)** rebuild" is an option. I just need to remove all my changes in `markIndexReadable` it will work like that. But that depends on how we see such error. If we think consider it as expected (even though not pleasant) as a side effect of reusing index name, I think it should better be working without manual intervention.

Comment (nblintao) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:3165]: Force build is not necessary. Just manual. So I think I'm fine with not marking index as readable, especially considering there may be underlying bugs that we need to be aware of.

**Comment by nblintao** [comment]
test this please

**Review by alecgrieser — APPROVED** [review]

**Review by MMcM — APPROVED** [review]
