### PR TITLE
Resolves #663: Enable the capability to add logging details to mapped exceptions

### LINKED ISSUE #663: Enable the capability to add logging details to mapped exceptions

### PR DESCRIPTION
**Pull request by dsimmen**

### CODE REVIEW

**Comment by dsimmen** [comment]
The PMD analyzer did not like the fact that LoggableException was not preserving the stack trace... https://pmd.github.io/pmd-6.10.0/pmd_rules_java_bestpractices.html#preservestacktrace ... and hence why Exception:initCause(cause) is being called...

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/LoggableTimeoutException.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+    /**
+     * Create an exception with the given sequence of key/value pairs.
+     * This will throw an {@link IllegalArgumentException} if <code>keyValues</code>
+     * contains an odd number of elements.
+     *
+     * @param cause cause of the exception
+     * @param keyValues loggable keys and values
+     *
+     * @see #addLogInfo(Object...)
+     */
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/LoggableTimeoutException.java]: No need to change anything, but for the future you might want to be aware of the `{@inheritDoc}` javadoc tag (see https://dzone.com/articles/inheriting-javadoc-method-comments)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java [hunk 2]
```diff
@@ -912,6 +913,7 @@ protected RuntimeException mapAsyncToSyncException(@Nonnull Throwable ex) {
             } catch (TimeoutException ex) {
                 if (timer != null) {
                     timer.recordTimeout(event, startTime);
+                    throw asyncToSyncExceptionMapper.apply(new LoggableTimeoutException(ex, "TimeLimit", timeout.getLeft(), "TimeUnit", timeout.getRight()), event);
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java]: Minor, but our "convention" for record layer logging keys is to be `lower_case` rather than `CamelCase` and, although we aren't really re-using these strings today, you may want to add `LogMessageKeys.TIME_LIMIT` and `LogMessageKeys.TIME_UNIT`.  At some point we really need to write down guidelines for exceptions and logging.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java [hunk 3]
```diff
@@ -130,6 +131,13 @@ public FDBStoreRetriableException(FDBException cause) {
     }
 
     public static RuntimeException wrapException(@Nonnull Throwable ex) {
+        //transfer any logging details into mapped exception
+        Object[] logInfo;
+        if (ex instanceof LoggableKeysAndValues) {
+            logInfo = ((LoggableKeysAndValues)ex).exportLogInfo();
+        } else {
+            logInfo = new Object[0];
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBExceptions.java]: Minor, but it would be good to save the unnecessary object allocation here, by defining a:

    private static final Object[] EMPTY_KEYS_AND_VALUES = new Object[0];

at the top of the class, then doing:

    logInfo = EMPTY_KES_AND_VALUES;

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java [hunk 4]
```diff
@@ -912,6 +913,7 @@ protected RuntimeException mapAsyncToSyncException(@Nonnull Throwable ex) {
             } catch (TimeoutException ex) {
                 if (timer != null) {
                     timer.recordTimeout(event, startTime);
+                    throw asyncToSyncExceptionMapper.apply(new LoggableTimeoutException(ex, LogMessageKeys.TIME_LIMIT.toString(), timeout.getLeft(), LogMessageKeys.TIME_UNIT.toString(), timeout.getRight()), event);
```
Comment (scgray) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java]: No need to fix, but the `.toString()` is necessary for the `LogMessageKeys`.  The logging framework automatically does this.

Comment (dsimmen) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java]: Interesting that things were failing without that.
