### PR TITLE
Fixes #399: FDBRecordStore.deleteAllRecords enables disabled indexes

### LINKED ISSUE #399: FDBRecordStore.deleteAllRecords enables disabled indexes
Calling `FDBRecordStore.deleteAllRecords` on a record store wipes out the information in the `RecordStoreState` header. This means that all indexes are made `READABLE`. Most indexes should be readable anyway, so that's not a big deal, and `WRITE_ONLY` indexes are (presumably) write-only because they haven't been built yet, so marking them as `READABLE` now is...probably fine. (The newly readable index will, in fact, serve queries correctly.) However, `DISABLED` indexes will suddenly be enabled. I think the assumption should be that the user disabled the index for some reason (e.g., to decrease the write amplification associated with maintaining the index), so that seems wrong.

One solution would be to exclude the `RecordStoreState` range from the list of deleted ranges. Another would be to continue to delete it but to write the disabled indexes first.

### PR DESCRIPTION
**Pull request by alecgrieser**
The index state space is now excluded from `deleteAllRecords`. This means that the index state information is preserved after all records are deleted. The issue, #399, mentioned that in theory, this was the "right" thing to do for write-only indexes (under the assumption that they are write only just because no one has finished building them, and now that the store is empty, there isn't need to keep them write-only). I decided to keep it simple in this fix and have it just preserve all index states, which is easier to reason about.

@amouehsan, IIRC, I was under that impression that some of the index meta-data changes (in #520?) will end up using a different subspace or something within the Record Store keyspace. I think you'll also need to update this to also exclude that region if I understand how that is supposed to work.

This fixes #399.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 1]
```diff
@@ -1119,8 +1119,13 @@ public static void deleteStore(FDBRecordContext context, Subspace subspace) {
...
         preloadCache.invalidateAll();
         Transaction tr = ensureContextActive();
-        tr.clear(recordsSubspace().getKey(),
-                 getSubspace().range().end);
+
+        // Clear out all data except for the store header key and the index state space.
+        // Those two subspaces are determined by the configuration of the record store rather then
+        // the records.
+        Range indexStateRange = indexStateSubspace().range();
+        tr.clear(recordsSubspace().getKey(), indexStateRange.begin);
```
Comment (amouehsan) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: Is it right to assume that e.g., `indexStateSubspace().range().begin` is always < `indexRangeSubspace().range().begin`? If not, would it be better if we just go thru the `FDBRecordStoreKeyspace` enum members and clear subspaces one by one?  I'm asking this to see how it'll affect my change.

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: Hm, interesting. In some sense, that's a question about the leakiness of the abstraction, because it would be a format breaking (and therefore forbidden) change to reorder the values from that enum. I think that you can assume it's order, but it's also possible that there is a better way of doing it (and by better, I think the concern is only maintainability rather than, like, correctness or performance).

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java [hunk 2]
```diff
@@ -1254,7 +1254,7 @@ default boolean deleteRecord(@Nonnull Tuple primaryKey) {
     /**
      * Delete all the data in the record store.
      * <p>
-     * Everything except the store header is cleared from the database.
+     * Everything except the store header and index state information is cleared from the database.
```
Comment (nblintao) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java]: - I agree that it might be okay to simply including WriteOnly states to make the semantic simple. But this should be documented somewhere.

- Since `deleteAllRecords` does not delete index states anymore, should there be a new interface to delete all index states? Or do we already have one? And maybe we also need separate interfaces for the two states.

Comment (alecgrieser) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java]: Okay, I attempted to be more explicit about what happens to `WRITE_ONLY` indexes in the doc.

I think the correct way (after calling `deleteAllRecords`) of also clearing out any index states is to use `rebuildAllIndexes` if one wants to continue using the record store and to use `deleteStore` (instead of `deleteAllRecords`) if one doesn't. I've updated the docs with that; I also found a bug (#597) where we weren't updating the local record store state, so I have updated the tests to exercise that function more.
