### PR TITLE
Resolve #2537: IndexingMerger: If partition re-balancing fails, retry with fewer documents to move

### LINKED ISSUE #2537: if partition re-balancing fails, retry with fewer documents to move

### PR DESCRIPTION
**Pull request by jjezra**
This adds another fallback layer to IndexingMerger.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 1]
```diff
@@ -108,27 +112,70 @@ private CompletableFuture<Boolean> handleSuccess(final IndexDeferredMaintenanceC
...
+            giveUpMerging(mergeControl, e);
+        }
+        repartitionDocumentCount /= 2;
+        if (repartitionDocumentCount == 0) {
+            // Here: retry merge, but without partition re-balance
+            repartitionDocumentCount = -1;
+        }
+        if (LOGGER.isTraceEnabled()) {
+            LOGGER.trace(mergerLogMessage("IndexMerge: partition rebalance failure", mergeControl), e);
+        }
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:166]: I feel like this should be at least `DEBUG` level. 
```suggestion
        if (LOGGER.isDebugEnabled()) {
            LOGGER.debug(mergerLogMessage("IndexMerge: partition rebalance failure", mergeControl), e);
        }
```

Unless it's redundant, or would be logged many times during a deferred maintenance.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 2]
```diff
@@ -108,27 +112,70 @@ private CompletableFuture<Boolean> handleSuccess(final IndexDeferredMaintenanceC
...
+                break; // "A switch statement does not contain a break", croaks a grumpy pmdMain.
         }
         return AsyncUtil.READY_TRUE; // and retry
     }
 
+    private void handlePotentialRebalanceFailure(final IndexDeferredMaintenanceControl mergeControl, Throwable e) {
+        repartitionDocumentCount = mergeControl.getRepartitionDocumentCount();
+        if (repartitionDocumentCount == -1) {
+            // Here: failed, despite being set to skip. No recovery.
+            giveUpMerging(mergeControl, e);
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:157]: It seems like we should log this, or add it to the information logged when giving up.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java [hunk 3]
```diff
@@ -664,9 +669,6 @@ public CompletableFuture<Pair<Integer, Integer>> processPartitionRebalancing(@No
 
                     // get the N oldest documents in the partition (note N = (count of docs to move) + 1, since we need
                     // the (N+1)th doc's timestamp to update the partition's "from" field.
-                    final Integer repartitionDocumentCount = Math.min(
-                            Objects.requireNonNull(state.context.getPropertyStorage().getPropertyValue(LuceneRecordContextProperties.LUCENE_REPARTITION_DOCUMENT_COUNT)),
-                            indexPartitionHighWatermark);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java:669]: You dropped the fact that this takes the min of the `indexPartitionHighWatermark` and the provided document count.
It's probably not super important in practice, because your partition high-watermark should be much higher than not, and it allowed `LuceneIndexMaintenanceTest.randomizedRepartitionTest` to be more chaotic (none of the prb tests set the repartition-count higher than the partition high-watermark)

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java [hunk 4]
```diff
@@ -98,7 +98,7 @@ public final class LuceneRecordContextProperties {
     /**
      * Number of documents to move from a partition when its size exceeds {@link com.apple.foundationdb.record.lucene.LuceneIndexOptions#INDEX_PARTITION_HIGH_WATERMARK}.
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java:99]: Is it worth commenting that this should be an even power of 2?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java [hunk 5]
```diff
@@ -937,5 +939,70 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
         assertTrue(newLength < oldLength);
         assertTrue(timeCommitCount > 0);
     }
+
+    private static class TerribleRebanalceIndexMaintainer extends LuceneIndexMaintainer {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:943]:
```suggestion
    private static class TerribleRebalanceIndexMaintainer extends LuceneIndexMaintainer {
```

I'm also not sure that putting `Terrible` in here is super valuable, but it's not a big deal.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java [hunk 6]
```diff
@@ -937,5 +939,70 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+            }
+            if (documentCount > 2) {
+                throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+            }
+            return AsyncUtil.DONE;
+        }
+    }
+
+    @AutoService(IndexMaintainerFactory.class)
+    public static class TerribleRebanalceIndexMaintainerFactory implements IndexMaintainerFactory {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:969]:
```suggestion
    public static class TerribleRebalanceIndexMaintainerFactory implements IndexMaintainerFactory {
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 7]
```diff
@@ -108,27 +112,70 @@ private CompletableFuture<Boolean> handleSuccess(final IndexDeferredMaintenanceC
...
         }
-        // Here: this exception might be resolved by reducing the number of merges or forcing shorter intervals between auto-commits
-        if (mergeControl.getMergesTried() < 2) {
-            handleSingleMergeFailure(mergeControl, e);
-        } else {
-            handleMultiMergeFailure(mergeControl, e);
+        switch (lastStep) {
+            case REBALANCE:
+                // Here: this exception might be resolved by reducing the number of documents to move during rebalancing
+                handlePotentialRebalanceFailure(mergeControl, e);
```
Comment (ScottDugas) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:134]: nit: perhaps there's no need for `Potential` in this method name, it is known that there is a failure, and it was because of rebalance.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java [hunk 8]
```diff
@@ -937,5 +939,70 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+
+        @Nonnull
+        @Override
+        public IndexMaintainer getIndexMaintainer(@Nonnull IndexMaintainerState state) {
+            return new TerribleRebanalceIndexMaintainer(state);
+        }
+    }
+
+    @Test
+    void luceneOnlineIndexingTestTerribleRebalance() {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:990]: Can we have a test that covers the behavior of `shouldGiveRepartitionSecondChance`
I think it should be something where it maintains some state (`x`) and merge decreases `x`, and rebalance always fails if `x>10`, and succeeds with a count of 2 if `x < 10`, or something like that.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java [hunk 9]
```diff
@@ -937,5 +939,70 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+                ImmutableMap.of(IndexOptions.TEXT_TOKENIZER_NAME_OPTION, AllSuffixesTextTokenizer.NAME));
+
+        boolean needMerge = populateDataSplitSegments(index, 4, 1);
+        assertTrue(needMerge);
+        try (OnlineIndexer indexBuilder = OnlineIndexer.newBuilder()
+                .setRecordStore(recordStore)
+                .setIndex(index)
+                .build()) {
+            indexBuilder.mergeIndex(); // retries under the hood until document count reaches minimum
+            assertTrue(recordStore.getIndexDeferredMaintenanceControl().getRepartitionDocumentCount() <= 2);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:1003]: It probably doesn't make sense with this extending `LuceneIndexMaintainer`, but something to think about if the deferred maintenance gets more complicated, or ever gets decoupled from lucene:
It may make sense to have it track the `MergeControl` controls, and then we can assert about exactly what it got called with during the index build. In order to do that.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java [hunk 10]
```diff
@@ -717,6 +717,7 @@ protected TerribleMergingIndexMaintainer(final IndexMaintainerState state) {
         @Override
         public CompletableFuture<Void> mergeIndex() {
             final IndexDeferredMaintenanceControl mergeControl = state.store.getIndexDeferredMaintenanceControl();
+            mergeControl.setLastStep(IndexDeferredMaintenanceControl.LastStep.MERGE);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:720]: Note: at some point, outside the scope of this PR, we should rename this class to have the second `e` in `Lucene`

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 8 above)
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:990]: We should also have a test that just does the deferred maintenance, outside of an index build.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 2 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:157]: The information is there, I think. `giveUpMerging` should log the error, the last step, etc.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java (hunk 3 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LucenePartitioner.java:669]: Yes, I did think that this check is weird as the high-watermark is much higher. I'll add it for the tests. 
✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 5 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:943]: ✅

Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:943]: (The "Terrible" seems to be an ad-hoc description of a test maintainer that doesn't do its job...)

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 6 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:969]: ✅

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 7 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:134]: ✅ 
(Good point!)

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 8 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:990]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 9 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:1003]: Do you mean by using `timer`?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 10 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:720]: Oops. 
Changed it now ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 8 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:990]: Isn't that what this test does?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 11]
```diff
@@ -937,5 +941,146 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+            super(state, state.context.getExecutor());
+            this.state = state;
+        }
+
+        @Override
+        public CompletableFuture<Void> mergeIndex() {
+            final IndexDeferredMaintenanceControl mergeControl = state.store.getIndexDeferredMaintenanceControl();
+            if (isSecondPass) {
+                mergeControl.setLastStep(IndexDeferredMaintenanceControl.LastStep.REBALANCE);
+                gotSecondChance = true;
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1025]: I think this test would pass, if, after doing the merge, it continued to tell the indexer to skip.
Instead it should store the limit in the second chance, and assert that it is not negative.

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java (hunk 9 above)
Comment (ScottDugas) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LucenOnlineIndexingTest.java:1006]: No, I meant tracking the `MergeControl`, i.e.:
assert that it got called with:
| repartition limit | merge limit | result |
| -- | -- | -- |
| 0 | 0 | failure on repartition |
| 8 | 0 | failure on repartition |
| 4 | 0 | failure on repartition |
| 2 | 0 | failure on merge |
| 0 | 8 | failure on merge |
| 0 | 4 | success |
...

Or something like that.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java [hunk 12]
```diff
@@ -114,7 +114,9 @@ private CompletableFuture<Boolean> handleSuccess(final IndexDeferredMaintenanceC
         }
         // after a successful merge, reset the time quota and document count. They are unlikely to be applicable for the next merge.
         timeQuotaMillis = 0;
-        repartitionDocumentCount = 0;
+        if (repartitionDocumentCount > 0) {
+            repartitionDocumentCount = 0;
+        }
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:119]: * `shouldGiveRepartitionSecondChance` should have reset that. My typo. 
* Added an assertion to `TerribleRebalalce2ndChanceIndexMaintainer`. 
✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 13]
```diff
@@ -937,5 +941,146 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+            }
+            if (documentCount > 2) {
+                throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+            }
+            return AsyncUtil.DONE;
+        }
+    }
+
+    @AutoService(IndexMaintainerFactory.class)
+    public static class TerribleRebalalceIndexMaintainerFactory implements IndexMaintainerFactory {
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:971]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 14]
```diff
@@ -937,5 +941,146 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+                .setRecordStore(recordStore)
+                .setIndex(index)
+                .setMaxAttempts(1)
+                .build()) {
+            indexBuilder.mergeIndex(); // retries under the hood until document count reaches minimum
+            assertTrue(recordStore.getIndexDeferredMaintenanceControl().getRepartitionDocumentCount() <= 2);
+        }
+    }
+
+    private static class TerribleRebalalce2ndChanceIndexMaintainer extends LuceneIndexMaintainer {
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1010]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 15]
```diff
@@ -937,5 +941,146 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+            if (documentCount <= 0) {
+                mergeControl.setRepartitionDocumentCount(16);
+                throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+            }
+            throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+        }
+    }
+
+    @AutoService(IndexMaintainerFactory.class)
+    public static class TerribleRebalalce2ndChanceIndexMaintainerFactory implements IndexMaintainerFactory {
```
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1044]: ✅

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 16]
```diff
@@ -937,5 +941,147 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+                .setRecordStore(recordStore)
+                .setIndex(index)
+                .setMaxAttempts(1)
+                .build()) {
+            indexBuilder.mergeIndex(); // retries under the hood until document count reaches minimum
+            assertTrue(recordStore.getIndexDeferredMaintenanceControl().getRepartitionDocumentCount() <= 2);
+        }
+    }
+
+    private static class Terriblerebalnce2ndChanceIndexMaintainer extends LuceneIndexMaintainer {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1010]:
```suggestion
    private static class TerribleRebalance2ndChanceIndexMaintainer extends LuceneIndexMaintainer {
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java [hunk 17]
```diff
@@ -937,5 +941,147 @@ void testRecordUpdateReducedMergeForcingAgileTimeQuota() {
...
+            if (documentCount <= 0) {
+                mergeControl.setRepartitionDocumentCount(16);
+                throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+            }
+            throw new FDBException("transaction_too_old", FDBError.TRANSACTION_TOO_OLD.code());
+        }
+    }
+
+    @AutoService(IndexMaintainerFactory.class)
+    public static class Terriblerebalnce2ndChanceIndexMaintainerFactory implements IndexMaintainerFactory {
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1045]:
```suggestion
    public static class TerribleRebalance2ndChanceIndexMaintainerFactory implements IndexMaintainerFactory {
```

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (ScottDugas) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:119]: So, is there any point to the `if` block here?

**Review by ScottDugas — APPROVED** [review]
A couple minor changes, lets merge, and followup

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:119]: Yes. Unlike the regular indexer, that assumes correlation between "neighboring" records, this code assumes none for records that had been moved during repartitioning. Hence, if the number of moved records per single transaction was reduced in a previous repartitioning (because of failures), it will be reset back to default for the next one. 
@wshaib-apple is now working on code that will limit the total number of records to move in a single rebalance operation, his code will cause this function to return `AsyncUtil.READY_TRUE` (i.e. `hasMore`) when needed. So this reset is relevant for either a second chance or when only partial work was done.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java (hunk 16 above)
Comment (jjezra) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneOnlineIndexingTest.java:1010]: I'll fix this typo in a future PR. (Probably not worth creating a PR of its own)

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java:119]: Note that if the repartitioning failed twice it will not be retried again. We should probably look into it in the future.
