### PR TITLE
Resolve #2247: Re-word misleading error message "unable to build index

### LINKED ISSUE #2247: Re-word misleading error message "unable to build index"
This is triggered when `rebuildOrMarkIndex` fails.

### PR DESCRIPTION
**Pull request by jjezra**

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java [hunk 1]
```diff
@@ -3828,7 +3828,7 @@ protected CompletableFuture<Void> rebuildIndexes(@Nonnull Map<Index, List<Record
                             ),
                             exception -> {
                                 // If there is any issue, simply mark the index as disabled without blocking checkVersion
-                                logExceptionAsWarn(KeyValueLogMessage.build("unable to build index",
+                                logExceptionAsWarn(KeyValueLogMessage.build("unable to rebuild or mark index",
```
Comment (ohadzeliger) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java:3831]: I thought that we may be able to add some more info to the already existing message (e.g. for the cause of the failure)

**Review by ohadzeliger — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java (hunk 1 above)
Comment (jjezra) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java]: ✅

**Review by ohadzeliger — APPROVED** [review]
