### PR TITLE
Resolves #2923: Create a new version of AsyncToSync

### LINKED ISSUE #2923: Lucene to use a custom version of asyncToSync that does not inject exceptions
Since Lucene logic realizes Futures and uses the results for further logic, it needs to reason about the exceptions being thrown by the lower levels for these futures. The context's AsyncToSync implementation allows exceptions to be remapped which may hinder the ability to catch specific exceptions.

### PR DESCRIPTION
**Pull request by ohadzeliger**
The existing implementation of context AsyncToSync allows exceptions to be mapped to other exceptions. In order to be able to reason about the errors throws by futures when relalized by AsyncToSync this PR creates a new version of AsyncToSync, to be used by Lucene code, so that exception mapping is no longer taking place.
This is the first step in handling Lucene exceptions, the others being mapping to -and from- IOExceptions on Lucene code boundaries.

### CODE REVIEW

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+            try {
+                if (timeout != null) {
+                    return async.get(timeout.getDuration(), timeout.getTimeUnit());
+                } else {
+                    return async.get();
+                }
+            } catch (TimeoutException ex) {
+                if (timer != null) {
+                    timer.recordTimeout(event, startTime);
+                    throw new AsyncToSyncTimeoutException(ex.getMessage(), ex, LogMessageKeys.TIME_LIMIT.toString(), timeout.getDuration(), LogMessageKeys.TIME_UNIT.toString(), timeout.getTimeUnit());
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:101]: Why create a new `AsyncToSyncTimeoutException` instead of throwing `LoggableTimeoutException`?

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+                }
+                throw new AsyncToSyncTimeoutException(ex.getMessage(), ex);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:103]: I see that the `FDBDatabase.asyncToSync` does this too, but why does this only add the extra details if the timer is non-null?
The original PR (https://github.com/FoundationDB/fdb-record-layer/pull/664/files#diff-a2b46d3c7810aff21a344c3904a14d949eda54d0be86d34915f26ea01ce612c6R916) has no context

Either way, it seems best to minimize the changes here, and we can change that at a later time.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+        private final TimeUnit timeUnit;
+
+        public Timeout(final long duration, @Nonnull final TimeUnit timeUnit) {
+            this.duration = duration;
+            this.timeUnit = timeUnit;
+        }
+
+        public static Timeout of(final long duration, @Nonnull final TimeUnit timeUnit) {
+            return new Timeout(duration, timeUnit);
+        }
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:135]: Why have a public constructor _and_ factory method that are identical

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 1 above)
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:101]: Nit: For readability to ensure that there is a correct set of pairs, it would be good to wrap this line
```suggestion
                    throw new AsyncToSyncTimeoutException(ex.getMessage(), ex,
                            LogMessageKeys.TIME_LIMIT.toString(), timeout.getDuration(),
                            LogMessageKeys.TIME_UNIT.toString(), timeout.getTimeUnit());
```

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+import org.apache.commons.lang3.tuple.Pair;
+
+import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
+import java.util.concurrent.CompletableFuture;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+
+import static com.apple.foundationdb.record.lucene.LuceneRecordContextProperties.LUCENE_USE_LEGACY_ASYNC_TO_SYNC;
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:41]: I think it would be better to not statically import this. It's only used in one place, and it would be clearer as `LuceneRecordContextProperties.LUCENE_USE_LEGACY_ASYNC_TO_SYNC`

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java [hunk 5]
```diff
@@ -373,7 +378,7 @@ public <R> CompletableFuture<R> applyInRecoveryPath(Function<FDBRecordContext, C
                 future = function.apply(recoveryContext)
                         .whenComplete((result, ex) -> {
                             if (ex == null) {
-                                recoveryContext.commit();
+                                commit(recoveryContext);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java:381]: After this PR, at some point....
This was in existing code, but this probably shouldn't be calling `asyncToSync`, and instead should be doing
```
function.apply(recoveryContext)
    .thenCompose(recoveryContext.commitAsync)
    .whenComplete(() -> recoveryContext.close());
```

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java [hunk 6]
```diff
@@ -178,6 +179,10 @@ default <T> T getPropertyValue(@Nonnull RecordLayerPropertyKey<T> propertyKey) {
      */
     void setCommitCheck(Function<FDBRecordContext, CompletableFuture<Void>> commitCheck);
 
+    default void commit(@Nonnull FDBRecordContext context) {
+        LuceneConcurrency.asyncToSync(FDBStoreTimer.Waits.WAIT_COMMIT, context.commitAsync(), context);
+    }
+
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java:185]: After this PR, at some point....
I _feel_ like instead of calling `asyncToSync` `AgilityContext` should just have asynchronous methods, and callers can use `asyncToSync`.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 7]
```diff
@@ -405,7 +406,7 @@ void flakyMerge(boolean isGrouped,
                     assertFalse(requireFailure && i < 15, i + " merge should have failed");
                     success = true;
                 } catch (RecordCoreException e) {
-                    final LoggableTimeoutException timeoutException = findTimeoutException(e);
+                    final LoggableKeysAndValues<? extends Exception> timeoutException = findTimeoutException(e);
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:409]: If the new `asyncToSync` is changed to throw the same exception, this should be changed back.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 8]
```diff
@@ -959,15 +959,18 @@ private void createComplexRecords(int count,
...
 
-    private static LoggableTimeoutException findTimeoutException(final RecordCoreException e) {
+    private static LoggableKeysAndValues<? extends Exception> findTimeoutException(final RecordCoreException e) {
         Map<Throwable, String> visited = new IdentityHashMap<>();
         ArrayDeque<Throwable> toVisit = new ArrayDeque<>();
         toVisit.push(e);
         while (!toVisit.isEmpty()) {
             Throwable cause = toVisit.removeFirst();
             if (!visited.containsKey(cause)) {
+                // TODO: This should eventually be removed since LoggableTimeoutException would not be thrown
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:969]: Why not remove now?

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java [hunk 9]
```diff
@@ -405,7 +406,7 @@ void flakyMerge(boolean isGrouped,
                     assertFalse(requireFailure && i < 15, i + " merge should have failed");
```
Comment (ScottDugas) [inline fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:406]: Have you run this and `LuceneIndexTest` with `LUCENE_USE_LEGACY_ASYNC_TO_SYNC` defaulting to `false`, so that all the code uses the new path?

**Review by ScottDugas — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java]: `LoggableTimeoutException` is a Checked Exception, and I needed a subclass of `RecordCoreException` to throw from the `asyncToSync`. The original code in `FDBException.wrapExceptions` would have wrapped this in a `RecordCoreException`.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 2 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:103]: Yeah, that was the thinking on my end too. I'll collect the followups for future implementation.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 1 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java]: Done.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 4 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java]: Done.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java (hunk 5 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/AgilityContext.java:381]: Added to future issues.
Together with `LucenePartitioner`:
```
public PartitionedQueryHint selectQueryPartition(@Nonnull Tuple groupKey, @Nullable LuceneScanQuery luceneScanQuery) {
        return LuceneConcurrency.asyncToSync(WAIT_LOAD_LUCENE_PARTITION_METADATA, selectQueryPartitionAsync(groupKey, luceneScanQuery), state.context);
}
```

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 8 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java]: This would still be thrown when the property is set to use the legacy asyncToSync. Changed the comment.

File: fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java (hunk 9 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java:406]: Initially planned to add tests with the second PR, but this is a good idea. Done.

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java [hunk 10]
```diff
@@ -0,0 +1,162 @@
...
+        }
+    }
+
+    private LuceneConcurrency() {
+    }
+
+    /**
+     * A representation of a timeout value: A duration and a time unit.
+     */
+    public static class Timeout {
```
Comment (MMcM) [inline fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:123]: I am not exactly opposed to the creation of this new class, but I see that the only(?) usage constructs one from separate values retrieved via an API that returns `Pair` and then deconstructs it just a few lines later.

Would it make more sense to push this into `getAsyncToSyncTimeout` in place of the `Pair`? I guess that's an incompatible change.

Would it make sense to also include the `Event`, so that it's more scoped to the abstracts immediately here?

**Review by MMcM — CHANGES_REQUESTED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 10 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java:123]: The original idea behind this class was the ability to add a version of `asyncToSync` that could take the timeout value without consulting the `FDBDatabase`, but that did not pan out because it is incompatible with existing tests and would not end up being useful. Then I left the class in place as it offered some indication of the constituents of the timeout (as opposed to `Pair.getRight` and `Pair.getLeft`), but if that is causing confusion, I will remove it.

**Review by ScottDugas — APPROVED** [review]

File: fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java (hunk 10 above)
Comment (ohadzeliger) [reply fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneConcurrency.java]: Done (Removed `Timeout` class)

**Review by MMcM — APPROVED** [review]

**Review by ScottDugas — APPROVED** [review]
