### PR TITLE
Fix unstable in hash code of `RecordQueryAbstractDataModificationPlan`

### LINKED ISSUE #2325: `RecordQueryAbstractDataModificationPlan` hash code is not stable
The hash code calculation of the `RecordQueryAbstractDataModificationPlan` is not stable. This is causing discrepancies in the optimiser choosing optimal `UPDATE` plans pseudo-randomly when multiple equivalent alternatives exist and the plan hash code is used as a costing tie-breaker.

### PR DESCRIPTION
**Pull request by hatyo**
The hash code calculation of the `RecordQueryAbstractDataModificationPlan` is not stable. This is causing discrepancies in the optimiser choosing optimal `UPDATE` plans pseudo-randomly when multiple equivalent alternatives exist and the plan hash code is used as a costing tie-breaker.

This happens because the `MessageHelpers#CoercionTrieNode` class does not override `equals` and `hashCode`, despite it being used in `computeHashCodeWithoutChildren` of `RecordQueryAbstractDataModificationPlan`.

The provided fix implements `hashCode` and `equals` properly for this class, and adds a number of unit tests for equality and hash code calculation for `MessageHelpers#CoercionTrieNode` and `MessageHelpers#TransformationTrieNode`, it also adds an integration test for that examines the stability of plan hash of an `UPDATE` plan (which leverages the `RecordQueryAbstractDataModificationPlan` physical operator).

This fixes #2325.

### CODE REVIEW

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/TrieNode.java [hunk 1]
```diff
@@ -77,4 +78,22 @@ public Collection<T> values() {
                 .flatMap(trie -> trie.getValue() == null ? Stream.of() : Stream.of(trie.getValue()))
                 .collect(ImmutableList.toImmutableList());
     }
+
+    @Override
+    public boolean equals(final Object other) {
+        if (this == other) {
+            return true;
+        }
+        if (!(other instanceof TrieNode)) {
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/TrieNode.java:87]: Could this compare `getClass` instead and eliminate the need for the subclass to override?

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java [hunk 2]
```diff
@@ -579,5 +576,19 @@ public CoercionTrieNode(@Nullable final BiFunction<Descriptors.Descriptor, Objec
         public CoercionTrieNode getThis() {
             return this;
         }
+
+        @Override
+        public boolean equals(final Object other) {
+            if (this == other) {
+                return true;
+            }
+            if (!(other instanceof CoercionTrieNode)) {
```
Comment (MMcM) [inline fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java:585]: This is the only difference, right?

**Review by MMcM — CHANGES_REQUESTED** [review]

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/TrieNode.java (hunk 1 above)
Comment (hatyo) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/util/TrieNode.java]: Done.

File: fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java (hunk 2 above)
Comment (hatyo) [reply fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java]: Yes, correct, I refactored it accordingly.

**Review by MMcM — APPROVED** [review]
